bulk commit week 19-20 2025

diff --git a/modules/binaries b/modules/binaries
--- a/modules/binaries
+++ b/modules/binaries
@@ -11,121 +11,204 @@ ${BINARIES_BASHLIB:-false} && return
 BINARIES_BASHLIB=:
 
 for x in B BINARY D F J M PHP T V; do declare -gA $x 2>${NUL:=/dev/null} || declare -A $x; done
-declare -i BINARIES_LIB_VERSION BINARY_ARRAY_VERSION
-
-__libversion__
-BINARY_ARRAY_VERSION=0
-
-[[ "$-" =~ x ]] && { set +x; B[binaries_debugx]=:; }
-
-declare -a paths used_binaries binaries
-# declare -gA BINARY 2>$NUL || declare -A BINARY
-# declare -gA PHP 2>$NUL || declare -A PHP
 PHP[vregex]='(5\.6|[78]\.[01234])'
 PHP[vextglob]='*@(*5\.6*|*[78]\.[01234]*)*'
 declare -p PHP > "${F[php]:="${D[vt]}/php"}"
+# Create a nameref for BINARY named X
+declare -gn X=BINARY &>$NUL || declare -n X=BINARY
+declare -i BINARIES_LIB_VERSION BINARY_ARRAY_VERSION
+__libversion__
+BINARY_ARRAY_VERSION=0
 
-F[binary]="${D[vt]}/binary"
-[ -f "${F[binary]}" ] && . "${F[binary]}"
-
-(( BINARIES_LIB_VERSION == BINARY_ARRAY_VERSION )) || BINARY=()
-
-reload_binaries(){
-    [ -f "${F[binary]:=${D[vt]}/binary}" ] && ${BINARY[rm]} -f -- "${F[binary]}"
-    FILTER_BASHLIB=_ BINARIES_BASHLIB=_
-    . <(lrequire filter)
+binaries_is_func_(){ 
+    d=$(declare -f $1) || return
+    d=${d//$'\n'/}
+    [[ ${d// /} != "$1(){:}" ]]
 }
 
-map_paths(){
-    # standard paths take precedence
-    PATH=$(printf "%s" "/usr/sbin:/usr/bin:/sbin:/bin:$PATH" | ${BINARY[gawk]} -v RS=: -v ORS=: '!seen[$0]++' | ${BINARY[sed]} 's/::/:/g;s/:$//')
-    mapfile -t paths< <(printf "%s\n" ${PATH//:/ })
+binaries_reload(){
+    local msg
+    msg="$(q2 fn_ln 1)rebuild BINARY array with newly installed binaries"
+    binaries_is_func_ mh && mh "$msg" || log "$msg"
+    [ -f "${F[binary]:=${D[vt]}/binary}" ] && ${C[r]} "${F[binary]}"
+    BINARIES_BASHLIB=_
+    tabula_rasa(){ :; }
+    . <(lrequire binaries)
 }
 
-nullglob_path(){
+# fallback for realpath/readlink using bash builtins
+binaries_realpath(){
+    local p msg
+    p="$1"
+    if [[ -d "$p" ]]; then
+        (cd -P "$p" 2>$NUL && printf '%s\n' "$PWD")
+    elif [[ -e "$p" ]]; then
+        (cd -P "${p%/*}" 2>$NUL && printf '%s/%s\n' "$PWD" "${p##*/}")
+    else
+        msg="binaries_realpath(): unresolvable path $p"
+        binaries_is_func_ mh && mh "$msg" || log "$msg"
+    fi
+}
+
+binaries_map_paths(){
+    local raw_paths p
+    raw_paths="/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
+    printf "%s\n" ${raw_paths//:/ } | while IFS= read -r p; do
+        [[ -n "$p" ]] || continue # avoid empty entries
+        # resolve symlinks and canonicalize
+        binaries_realpath "$p" 2>$NUL || continue
+    done | ${BINARY[gawk]} '!seen[$0]++'
+}
+
+# return only the paths from the used_binaries array if existent
+binaries_used_paths(){
+    local path name
+    local -a binaries_used paths
+__binaries_used__
+    mapfile -t paths < <(binaries_map_paths)
+    for path in "${paths[@]}"; do
+        for name in "${binaries_used[@]}"; do
+            [[ -e $path/$name ]] && printf '%s\n' $path/$name
+        done
+    done
+}
+
+# return all existent binariy paths
+binaries_nullglob_paths(){
     local old_nullglob path binary
-    local -a results
-    map_paths
+    local -a paths
+    mapfile -t paths < <(binaries_map_paths)
     old_nullglob=$(shopt -p nullglob || :)
     shopt -s nullglob
     for path in "${paths[@]}"; do
         for binary in "$path"/*; do
-            results+=("$binary")
+            printf '%s\n' $binary
         done
     done
     [[ -n $old_nullglob ]] && $old_nullglob || shopt -u nullglob
-    printf '%s\n' "${results[@]}"
 }
 
-extglob_path(){
+# return all existing paths matching ${PHP[vextglob]}
+binaries_extglob_paths(){
     local path binary
-    local -a results
-    map_paths
+    local -a paths
+    mapfile -t paths < <(binaries_map_paths)
     for path in "${paths[@]}"; do
         for binary in "$path"/${PHP[vextglob]}; do
-            [[ -e "$binary" ]] && results+=("$binary")
+            [[ -e "$binary" ]] && printf '%s\n' $binary
         done
     done
-    printf '%s\n' "${results[@]}"
 }
 
-if [[ -z ${BINARY[env]} ]]; then
-    BINARY[env]="$(command -v env)"
-    for x in gawk sed; do
-        if [ -x "$(command -v $x)" ]; then
-            BINARY[$x]="${BINARY[env]} LC_MESSAGES=C $(command -v $x)" &>$NUL
-        else
-            echo -e "\e[31mERROR: no '$x' binary or '$x' not executable\e[0m" > ${TTY:=/dev/tty}
-            [ -t 0 ] || exit 1
-        fi
-    done
-    # binaries that need LC_ALL=C
-    for x in lastlog; do
-        if [ -x "$(command -v $x)" ]; then
-            BINARY[$x]="${BINARY[env]} LC_ALL=C $(command -v $x)" &>$NUL
-        fi
-    done
-    # binaries that need LC_ALL=C.UTF-8
-    for x in add-apt-repository gpg; do
-        if [ -x "$(command -v $x)" ]; then
-            BINARY[$x]="${BINARY[env]} LC_ALL=C.UTF-8 $(command -v $x)" &>$NUL
-        fi
-    done
-
-__used_binaries__
-
-    mapfile -t binaries < <(nullglob_path)
-
+binaries_load_php(){
+    # allways load actual php versions because they may have been newly installed
+    local -a binaries
+    shopt -s extglob
+    mapfile -t binaries < <(binaries_extglob_paths)
+    shopt -u extglob
     for x in "${binaries[@]}"; do
-        [ -z "${BINARY[${x##*/}]}" ] || continue
+        [ -z "${BINARY[${x##*/}]:-}" ] || continue
         [ -x "$x" ] || continue
-        [[ " ${used_binaries[@]} " =~ " ${x##*/} " ]] || continue
+        [[ "${x##*/}" =~ ^php(-config|-fpm|ize)?${PHP[vregex]}$ ]] || continue
         BINARY[${x##*/}]="${BINARY[env]} LC_MESSAGES=C $x" &>$NUL
     done
+}
+
+binaries_extra_treatments(){
+    # fallback to function if ansifilter binary is not installed
+    : ${BINARY[ansifilter]:=filter_ansi} &>$NUL
     # xmlstarlet invocation https://xmlstar.sourceforge.net/doc/UG/xmlstarlet-ug.html#idm47077139670224
-    [ -z "${BINARY[xmlstarlet]}" ] || BINARY[xmls]="${BINARY[xmlstarlet]} sel -B -t" &>$NUL
+    [ -z "${BINARY[xmlstarlet]:-}" ] || BINARY[xmls]="${BINARY[xmlstarlet]} sel -B -t" &>$NUL
+}
+
+# dispatcher function.for "used" and "nullglob" (all) pathes
+binaries_load_(){
+    local -a binaries
+    mapfile -t binaries < <(binaries_$1_paths)
+    for x in "${binaries[@]}"; do
+        [[ -z ${BINARY[${x##*/}]:-} ]] || continue
+        [[ -x $x ]] || continue
+        BINARY[${x##*/}]="${BINARY[env]} LC_MESSAGES=C $x" &>$NUL
+    done
+}
+
+binaries_file_create(){
+    (   echo "BINARY_ARRAY_VERSION=$BINARIES_LIB_VERSION"
+        declare -p BINARY
+        declare -p X
+    ) > "${F[binary]}"
+    q0 ${BINARY[chmod]} 666 "${F[binary]}" "${F[php]}"
+}
+
+binaries_error(){
+    local msg
+    msg="$(q2 fn_ln 2)ERROR: no '$1' binary or '$1' not executable"
+    binaries_is_func_ mh && mh "$msg" || log "$msg"
+    echo -e "\e[31mERROR: no '$1' binary or '$1' not executable\e[0m" > ${TTY:=/dev/tty}
+    [ -t 0 ] || exit 1
+}
+
+# bootstrap
+binaries_bootstrap(){
+    local msg bb
+    if [[ -z ${BINARY[env]:-} ]]; then
+        if binaries_is_func_ tabula_rasa; then
+            tabula_rasa # force a fresh download of all modules
+            msg="$(q2 fn_ln 1)make tabula_rasa"
+            binaries_is_func_ mh && mh "$msg" || log "$msg"
+        fi
+        BINARY[env]="$(binaries_realpath "$(command -v env)")"
+        # this 'for bb in ..; do' patterns are evaluated by the 'binaries_exceptions' function during build process
+        for bb in gawk; do
+            if [ -x "$(command -v $bb)" ]; then
+                BINARY[$bb]="${BINARY[env]} LC_ALL=C $(binaries_realpath $(command -v $bb))" &>$NUL
+            else
+                binaries_error "$bb"
+                return 1
+            fi
+        done
+        # binaries that need LC_ALL=C
+        for bb in grep lastlog sed; do
+            if [ -x "$(command -v $bb)" ]; then
+                BINARY[$bb]="${BINARY[env]} LC_ALL=C $(binaries_realpath $(command -v $bb))" &>$NUL
+            
+            else
+                msg="$(q2 fn_ln 1)no '$1' binary or '$1' not executable"
+                binaries_is_func_ mh && mh "$msg" || log "$msg"
+            fi
+        done
+        # binaries that need LC_ALL=C.UTF-8
+        for bb in add-apt-repository gpg; do
+            if [ -x "$(command -v $bb)" ]; then
+                BINARY[$bb]="${BINARY[env]} LC_ALL=C.UTF-8 $(binaries_realpath $(command -v $bb))" &>$NUL
+            else
+                msg="$(q2 fn_ln 1)no '$1' binary or '$1' not executable"
+                binaries_is_func_ mh && mh "$msg" || log "$msg"
+            fi
+        done
+    else
+        return 1
+    fi
+}
+
+[[ "$-" =~ x ]] && { set +x; B[binaries_debugx]=:; } || :
+
+F[binary]="${D[vt]}/binary"
+[ -f "${F[binary]}" ] && . "${F[binary]}"
+
+if (( BINARIES_LIB_VERSION != BINARY_ARRAY_VERSION )); then
+    if binaries_is_func_ tabula_rasa; then
+        msg="$(q2 fn_ln 1)the binary-path array is outdated"
+        binaries_is_func_ mh && mh "$msg" || log "$msg"
+        unset msg
+    fi
+    BINARY=()
 fi
 
-# allways load actual php versions because they may have been newly installed
-shopt -s extglob
-mapfile -t binaries < <(extglob_path)
-shopt -u extglob
-
-for x in "${binaries[@]}"; do
-    [ -z "${BINARY[${x##*/}]}" ] || continue
-    [ -x "$x" ] || continue
-    [[ "${x##*/}" =~ ^php(-config|-fpm|ize)?${PHP[vregex]}$ ]] || continue
-    BINARY[${x##*/}]="${BINARY[env]} LC_MESSAGES=C $x" &>$NUL
-done
-unset -v used_binaries binaries
-echo "BINARY_ARRAY_VERSION=$BINARIES_LIB_VERSION" > "${F[binary]}"
-declare -p BINARY >> "${F[binary]}"
-q0 ${BINARY[chmod]} 666 "${F[binary]}" "${F[php]}"
-
-# Create a nameref for BINARY named X
-declare -n X=BINARY &>$NUL
-declare -p X >> "${F[binary]}"
+binaries_bootstrap && binaries_load_ used && binaries_extra_treatments
+binaries_load_php
+binaries_file_create
 
 [[ "$(type -t req)" == function ]] && . <(req backcomp 2>$NUL)
 
-${B[binaries_debugx]:-false} && set -x
+${B[binaries_debugx]:-false} && set -x || :
diff --git a/modules/nc/first_run b/modules/nc/first_run
--- a/modules/nc/first_run
+++ b/modules/nc/first_run
@@ -12,22 +12,23 @@ NC_FIRST_RUN_BASHLIB=:
 
 . <(lrequire httpd)
 
+first_run_register_nc_dir(){
+    local dir
+    dir="$1"
+    mh "vdir: $dir"
+    setvdir v "$dir"
+    NC[d]="$dir"
+    declare -p NC > "${F[nc]}"
+    ${X[chmod]} 666 "${F[nc]}"
+    f
+    o2; echo "- $(lG)first run wizard completed successfully. Please start script again"; N
+    o2; echo "- $(lG)No further root rights are required to use the script except for updating."; N
+    f
+    exit 0
+}
+
 first_run(){
     te1
-
-    finish(){
-        mh "vdir: $1"
-        setvdir v "$1"
-        NC[d]="$1"
-        declare -p NC > "${F[nc]}"
-        ${X[chmod]} 666 "${F[nc]}"
-        f
-        o2; echo "- $(lG)first run wizard completed successfully. Please start script again"; N
-        o2; echo "- $(lG)No further root rights are required to use the script except for updating."; N
-        f
-        exit 0
-    }
-
     local p h
     local -l ans num
     local -i c2 i
@@ -60,7 +61,7 @@ first_run(){
             read -rsn 1 ans; te1
             case ${ans:-y} in
                 q)  exit 0      ;;
-                y)  finish "$p" ;;
+                y)  first_run_register_nc_dir "$p" ;;
                 n)  break       ;;
                 *)  printf "$invi Please enter $(box y), $(box n) or $(q2q) "
             esac
@@ -101,7 +102,7 @@ first_run(){
                             q)  exit 0      ;;
                             h)  break       ;;
                             n)  continue    ;;
-                            y)  finish "$p" ;;
+                            y)  first_run_register_nc_dir "$p" ;;
                             *)  printf "$invi Please enter $(box y), $(box n), $(box h) or $(q2q) "
                         esac
                     done
@@ -119,7 +120,7 @@ first_run(){
         te1
         cursor_ hide
         [ "${p,}" = "q" ] && exit 0
-        [ -f "$p/occ" ] && finish "$p" || echo "$(Pbg)  * I can not detect a Nextcloud installation in \"$p\" $(N)"
+        [ -f "$p/occ" ] && first_run_register_nc_dir "$p" || echo "$(Pbg)  * I can not detect a Nextcloud installation in \"$p\" $(N)"
     done
 }
 # COMMENT -->
diff --git a/modules/php/extensions b/modules/php/extensions
--- a/modules/php/extensions
+++ b/modules/php/extensions
@@ -28,6 +28,17 @@ SAPI=(
     [embed]="libphp@VER@-embed"
     [phpdbg]="php@VER@-phpdbg"
 )
+# TODO 1 -->
+#q2 declare -Ag SAPI_BIN || declare -A SAPI_BIN
+#SAPI_BIN=(
+#    [apache2]="libapache2-mod-php@VER@"
+#    [fpm]="/usr/sbin/php-fpm@VER@"
+#    [cli]="/usr/bin/php@VER@"
+#    [cgi]="php@VER@-cgi"
+#    [embed]="libphp@VER@-embed"
+#    [phpdbg]="/usr/bin/php-phpdbg@VER@"
+#)
+# TODO <-- 1
 q2 declare -Ag DESCR || declare -A DESCR
 DESCR=(
     [apache2]="Apache 2.0 Handler SAPI"
@@ -59,6 +70,7 @@ DESCR=(
     [opcache]="Zend OpCache module for PHP"
     [pgsql]="PostgreSQL module for PHP"
     [pq]="PostgreSQL client library (libpq) binding for PHP"
+    [pspell]="pspell module for PHP"
     [readline]="readline module for PHP"
     [redis]="PHP extension for interfacing with Redis"
     [smbclient]="PHP wrapper for libsmbclient"
@@ -133,40 +145,46 @@ extension_include_dir_of_(){
     echo "/usr/include/php/${EXG[$pv]%%;*}/ext"
 }
 
-detect_and_assign_extensions(){
-    assign(){
-        local dpkg_package phpregex
-        if [ "${search:-}" = 'apache2' ]; then
-            phpregex="libapache2-mod-php${PHP[vregex]}"
-        else
-            phpregex="php"
-        fi
+# sub function from 'detect_and_assign_extensions()'
+_assign(){
+    [[ -f "${F[php]:=${D[vt]}/php}" ]] && . "${F[php]}"
+    local -n _search=$1
+    local -n _exts_dpkg=$2
+    local dpkg_package phpregex
+    if [[ ${_search:-} = apache2 ]]; then
+        phpregex="libapache2-mod-php${PHP[vregex]}"
+    else
         spinner C " . assign detected extensions to their corresponding package ." &
-        for dpkg_package in $(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*'$phpregex'/{print $2}'); do
-            declare -ga ${dpkg_package//[.-]/_}
-            mapfile -t "${dpkg_package//[.-]/_}"< <(${X[dpkg]} -L $dpkg_package|${X[grep]} "\.so$")
-            mapfile -t exts_dpkg< <(p_nosort ${exts_dpkg[@]};${X[dpkg]} -L $dpkg_package|${X[grep]} "\.so$"|${X[sort]})
-        done
-        kill_spinner
-    }
-    [ -f "${F[php]:="${D[vt]}/php"}" ] && . "${F[php]}"
+        phpregex="php"
+    fi
+    for dpkg_package in $(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*'$phpregex'/{print $2}'); do
+        declare -ga ${dpkg_package//[.-]/_} # declare array globaly
+        mapfile -t "${dpkg_package//[.-]/_}" < <(${X[dpkg]} -L $dpkg_package | ${X[grep]} "\.so$")
+        ${B[trace]:-_} && log_trace "$(declare -p ${dpkg_package//[.-]/_})"
+        $3 && mapfile -t _exts_dpkg < <(p_nosort ${_exts_dpkg[@]}; ${X[dpkg]} -L $dpkg_package | ${X[grep]} "\.so$" | ${X[sort]}) || :
+    done
+    [[ ${_search:-} = apache2 ]] || kill_spinner
+}
+
+detect_and_assign_extensions(){
     local search pv
     local -a exts_all exts_dpkg
-    [[ "$@" =~ apache2 ]] && search=apache2
+    [[ "$@" =~ apache2 ]] && search=apache2 || search=''
     if [[ "$@" =~ assign ]]; then
-        assign
+        _assign search exts_dpkg _
     else
         spinner C " . detect actually installed extensions ." &
         for pv in $(${X[phpquery]} -V); do
-            mapfile -t exts_all< <(p_nosort ${exts_all[@]};detect_extensions_in_ "/usr/lib/php/${EXG[$pv]%%;*}")
+            mapfile -t exts_all < <(p_nosort ${exts_all[@]};detect_extensions_in_ "/usr/lib/php/${EXG[$pv]%%;*}")
         done
         kill_spinner
-        assign
+        _assign search exts_dpkg :
         # EXTENSIONS_INSTALLED_BY_ADMIN
         spinner C " . detect extensions installed by admin ." &
         ${B[verbose]:-_} && echo "$(pf)Extensions installed by admin = difference between installed by dpkg and all extensions.."
-        mapfile -t EXTS_ADMIN< <(${X[comm]} -23 <(p_sort ${exts_all[@]}) <(p_sort ${exts_dpkg[@]}))
-        (( ${#EXTS_ADMIN[@]} )) && mapfile -t EXTS_ADMIN< <(p_sort_trim ${EXTS_ADMIN[@]})
+        mapfile -t EXTS_ADMIN < <(${X[comm]} -23 <(p_sort ${exts_all[@]}) <(p_sort ${exts_dpkg[@]}))
+        (( ${#EXTS_ADMIN[@]} )) && mapfile -t EXTS_ADMIN < <(p_sort_trim ${EXTS_ADMIN[@]})
+        ${B[trace]:-_} && log_trace "$(declare -p EXTS_ADMIN)"
         kill_spinner
     fi
 }
@@ -264,25 +282,31 @@ ext_state(){
     nonullglob "$vlpm/*" || return
     case "$1" in
         cleanup)
+            kill_spinner
+            cursor_ hide
+            spinner C " . etx_state() cleanup orphaned entries from extensions state registry ." &
             for dir in $vlpm/*; do
-                [[ -d "$dir" && ! "$(${X[phpquery]} -V)" =~ ${dir##*/} ]] && cleanup "$dir"
+                [[ -d $dir && ! "$(${X[phpquery]} -V)" =~ ${dir##*/} ]] && cleanup "$dir" || :
             done
             return
             ;;
         fix)
-            [ -f "${F[php]:="${D[vt]}/php"}" ] && . "${F[php]}"
+            kill_spinner
+            cursor_ hide
+            spinner C " . etx_state() fix extensions state registry /var/lib/php/modules ." &
+            [[ -f "${F[php]:=${D[vt]}/php}" ]] && . "${F[php]}"
             for mod in $(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i\s+[^\s]*php'${PHP[vregex]}'/{print $2}'); do
                 for pv in $(${X[phpquery]} -V); do
-                    [ "${mod%-*}" = "php$pv" ] && mod="${mod#*-}" || continue
+                    [[ ${mod%-*} = php$pv ]] && mod="${mod#*-}" || continue
                     registry_dir="$vlpm/$pv/registry"
-                    [ -d "$registry_dir" ] || mkdir -p "$registry_dir"
+                    [[ -d $registry_dir ]] || ${X[mkdir]} -p "$registry_dir"
                     for sapi in $(${X[phpquery]} -v $pv -S); do
                         state_dir="$vlpm/$pv/$sapi"
-                        if [ -f "$state_dir/enabled_by_admin/$mod" ]; then
+                        if [[ -f "$state_dir/enabled_by_admin/$mod" ]]; then
                             cleanup "$state_dir/enabled_by_admin/$mod"
-                            [ -d "$state_dir/enabled_by_maint" ] || mkdir -p "$state_dir/enabled_by_maint"
+                            [[ -d $state_dir/enabled_by_maint ]] || ${X[mkdir]} -p "$state_dir/enabled_by_maint"
                             touch "$state_dir/enabled_by_maint/$mod"
-                            [ -f "$registry_dir/$mod" ] || touch "$registry_dir/$mod"
+                            [[ -f "$registry_dir/$mod" ]] || touch "$registry_dir/$mod"
                         fi
                     done
                 done
diff --git a/modules/spinner b/modules/spinner
--- a/modules/spinner
+++ b/modules/spinner
@@ -41,7 +41,7 @@ spinner(){
     ${B[verbose]:-_} || ${B[trace]:-_} || ${B[debug]:-_} && { shift; (($#)) && echo "$@"; return 0; }
 
 #    ONLY USE THIS FOR DEBUGING: THE AMOUNT OF OUTPUT IS HUGE!
-#    mh "$(funcname_and_lineno 1)$BASHPID:$(funcname_and_lineno) $@"
+#    mh "$(fn_ln 1)$BASHPID:$(fn_ln) $@"
     # if not started in background, return imediately, since otherwise the spinner would be eternal
     (( BASHPID == M[pid] )) && return 0
 
@@ -87,7 +87,7 @@ spinner(){
     cursor_ hide # hide cursor
     echo -n "$cursor_status" > "${F[cursor]}"
 
-    tput rmam   # Disable automatic line wrapping
+    ${X[tput]} rmam   # Disable automatic line wrapping
 
     $color
     (( $# )) && echo "$@"
@@ -127,10 +127,11 @@ spinner(){
 # kill and clean up  spinner:
 kill_spinner(){
     # there is nothing to kill while in verbose/trace/debug mode
-    ${B[verbose]:-_} || ${B[trace]:-_} || ${B[debug]:-_} && return 0
+    ${B[verbose]:-_} || ${B[trace]:-_} || ${B[debug]:-_} && return 1
 
     local cursor_status
     local -i ct pid
+    local -A bool
 
     cursor_status='show'
 
@@ -138,16 +139,18 @@ kill_spinner(){
     ${X[sleep]} .08
     # Wait until the spinner PID file exists (max. ~500ms wait)
     ct=0
+    [[ "$-" =~ e ]] && { set +e; bool[errexit]=:; } || :
     until [[ -f "${F[spinner_pid]}" ]]; do
-        (( ct > 200 )) && return 0
+        (( ct > 200 )) && return 1
         (( ct++ ))
         ${X[sleep]} 0.001
     done
+    ${bool[errexit]:-_} && set -e || :
 
 #    pid="$(${X[cat]} "${F[spinner_pid]}")"
     read -r pid < "${F[spinner_pid]}"
 #    (( pid )) || return 1
-    (( pid )) || return 0
+    (( pid )) || return 1
     if [[ -f "${F[cursor]}" ]]; then
         if ${X[grep]} -qsw 'hide' "${F[cursor]}"; then
             cursor_status='hide'
@@ -155,7 +158,7 @@ kill_spinner(){
     fi
 
     # Attempt graceful termination: send 15 - SIGTERM to the spinner process.
-    kill -TERM "$pid" &>$NUL
+    kill -TERM "$pid" &>$NUL || :
 
     # Wait until the process terminates (max ~5 seconds)
     local wait_timeout=50
@@ -172,12 +175,17 @@ kill_spinner(){
 
     # Final reset actions:
     N                        # Reset any ansi color code
-    tput smam                # Re-enable automatic line wrapping
-    te0                      # Move one line up, deleting each line
+    ${X[tput]} smam                # Re-enable automatic line wrapping
+#    te0                      # Move one line up, deleting each line
+    te1                      # Delete line
     cursor_ "$cursor_status" # Restore original cursor state
 
     # Remove the PID file
-    cleanup "${F[spinner_pid]}"
+#    cleanup "${F[spinner_pid]}"
 
     return 0
+}
+
+kill_spinner_te0(){
+    kill_spinner && te0 || :
 }
