build(binaries): only load used binaries in asoc array X
- write BINARY array to file in D[vt]
- add asoc array PHP
- get rid of dependency of ccdiff

diff --git a/modules/binaries b/modules/binaries
--- a/modules/binaries
+++ b/modules/binaries
@@ -10,60 +10,106 @@ __license__
 ${BINARIES_BASHLIB:-false} && return
 BINARIES_BASHLIB=:
 
+__libname__
+
 [[ "$-" =~ x ]] && { set +x; B[binaries_debugx]=:; }
+: ${NUL:=/dev/null}
 
-declare binary
-declare -a binaries
-
-declare -gA BINARY 2>${NUL:=/dev/null} || declare -A BINARY
-
-BINARY[env]="$(command -v env)"
-
-for binary in gawk sed; do
-    if [ -x "$(command -v $binary)" ]; then
-        BINARY[$binary]="${BINARY[env]} LC_MESSAGES=C $(command -v $binary)" &>$NUL
-    else
-        echo -e "\e[31mERROR: no '$binary' binary or '$binary' not executable\e[0m" > ${TTY:=/dev/tty}
-        [ -t 0 ] || exit 1
-    fi
-done
+declare -a paths used_binaries binaries
+declare -gA BINARY 2>$NUL || declare -A BINARY
+declare -gA PHP 2>$NUL || declare -A PHP
+PHP[vregex]='(5\.6|[78]\.[01234])'
+PHP[vextglob]='*@(*5\.6*|*[78]\.[01234]*)*'
 
 reload_binaries(){
+    [ -f "${F[binary]:=${D[vt]}/binary}" ] && ${BINARY[rm]} -f -- "${F[binary]}"
     FILTER_BASHLIB=_ BINARIES_BASHLIB=_
     . <(lrequire filter)
 }
 
-glob_path(){
-    local path binary
-    local -a paths results
+map_paths(){
     # standard paths take precedence
     PATH=$(printf "%s" "/usr/sbin:/usr/bin:/sbin:/bin:$PATH" | ${BINARY[gawk]} -v RS=: -v ORS=: '!seen[$0]++' | ${BINARY[sed]} 's/::/:/g;s/:$//')
     mapfile -t paths< <(printf "%s\n" ${PATH//:/ })
-    shopt -s nullglob
+}
+
+shopt -s nullglob
+nullglob_path(){
+    local path binary
+    local -a results
+    map_paths
     for path in "${paths[@]}"; do
         for binary in "$path"/*; do
             results+=("$binary")
         done
     done
-    shopt -u nullglob
     printf '%s\n' "${results[@]}"
 }
+shopt -u nullglob
 
-mapfile -t binaries < <(glob_path)
-for binary in "${binaries[@]}"; do
-    [ -z "${BINARY[${binary##*/}]}" ] || continue
-    [ -x "$binary" ] || continue
-    BINARY[${binary##*/}]="${BINARY[env]} LC_MESSAGES=C $binary" &>$NUL
+shopt -s extglob
+extglob_path(){
+    local path binary
+    local -a results
+    map_paths
+    for path in "${paths[@]}"; do
+        for binary in "$path"/${PHP[vextglob]}; do
+            [[ -e "$binary" ]] && results+=("$binary")
+        done
+    done
+    printf '%s\n' "${results[@]}"
+}
+shopt -u extglob
+
+: "${F[binary]:=${D[vt]}/binary}"
+[ -f "${F[binary]}" ] && . "${F[binary]}"
+
+if [[ -z "${BINARY[stat]}" || $(${BINARY[stat]} -c %Y "${F[binary]}" 2>$NUL) -lt ${M[binaries_e]} ]]; then
+    BINARY[env]="$(command -v env)"
+    for x in gawk sed; do
+        if [ -x "$(command -v $x)" ]; then
+            BINARY[$x]="${BINARY[env]} LC_MESSAGES=C $(command -v $x)" &>$NUL
+        else
+            echo -e "\e[31mERROR: no '$x' binary or '$x' not executable\e[0m" > ${TTY:=/dev/tty}
+            [ -t 0 ] || exit 1
+        fi
+    done
+
+__used_binaries__
+
+    shopt -s nullglob
+    mapfile -t binaries < <(nullglob_path)
+    shopt -u nullglob
+
+    for x in "${binaries[@]}"; do
+        [ -z "${BINARY[${x##*/}]}" ] || continue
+        [ -x "$x" ] || continue
+#        [[ " ${used_binaries[@]} " =~ " ${x##*/} " || "${x##*/}" =~ ^php(-config|-fpm|ize)?${PHP[vregex]}$ ]] || continue
+        [[ " ${used_binaries[@]} " =~ " ${x##*/} " ]] || continue
+        BINARY[${x##*/}]="${BINARY[env]} LC_MESSAGES=C $x" &>$NUL
+    done
+    # xmlstarlet invocation https://xmlstar.sourceforge.net/doc/UG/xmlstarlet-ug.html#idm47077139670224
+    [ -z "${BINARY[xmlstarlet]}" ] || BINARY[xmls]="${BINARY[xmlstarlet]} sel -B -t" &>$NUL
+fi
+
+# allways load actual php versions because they may have been newly installed
+shopt -s extglob
+mapfile -t binaries < <(extglob_path)
+shopt -u extglob
+
+for x in "${binaries[@]}"; do
+    [ -z "${BINARY[${x##*/}]}" ] || continue
+    [ -x "$x" ] || continue
+    [[ "${x##*/}" =~ ^php(-config|-fpm|ize)?${PHP[vregex]}$ ]] || continue
+    BINARY[${x##*/}]="${BINARY[env]} LC_MESSAGES=C $x" &>$NUL
 done
-unset -v binary binaries
-
-# xmlstarlet invocation https://xmlstar.sourceforge.net/doc/UG/xmlstarlet-ug.html#idm47077139670224
-[ -z "${BINARY[xmlstarlet]}" ] || BINARY[xmls]="${BINARY[xmlstarlet]} sel -B -t" &>$NUL
-
+unset -v used_binaries binaries
+declare -p BINARY > "${F[binary]}"
+${BINARY[chmod]} 666 "${F[binary]}"
 
 # Create a nameref for BINARY named X
 declare -n X=BINARY
-# readonly -A X # this is declared as readonly after the depency_check passed
+declare -p X >>  "${F[binary]}"
 
 [[ "$(type -t req)" == function ]] && . <(req backcomp 2>$NUL)
 
diff --git a/modules/dependency b/modules/dependency
--- a/modules/dependency
+++ b/modules/dependency
@@ -69,38 +69,49 @@ dependency_check(){
                 "apt-rdepends#apt-rdepends#Recursively lists package dependencies"
                 "sponge#moreutils#additional Unix utilities"
                 "dos2unix#dos2unix#Convert text file line endings between CRLF and LF"
+                "update-ca-certificates#ca-certificates#Common CA certificates"
+                "ccdiff#ccdiff#Colored Character Diff"
 # TODO <-- 2
                 "less#less#A terminal pager similar to more"
                 "ss#iproute2#Networking and traffic control tools"
                 "phpquery#php-common#Common files for PHP packages"
                 "lsb_release#lsb-release#Tool to detect the Linux standard base version"
-                "update-ca-certificates#ca-certificates#Common CA certificates"
-                "ccdiff#ccdiff#Colored Character Diff"
                 "ss#iproute2#Networking and traffic control tools"
                 "file#file#Detecting the file type using magic numbers"
+                "diff#diffutils#File comparison utilities"
             )
     esac
     c2=18 c3=34
     mapfile -t dependencies< <(p_sort "${dependencies[@]}")
     for dependency in ${dependencies[@]%%#*}; do
 #        if [ -z "${X[$dependency]}" ]; then
-        if ! [[ "${X[$dependency]}" =~ $dependency ]]; then
-            case "$dependency" in
-                ansifilter)
-                    if [[ "$(type -t apt_exist)" == function ]]; then
-                        apt_exist "$dependency" && mis+=("$dependency")
-                    fi
-                    ;;
-                *)  if ${X[dpkg]} -l | ${X[grep]} -qs "^[hiu]i.*\s$(a_fld dependencies '#' "$dependency" 2)\s"; then
-                        if (( M[e] > 1737549000 )); then
-                            R; bundle echo "  The '$(a_fld dependencies '#' "$dependency" 2)' package seams to be installed but the '$dependency' binary could not be found in the path"
-                            R; bundle echo "  You should fix that first!"; N
-                            anykey
+        if ! [[ "${X[$dependency]}" =~ /$dependency ]]; then
+            if q0 command -v $dependency; then
+                X[$dependency]="${X[env]} LC_MESSAGES=C $(command -v $dependency)" &>$NUL
+            else
+                case "$dependency" in
+                    ansifilter)
+                        if [[ "$(type -t apt_exist)" == function ]]; then
+                            apt_exist "$dependency" && mis+=("$dependency")
                         fi
-                    else
-                        mis+=("$dependency")
-                    fi
-            esac
+                        ;;
+                    *)  if ${X[dpkg]} -l | ${X[grep]} -qs "^[hiu]i.*\s$(a_fld dependencies '#' "$dependency" 2)\s"; then
+                            if (( M[e] > 1737549000 )); then
+                                f 2
+                                bundle echo "$(es2; R; format_string "The '$(a_fld dependencies '#' "$dependency" 2)' package seams to be installed but the '$dependency' binary could not be found by the script, that should be fixed first!" 2; N)"
+                                f
+                                es2; W; bundle echo "Try:"; N
+                                f
+                                es4; GRAY; bundle echo "sudo$(Yi) apt-get install --reinstall $(a_fld dependencies '#' "$dependency" 2)"; N
+                                f
+                                bundle echo "$(es2; W; format_string ".. and if that does not succeed, it could be a bug, which will be fixed as soon as possible. Try to run the script later again or open an issue on https://github.com/ernolf/ebtb/issues" 2; N)"
+                                exit1
+                            fi
+                        else
+                            mis+=("$dependency")
+                        fi
+                esac
+            fi
         fi
     done
     if (( ${#mis[@]} )); then
@@ -155,7 +166,5 @@ dependency_check(){
             exit1
         fi
     fi
-    # declare the binaries array as readonly.
-    readonly -A X
 }
 dependency_check
