refactor: bulk commit week 11 2025

diff --git a/modules/dependency b/modules/dependency
--- a/modules/dependency
+++ b/modules/dependency
@@ -16,26 +16,28 @@ DEPENDENCY_BASHLIB=:
 . <(lrequire sudo)
 . <(lrequire ask)
 . <(lrequire anykey)
+. <(lrequire dpkg)
 # TODO <-- 0
 dependency_check(){
     local dependency bin plu pkg
     local -i c2 c3
     local -a dependencies mis
     dependencies=(
-# TODO 0 -->
+# TODO 1 -->
         "curl#curl#Command line file transfer tool with URL syntax"
-# TODO <-- 0
+# TODO <-- 1
         "gawk#gawk#GNU awk"
         "grep#grep#GNU grep, egrep and fgrep"
         "gpg#gnupg#GNU Privacy Guard"
         "jq#jq#command-line JSON processor"
+        "ansifilter#ansifilter#parse common (terminal) ANSI codes and remove or convert them"
     )
     case "$MS" in
         nc-apps)
             dependencies+=(
                 "less#less#A terminal pager similar to more"
                 "sqlite3#sqlite3#Command line interface for SQLite 3"
-                "php#php-cli#PHP Commandline Interface"
+                "php#php-cli#PHP Commandline Interpreter"
                 "xmlstarlet#xmlstarlet#Command line XML toolkit"
             )
             ;;
@@ -46,7 +48,7 @@ dependency_check(){
             ;;
         nc-occ)
             dependencies+=(
-                "php#php-cli#PHP Commandline Interface"
+                "php#php-cli#PHP Commandline Interpreter"
             )
             ;;
         nc-who)
@@ -62,12 +64,12 @@ dependency_check(){
             ;;
         php-updater)
             dependencies+=(
-# TODO 1 -->
+# TODO 2 -->
                 "apt-file#apt-file#Search for files within Debian packages"
                 "apt-rdepends#apt-rdepends#Recursively lists package dependencies"
                 "sponge#moreutils#additional Unix utilities"
                 "dos2unix#dos2unix#Convert text file line endings between CRLF and LF"
-# TODO <-- 1
+# TODO <-- 2
                 "less#less#A terminal pager similar to more"
                 "ss#iproute2#Networking and traffic control tools"
                 "phpquery#php-common#Common files for PHP packages"
@@ -81,16 +83,24 @@ dependency_check(){
     c2=18 c3=34
     mapfile -t dependencies< <(p_sort "${dependencies[@]}")
     for dependency in ${dependencies[@]%%#*}; do
-        if [ -z "${X[$dependency]}" ]; then
-            if ${X[dpkg]} -l | ${X[grep]} -qs "^[hiu]i.*\s$(a_fld dependencies '#' "$dependency" 2)\s"; then
-                if (( epoch > 1737549000 )); then
-                    R; bundle echo "  The '$(a_fld dependencies '#' "$dependency" 2)' package seams to be installed but the '$dependency' binary could not be found in the path"
-                    R; bundle echo "  You should fix that first!"; N
-                    anykey
-                fi
-            else
-                mis+=("$dependency")
-            fi
+#        if [ -z "${X[$dependency]}" ]; then
+        if ! [[ "${X[$dependency]}" =~ $dependency ]]; then
+            case "$dependency" in
+                ansifilter)
+                    if [[ "$(type -t apt_exist)" == function ]]; then
+                        apt_exist "$dependency" && mis+=("$dependency")
+                    fi
+                    ;;
+                *)  if ${X[dpkg]} -l | ${X[grep]} -qs "^[hiu]i.*\s$(a_fld dependencies '#' "$dependency" 2)\s"; then
+                        if (( M[e] > 1737549000 )); then
+                            R; bundle echo "  The '$(a_fld dependencies '#' "$dependency" 2)' package seams to be installed but the '$dependency' binary could not be found in the path"
+                            R; bundle echo "  You should fix that first!"; N
+                            anykey
+                        fi
+                    else
+                        mis+=("$dependency")
+                    fi
+            esac
         fi
     done
     if (( ${#mis[@]} )); then
diff --git a/modules/tempfile b/modules/tempfile
--- a/modules/tempfile
+++ b/modules/tempfile
@@ -14,29 +14,37 @@ TEMPFILE_BASHLIB=:
 . <(lrequire binaries)
 # TODO <-- 0
 # standard for root:
-: "${TMPDIR:=/tmp}"
-[[ "$TMPDIR" == '/' || ! -d "$TMPDIR" ]] && TMPDIR='/tmp'
-[ -d "$TMPDIR" ] || TMPDIR='/temp'
+: "${TD:=/tmp}"
+[[ "$TD" == '/' || ! -d "$TD" ]] && TD='/tmp'
+[ -d "$TD" ] || TD='/temp'
 
 # unprivileged users need their own writable tmp dir:
 if ! ${B[rt]}; then
-    TMPDIR="${TMPDIR%/}"
-    if (( $(${X[gawk]} -F/ '{print NF-1}' <<< "$TMPDIR") == 1 )) && [ -w "$TMPDIR" ]; then
-        TMPDIR="$TMPDIR/user-${I[u]}"
-    elif [ ! -w "$TMPDIR" ]; then
-        TMPDIR="$(${X[gawk]} -F/ '{print "/"$2}' <<< "$TMPDIR")/user-${I[u]}"
+    # remove trailing slash from TD
+    TD="${TD%/}"
+    if (( $(${X[gawk]} -F/ '{print NF-1}' <<< "$TD") == 1 )) && [ -w "$TD" ]; then
+        # if TD has only one directory level and is writable, append a user-specific subdirectory
+        TD="$TD/user-${I[u]}"
+    elif [ ! -w "$TD" ]; then
+        # if TD is not writable, derive a base directory from TD and append a user-specific subdirectory
+        TD="$(${X[gawk]} -F/ '{print "/"$2}' <<< "$TD")/user-${I[u]}"
     fi
-    [ -d "$TMPDIR" ] || q0 ${X[mkdir]} -m 755 "$TMPDIR"
+    # create the directory if it does not exist, with permissions 755
+    [ -d "$TD" ] || q0 ${X[mkdir]} -m 755 "$TD"
 fi
 declare ttf
-ttf="$(${X[mktemp]} -p "$TMPDIR")"
+# create a temporary file in the directory TD and store its name in the variable ttf
+ttf="$(${X[mktemp]} -p "$TD")"
 if [[ -n "$ttf" && -f "$ttf" ]]; then
+    # if the temporary file exists, remove it
     ${X[rm]} -f -- "$ttf"
 else
-    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '${I[un]}'\e[0m" >&2
+    # if the temporary file was not created, print an error message
+    echo -e "\e[31mERROR: TD '$TD' is not writable by user '${I[un]}'\e[0m" >&2
+    # exit with error if not running interactively
     [ -t 0 ] || exit 1
 fi
-unset ttf
+unset ttf  # unset the temporary file variable
 
 # tempfile creation $1=u (--dry-run)
 tf(){
@@ -47,9 +55,9 @@ tf(){
       666|777)  mode=$arg
         esac
     done
-    t="$(${X[mktemp]} -p $TMPDIR -${u}t ${bm}$$_XXXXXXXXXXXX)"
+    t="$(${X[mktemp]} -p $TD -${u}t ${M[b]}${M[pid]}_XXXXXXXXXXXX)"
 # TODO 0 -->
-#    t="$(${X[mktemp]} -p $TMPDIR -${u}t ${bm:-$$}_XXXXXXXXXXXX)"
+#    t="$(${X[mktemp]} -p $TD -${u}t ${M[b]:-$$}_XXXXXXXXXXXX)"
 # TODO <-- 0
     if [ -z "$u" ]; then
         if [ -n "$mode" ]; then
