refactor: bulk commit week 7, 8, 9

diff --git a/modules/dpkg b/modules/dpkg
--- a/modules/dpkg
+++ b/modules/dpkg
@@ -7,7 +7,7 @@ __copyright__
 __license__
 #
 
-${DPKG_BASHLIB:-false} && return
+${DPKG_BASHLIB:-_} && return
 DPKG_BASHLIB=:
 
 . <(lrequire binaries)
@@ -32,37 +32,39 @@ DPKG_LOCKFILES=(
 )
 
 check_lockfile(){
-    local lockfile verbose fuser_output
+    local lockfile fuser_output
+    local -A bool
     local -i pid
-    lockfile=$1
-    [ "$2" = '-v' ] && verbose=: || verbose=false
+    lockfile="$1"
+    [ "$2" = '-v' ] && bool[verbose]=: || bool[verbose]=_
     if [ -e "$lockfile" ]; then
         # Identify the process holding the lock
-        fuser_output=$(q2 ${BINARIES[fuser]} "$lockfile")
+        fuser_output=$(q2 ${X[fuser]} "$lockfile")
         if [ -n "$fuser_output" ]; then
-            processstring="$(listify_ Yi R "$(for pid in $fuser_output; do echo "$(${BINARIES[ps]} -p $pid -o comm=) (pid:$pid)"; done)")"
+            processstring="$(listify_ Yi R "$(for pid in $fuser_output; do echo "$(${X[ps]} -p $pid -o comm=) (pid:$pid)"; done)")"
             o3; R; echo "- Lockfile '$(C)$lockfile$(R)' is used by: $processstring";N
 #            for pid in $fuser_output; do echo "$(ps -p $pid -o comm=) (pid:$pid))"; done
         else
-            $verbose && { o3; echo "- Lockfile '$(C)$lockfile$(N)' exists but no process seems to be using it."; }
+            ${bool[verbose]} && { o3; echo "- Lockfile '$(C)$lockfile$(N)' exists but no process seems to be using it."; }
         fi
     else
-        $verbose && { o3; echo "- Lockfile '$(C)$lockfile$(N)' does not exist."; }
+        ${bool[verbose]} && { o3; echo "- Lockfile '$(C)$lockfile$(N)' does not exist."; }
     fi
 }
 
 check_lockfiles(){
-    local lockfile verbose
+    local lockfile
     local -a checked_lockfiles
+    local -A flag
     local -i i
-    verbose="$1"
-    mapfile -t checked_lockfiles< <(for lockfile in "${DPKG_LOCKFILES[@]}"; do check_lockfile "$lockfile" "$verbose"; done)
+    flag[verbose]="$1"
+    mapfile -t checked_lockfiles< <(for lockfile in "${DPKG_LOCKFILES[@]}"; do check_lockfile "$lockfile" "${flag[verbose]}"; done)
     if (( $# )); then
         for i in ${!checked_lockfiles[@]}; do
             echo "${checked_lockfiles[i]}"
         done
     elif (( ${#checked_lockfiles[@]} )); then
-        bundle echo "$(xpf;R) WARNING: dpkg and/or apt is locked:";N
+        bundle echo "$(xpf; R) WARNING: dpkg and/or apt is locked:"; N
         for i in ${!checked_lockfiles[@]}; do
             bundle echo "${checked_lockfiles[i]}"
         done
@@ -74,20 +76,21 @@ check_lockfiles(){
 
 apt_update(){
     spinner C " .  resynchronizing the APT package index files  ." &
-    ${BINARIES[apt-get]} -q2 update
+    ${X[apt-get]} -q2 update
     kill_spinner
 }
 
 # returns true if last apt-* update is done more than $1=int (defaults to 4) hours ago
 apt_need_update(){
     check_lockfiles || exit1
-    if [ $(($(($(now)-$(${BINARIES[stat]} -c %Y /var/lib/apt/lists/partial)))/3600)) -gt ${1:-4} ]; then
+    if [ $(($(($(now)-$(${X[stat]} -c %Y /var/lib/apt/lists/partial)))/3600)) -gt ${1:-4} ]; then
         f
         echo " -$(format_string "The APT package indexes are synchronized more than ${1:-4} hours ago. This script requires up-to-date indexes to function correctly." 3)"
         if ask "$(qpf)Do you want to resynchronize the APT package index files now" "$YES"; then
-        apt_update
+            apt_update
         else
-            te0;te0;te0
+#            te0; te0; te0
+            te0 3
         fi
     fi
 }
@@ -95,8 +98,8 @@ apt_need_update(){
 install_time(){
     local pkg
     pkg="$1"
-    if ${BINARIES[grep]} -qs " install $pkg" /var/log/dpkg.log; then
-        ${BINARIES[date]} -d "$(${BINARIES[gawk]} '/ install '$pkg'/ {date=$1 " " $2} END{print date}' /var/log/dpkg.log)" "+%s"
+    if ${X[grep]} -qs " install $pkg" /var/log/dpkg.log; then
+        ${X[date]} -d "$(${X[gawk]} '/ install '$pkg'/ {date=$1 " " $2} END{print date}' /var/log/dpkg.log)" "+%s"
         return 0
     fi
     return 1
@@ -105,58 +108,56 @@ install_time(){
 apt_file_search(){
     local fullpath package
     local -i installed now last_apt_update
-    fullpath="$1"
-    now=$(now)
-    last_apt_update=$(${BINARIES[stat]} -c %Y /var/lib/apt/lists/partial)
+    fullpath="$1" now=$(now) last_apt_update=$(${X[stat]} -c %Y /var/lib/apt/lists/partial)
     if installed=$(install_time apt-file); then
         if (( $(( now - installed )) < $(( now - last_apt_update )) )); then
-            q0 ${BINARIES[apt-get]} update -q2
+            q0 ${X[apt-get]} update -q2
         fi
     elif (( $(( $(( now - last_apt_update )) / 3600 )) > 4 )); then
-        q0 ${BINARIES[apt-get]} update -q2
+        q0 ${X[apt-get]} update -q2
     fi
     package=$(q2 apt-file -l search "$fullpath") || return $?
     printf "$package"
-    mh "apt-file -l search $fullpath -> $package" &
+    mh "apt-file -l search $fullpath -> $package"
     return 0
 }
 
 apt_exist(){
     local -a pkgnames
-    mapfile -t pkgnames< <(${BINARIES[apt-cache]} pkgnames "$1")
+    mapfile -t pkgnames< <(${X[apt-cache]} pkgnames "$1")
     [[ " ${pkgnames[@]} " =~ " $1 " ]] || return 1
-    ${BINARIES[apt-get]} -qqs install "$1" 2>&1 | ${BINARIES[grep]} -qs "has no installation candidate" && return 1
-    ${BINARIES[apt-get]} -qqs install "$1" 2>&1 | ${BINARIES[grep]} -qs "Unable to locate package" && return 1
-    ${BINARIES[apt-cache]} policy "$1" 2>&1 | ${BINARIES[grep]} -qs "Candidate: (none)" && return 1
-    q0 ${BINARIES[apt-get]} -qqs install "$1"
+    ${X[apt-get]} -qqs install "$1" 2>&1 | ${X[grep]} -qs "has no installation candidate" && return 1
+    ${X[apt-get]} -qqs install "$1" 2>&1 | ${X[grep]} -qs "Unable to locate package" && return 1
+    ${X[apt-cache]} policy "$1" 2>&1 | ${X[grep]} -qs "Candidate: (none)" && return 1
+    q0 ${X[apt-get]} -qqs install "$1"
 }
 
 apt_install(){
     apt_need_update
     check_lockfiles || exit1
     local p ps yes=" -y"
-    ${step:-false} && yes=""
-    mh "${BINARIES[apt-get]}$yes install $@" &
+    ${B[step]:-_} && yes=""
+    mh "${X[apt-get]}$yes install $@"
     for p in $@; do
-        ${BINARIES[dpkg]} -l | ${BINARIES[grep]} -wqs "$p" || ps="$ps $p"
-        if (( $(echo "$ps" | ${BINARIES[wc]} -w) )); then
-            mh "${BINARIES[apt-get]}$yes install $ps" &
-            ${BINARIES[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends install $ps
+        ${X[dpkg]} -l | ${X[grep]} -wqs "$p" || ps="$ps $p"
+        if (( $(echo "$ps" | ${X[wc]} -w) )); then
+            mh "${X[apt-get]}$yes install $ps"
+            ${X[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends install $ps
             (( $? )) && exit1
         fi
     done
-    ${step:-false} && anykey
+    ${B[step]:-_} && anykey
 }
 
 apt_install_prechecked(){
     check_lockfiles || exit1
-    prechecked "$@" &
+    prechecked "$@"
     local yes=''
     if [ "$1" = '--yes' ] || [ "$1" = '-y' ]; then
         yes=' -y'
         shift
     fi
-    ${BINARIES[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends install $@||{ echo "  $(Pbg) something went wrong $(N)";f;exit1;}
+    ${X[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends install $@ || { echo "  $(Pbg) something went wrong $(N)"; f; exit1; }
 }
 
 apt_remove(){
@@ -168,7 +169,7 @@ apt_remove(){
         shift
     fi
     switch_php_to_ $PHP_VERSION
-    ${BINARIES[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends remove $@
+    ${X[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends remove $@
 }
 
 apt_purge(){
@@ -180,32 +181,32 @@ apt_purge(){
         shift
     fi
     switch_php_to_ $PHP_VERSION
-    ${BINARIES[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends purge $@
+    ${X[apt-get]}$yes --ignore-hold --allow-change-held-packages --no-install-recommends purge $@
 }
 
-
 rdepends(){
-    local quiet glob
+    local glob
+    local -A bool
     if [ "$1" = '-q' ]; then
-        quiet='true'
+        bool[quiet]='true'
         shift
     else
-        quiet='false'
+        bool[quiet]='_'
     fi
     glob="$1"
-    if "$quiet"; then
-        (( $(q2 ${BINARIES[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove "$glob" | ${BINARIES[wc]} -l) - 1 )) # && return 0 || return 1
+    if "${bool[quiet]}"; then
+        (( $(q2 ${X[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove "$glob" | ${X[wc]} -l) - 1 )) # && return 0 || return 1
     else
-        q2 ${BINARIES[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove "$glob" | ${BINARIES[gawk]} '{print $2}'
+        q2 ${X[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove "$glob" | ${X[gawk]} '{print $2}'
     fi
 }
 
 apt_rdepends(){
     local glob package
     glob="$1"
-    for package in $(${BINARIES[dpkg]} -l|${BINARIES[gawk]} '/^[hiu]i\s+[^\s]*'$glob'/{print $2}'); do
-        q2 ${BINARIES[apt-rdepends]} -r --follow=Depends --show=Depends --state-follow=Installed --state-show=Installed $package | ${BINARIES[gawk]} '/Reverse/ {print $3}'
-    done | ${BINARIES[sort]} -u
+    for package in $(${X[dpkg]} -l|${X[gawk]} '/^[hiu]i\s+[^\s]*'$glob'/{print $2}'); do
+        q2 ${X[apt-rdepends]} -r --follow=Depends --show=Depends --state-follow=Installed --state-show=Installed $package | ${X[gawk]} '/Reverse/ {print $3}'
+    done | ${X[sort]} -u
 }
 
 # this is very slow but acurate
@@ -213,12 +214,12 @@ rdependency_tree(){
     local package pkg_main pkg_sub pkg_sub_sub
     local -a depending_main depending_sub
     package="$1"
-    mapfile -t depending_main< <(${BINARIES[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove $package | ${BINARIES[gawk]} '{print $2}')
+    mapfile -t depending_main< <(${X[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove $package | ${X[gawk]} '{print $2}')
     if (( ${#depending_main[@]} > 1 )); then
         echo "$package is required by:"
         for pkg_main in ${depending_main[@]}; do
             echo -n " - $pkg_main "
-            mapfile -t depending_sub< <(${BINARIES[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove $pkg_main | ${BINARIES[gawk]} '{print $2}')
+            mapfile -t depending_sub< <(${X[apt-get]} --ignore-hold --allow-change-held-packages -s -q2 remove $pkg_main | ${X[gawk]} '{print $2}')
             if (( ${#depending_sub[@]} > 1 )); then
                 echo "- which is required by:"
                 for pkg_sub in ${depending_sub[@]}; do
@@ -238,16 +239,16 @@ rdep_tree(){
         local pkg
         local -a rdeps rdep
         pkg=$1
-        mapfile -t rdeps< <(${BINARIES[apt-cache]} rdepends $pkg)
+        mapfile -t rdeps< <(${X[apt-cache]} rdepends $pkg)
         mapfile -t rdep< <(comm -12 <(p_sort ${installed[@]}) <(p_sort ${rdeps[@]}))
         mapfile -t rdep< <(comm -23 <(p_sort ${rdep[@]}) <(p_sort $pkg))
-        (( ${#rdep[@]} ))&&p_sort ${rdep[@]}
+        (( ${#rdep[@]} )) && p_sort ${rdep[@]}
     }
     local package rdependency
     local -a installed rdepends rrdepends
     local -i i ii depth
-    package=$1
-    mapfile -t installed< <(${BINARIES[dpkg]} -l | ${BINARIES[gawk]} '/^[hiu]i\s+[^\s]/{print $2}')
+    package="$1"
+    mapfile -t installed< <(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i\s+[^\s]/{print $2}')
     mapfile -t rdepends< <(rdep $package)
     if (( ${#rdepends[@]} )); then
         echo "$package has ${#rdepend[@]} reverse dependencies:"
@@ -280,17 +281,19 @@ rdep_tree(){
 # $3=old: 8.1
 # $4=new: 8.2
 set_selections(){
+    required_args 4 "$@"
     local regex modus old new mf
     regex="$1" modus="$2" old="$3" new="$4"
-    q0 ${BINARIES[apt-mark]} unhold *php*
+    q0 ${X[apt-mark]} unhold *php*
     [ "$modus" = "manual" ] && mf=auto
     [ "$modus" = "auto" ] && mf=manual
-    ${BINARIES[update-alternatives]} --get-selections | ${BINARIES[grep]} -E "$regex" |  ${BINARIES[sed]} -E "s/$mf/$modus/;s/$old/$new/" | q0 ${BINARIES[update-alternatives]} --set-selections
+    ${X[update-alternatives]} --get-selections | ${X[grep]} -E "$regex" |  ${X[sed]} -E "s/$mf/$modus/;s/$old/$new/" | q0 ${X[update-alternatives]} --set-selections
 }
 
 min_version(){
+    required_args 2 "$@"
     local bin="$1" min="$2"
-    ${BINARIES[dpkg]} --compare-versions "$(q2 $bin --version | ${BINARIES[grep]} -oP '\d+(\.\d+){1,3}')" ge "$min" # && return 0 || return 1
+    ${X[dpkg]} --compare-versions "$(q2 $bin --version | ${X[grep]} -oP '\d+(\.\d+){1,3}')" ge "$min" # && return 0 || return 1
 }
 
 # switch all findable php related packages to manual
@@ -298,15 +301,17 @@ min_version(){
 # $1=old: 8.1
 # $2=new: 8.2
 switch_php(){
+    required_args 2 "$@"
     set_selections "ph(ar|p)" "manual" "$1" "$2"
 }
 
 # switch all findable php related packages to manual Version $1 if $1 exists
 switch_php_to_(){
-    q0 ${BINARIES[apt-mark]} manual $(${BINARIES[dpkg]} -l | ${BINARIES[gawk]} '/^[hiu]i.*php*/{print $2}')
+    require_arg $@
+    q0 ${X[apt-mark]} manual $(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*php*/{print $2}')
     set_selections "ph(ar|p)" "manual" '\(5\.6\|7\.[01234]\|8\.[0123]\)' "$1"
 # TODO 0 -->
-#    q0 ${BINARIES[apt-mark]} hold $(${BINARIES[dpkg]} -l | ${BINARIES[gawk]} '/^[hiu]i.*php*/{print $2}')
+#    q0 ${X[apt-mark]} hold $(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*php*/{print $2}')
 # TODO <-- 0
 }
 
@@ -315,40 +320,40 @@ list_apt_sources(){
     local -i i
     local -a foreign_architectures aptsources apturls aptsourcesfiles
 
-    mapfile -t foreign_architectures< <(${BINARIES[dpkg]} --print-foreign-architectures 2>&1)
+    mapfile -t foreign_architectures< <(${X[dpkg]} --print-foreign-architectures 2>&1)
     if (( ${#foreign_architectures[@]} )); then
-        f;o2;B;echo "This is a list of the supported architectures on this machine for your information:";N
-        o2;pf;GRAY;echo "main architecture: $(${BINARIES[dpkg]} --print-architecture 2>&1)";N
+        f; o2; B; echo "This is a list of the supported architectures on this machine for your information:"; N
+        o2; pf; GRAY; echo "main architecture: $(${X[dpkg]} --print-architecture 2>&1)"; N
         (( ${#foreign_architectures[@]} > 1 ))&&plu='s'||plu=''
-        for i in ${!foreign_architectures[@]}; do o2;pf;GRAY;echo "foreign architecture$plu $((i+1)): ${foreign_architectures[i]}";N; done
+        for i in ${!foreign_architectures[@]}; do o2; pf; GRAY; echo "foreign architecture$plu $((i+1)): ${foreign_architectures[i]}"; N; done
     else
-        f;o2;B;echo "This is the supported architecture on this machine for your information:";N
-        o2;pf;GRAY;echo "architecture: $(${BINARIES[dpkg]} --print-architecture 2>&1)";N
+        f; o2; B; echo "This is the supported architecture on this machine for your information:"; N
+        o2; pf; GRAY; echo "architecture: $(${X[dpkg]} --print-architecture 2>&1)"; N
     fi
 
-    f;o2;B;echo "This is a list of the effective apt sources on this machine for your information:";N
+    f; o2; B;echo "This is a list of the effective apt sources on this machine for your information:"; N
     # apt sources
     if [ -d /var/lib/apt/lists ]; then
-        mapfile -t aptsources< <(p_sort "$(cd /var/lib/apt/lists/;${BINARIES[ls]} *Packages|${BINARIES[sed]} 's/_Packages.*$//;s/-deb.*$//;s/_dists_/ /;s/_binary-/ /')")
-        for i in ${!aptsources[@]}; do o2;pf;GRAY;echo "aptsource-$(printf '%02d' $((i+1))): $(urldecode ${aptsources[i]//_/\/}|${BINARIES[sed]} 's/\(.*\)\/\(.*\)/\1 \2/')";N; done
+        mapfile -t aptsources< <(p_sort "$(cd /var/lib/apt/lists/;${X[ls]} *Packages|${X[sed]} 's/_Packages.*$//;s/-deb.*$//;s/_dists_/ /;s/_binary-/ /')")
+        for i in ${!aptsources[@]}; do o2;pf;GRAY;echo "aptsource-$(printf '%02d' $((i+1))): $(urldecode ${aptsources[i]//_/\/}|${X[sed]} 's/\(.*\)\/\(.*\)/\1 \2/')"; N; done
 
-    f;o2;B;echo "This is a list of the files containing the apt sources for your information:";N
+    f; o2; B; echo "This is a list of the files containing the apt sources for your information:"; N
     # apt sources files
-        mapfile -t apturls< <(p_sort "$(cd /var/lib/apt/lists/;${BINARIES[ls]} *Packages|${BINARIES[sed]} 's/_dists.*$//')")
+        mapfile -t apturls< <(p_sort "$(cd /var/lib/apt/lists/;${X[ls]} *Packages|${X[sed]} 's/_dists.*$//')")
 # TODO 1 -->
-#    mapfile -t aptsourcesfiles< <(p_sort $(for i in ${!apturls[@]};do ${BINARIES[grep]} -r "$(urldecode ${apturls[i]//_/\/})" /etc/apt/|${BINARIES[grep]} -v ':\s*#'|${BINARIES[grep]} -E "*.(list|sources)\:"|${BINARIES[gawk]} -F':' '{print $1}'; done))
+#    mapfile -t aptsourcesfiles< <(p_sort $(for i in ${!apturls[@]};do ${X[grep]} -r "$(urldecode ${apturls[i]//_/\/})" /etc/apt/|${X[grep]} -v ':\s*#'|${X[grep]} -E "*.(list|sources)\:"|${X[gawk]} -F':' '{print $1}'; done))
 # TODO <-- 1
-        mapfile -t aptsourcesfiles< <(p_sort $(for i in "${!apturls[@]}";do ${BINARIES[grep]} -r "$(urldecode ${apturls[i]//_/\/})" /etc/apt/|${BINARIES[gawk]} -F: '/:\s*#/{next}/.*\.(list|sources):/{print$1}';done))
-        for i in ${!aptsourcesfiles[@]}; do o2;pf;GRAY;echo "aptsourcefile-$(printf '%02d' $((i+1))): ${aptsourcesfiles[i]}";N; done
+        mapfile -t aptsourcesfiles< <(p_sort $(for i in "${!apturls[@]}";do ${X[grep]} -r "$(urldecode ${apturls[i]//_/\/})" /etc/apt/|${X[gawk]} -F: '/:\s*#/{next}/.*\.(list|sources):/{print$1}';done))
+        for i in ${!aptsourcesfiles[@]}; do o2; pf; GRAY; echo "aptsourcefile-$(printf '%02d' $((i+1))): ${aptsourcesfiles[i]}"; N; done
     fi
 }
 
 list_alternatives(){
     local regex target target_version name mode path
     regex="${1:-ph(ar|p)}"
-    ${BINARIES[update-alternatives]} --get-selections 2>&1 | ${BINARIES[grep]} -E "$regex" | while read -r name mode path; do
-        if target="$(q2 ${BINARIES[readlink]} -e "$path")"; then
-            target_version="$(q2 ${BINARIES[echo]} "$target" | ${BINARIES[grep]} -o "[0-9.]*")"
+    ${X[update-alternatives]} --get-selections 2>&1 | ${X[grep]} -E "$regex" | while read -r name mode path; do
+        if target="$(q2 ${X[realpath]} "$path")"; then
+            target_version="$(q2 echo "$target" | ${X[grep]} -o "[0-9.]*")"
             if [[ "$path" =~ default ]]; then
                 printf "%-30s %-8s %-30s%s\n" "$name" "$mode" "$path" "$(GRAY)-> ${path//.default/${target_version%.}}$(N)"
             else
@@ -361,12 +366,12 @@ list_alternatives(){
 }
 
 list_alternatives_extended(){
-    [ -n "${BINARIES[update-alternatives]}" ] || { echo -e "\e[31mERROR: no 'update-alternatives' binary\e[0m" >&2; return 1; }
+    [ -n "${X[update-alternatives]}" ] || { echo -e "\e[31mERROR: no 'update-alternatives' binary\e[0m" >&2; return 1; }
     local regex candidate key value
     regex="${1:-ph(ar|p)}"
-    for candidate in $(q2 ${BINARIES[update-alternatives]} --get-selections | ${BINARIES[gawk]} '/'$regex'/{print $1}'); do
+    for candidate in $(q2 ${X[update-alternatives]} --get-selections | ${X[gawk]} '/'$regex'/{print $1}'); do
         echo -e "Name: $candidate"
-        ${BINARIES[update-alternatives]} --query "$candidate" | ${BINARIES[grep]} -Ev '(^$|Name:)' | while IFS= read -r line; do
+        ${X[update-alternatives]} --query "$candidate" | ${X[grep]} -Ev '(^$|Name:)' | while IFS= read -r line; do
             if [[ "$line" =~ (Slaves|Priority) ]]; then
                 echo "  \`- $line"
             elif [[ "$line" =~ ^([^:]+):\ (.*) ]]; then
diff --git a/modules/integrity b/modules/integrity
--- a/modules/integrity
+++ b/modules/integrity
@@ -7,7 +7,7 @@ __copyright__
 __license__
 #
 
-${INTEGRITY_BASHLIB:-false} && return
+${INTEGRITY_BASHLIB:-_} && return
 INTEGRITY_BASHLIB=:
 
 . <(lrequire binaries)
@@ -19,7 +19,7 @@ INTEGRITY_BASHLIB=:
 
 
 public_key(){
-    ${BINARIES[cat]} << PUBLIC_KEY_ASC
+    ${X[cat]} << PUBLIC_KEY_ASC
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 
 mQINBGSXjUIBEADbt4/706Fw6YNHMPwHT+qtq4ZxJCdUclzovEnCvECtylYCK1M5
@@ -54,68 +54,69 @@ PUBLIC_KEY_ASC
 }
 
 integrity_check(){
-    local -i r=1
-    local signed key mail aut itf="$(tf)" vtf="$(tf)" vdir ddir shash ehash
-    signed=:
-    key="$(${BINARIES[sed]} -n 's/^# OpenPGP_Key\s*\(.*\)$/\1/p' "$ca_me")"
-    mail="$(${BINARIES[sed]} -n 's/^# Email\s*\(.*\)$/\1/p' "$ca_me")"
-    aut="$(${BINARIES[sed]} -n 's/^# Copyright.*\[\(.*\)\]/\\[\1\\]/p' "$ca_me")"
+    local key mail aut itf vtf vdir ddir shash ehash
+    local -i r
+    local -A bool
+    bool[signed]=: itf="$(tf)" vtf="$(tf)" r=1
+    key="$(${X[sed]} -n 's/^# OpenPGP_Key\s*\(.*\)$/\1/p' "$ca_me")"
+    mail="$(${X[sed]} -n 's/^# Email\s*\(.*\)$/\1/p' "$ca_me")"
+    aut="$(${X[sed]} -n 's/^# Copyright.*\[\(.*\)\]/\\[\1\\]/p' "$ca_me")"
     su_root "to run the integrity check" integrity_check
     delp2ei '^-----BEGIN PGP SIGNATURE-----$' "$ca_me" "$itf"
     if [ -n "$vdirname" ]; then
         vdir=$(eval echo \$$vdirname) ddir=$(eval echo \$dflt_$vdirname)
         [ "$vdir" != "$ddir" ] && setvdir v d "$itf"
     fi
-    shash="$(${BINARIES[sha256sum]} "$itf" | ${BINARIES[gawk]} '{print $1}')"
-    ehash="$(${BINARIES[tail]} -n1 "$ca_me" | ${BINARIES[gawk]} '{print $NF}')"
+    shash="$(${X[sha256sum]} "$itf" | ${X[gawk]} '{print $1}')"
+    ehash="$(${X[tail]} -n1 "$ca_me" | ${X[gawk]} '{print $NF}')"
     line '=' P 5/75
     if ! [[ $ehash =~ ^[a-fA-F0-9]{64}$ ]]; then
         . <(lrequire ask)
-        signed=false
-        o5;R;echo "- No sha256sum hash, looks like script has not been signed!"
+        bool[signed]=_
+        o5; R; echo "- No sha256sum hash, looks like script has not been signed!"
         line '-' P 5/75
     elif [ "$shash" != "$ehash" ]; then
-        o5;R;echo "- Wrong hash, looks like script has been tampered with!"
+        o5; R; echo "- Wrong hash, looks like script has been tampered with!"
         line '-' P 5/75
     fi
-    ${BINARIES[gpg]} --list-keys | ${BINARIES[grep]} -qs "$key" || q2 ${BINARIES[gpg]} --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys "$key"
-    ${BINARIES[gpg]} --list-keys | ${BINARIES[grep]} -qs "$key" || q2 ${BINARIES[gpg]} --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key"
-    ${BINARIES[gpg]} --list-keys | ${BINARIES[grep]} -qs "$key" || q2 public_key|${BINARIES[gpg]} --import
-    ${BINARIES[gpg]} --list-keys | ${BINARIES[grep]} -qs "$key" || {
+    ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 ${X[gpg]} --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys "$key"
+    ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 ${X[gpg]} --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key"
+    ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 public_key|${X[gpg]} --import
+    ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || {
         . <(lrequire ask)
-        o5;R;echo "- import of public key failed."
-        qpf;ask "Continue at own risk without check?" "$NO"&&{
-            ${BINARIES[sed]} -i 's/^v=false$/v=true/' "$ca_me"
+        o5; R; echo "- import of public key failed."
+        qpf; ask "Continue at own risk without check?" "$NO" && {
+            ${X[sed]} -i 's/^v=false$/v=true/' "$ca_me"
             return 0
         }
     }
-    ${BINARIES[gpg]} --verify "$ca_me" "$itf">"$vtf" 2>&1
+    ${X[gpg]} --verify "$ca_me" "$itf">"$vtf" 2>&1
     r=$?
-    ${BINARIES[grep]} "$key" "$vtf"
-    ${BINARIES[grep]} "$aut (codesigning) <${mail//<at>/@}>" "$vtf"
+    ${X[grep]} "$key" "$vtf"
+    ${X[grep]} "$aut (codesigning) <${mail//<at>/@}>" "$vtf"
     line '-' P 5/75
     if (( r )); then
-        o5;R;echo -n "- Integrity check $(blinkR)failed$(R). "
-        if $signed; then
+        o5; R; echo -n "- Integrity check $(blinkR)failed$(R). "
+        if ${bool[signed]}; then
             echo "The script may have been modified or tampered with!"
         else
             echo "This script does not appear to be signed!"
         fi
         line '-' P 5/75
-        o5;B;echo "You should run:"
-        o5;GRAY;echo "sudo wget -O $ca_me $my_url"
-        if $signed; then
-            o5;B;echo "to fix this.";N
+        o5; B; echo "You should run:"
+        o5; GRAY; echo "sudo wget -O $ca_me $my_url"
+        if ${bool[signed]}; then
+            o5; B; echo "to fix this."; N
         else
-            o5;B;echo "to get a signed version of this script or disable the integrity check.";N
-            qpf;ask "Do you want to disable the integrity check at own risk" "$NO" && {
+            o5; B; echo "to get a signed version of this script or disable the integrity check."; N
+            qpf; ask "Do you want to disable the integrity check at own risk" "$NO" && {
                 echo -e "v=true\nnohash" >> "$ca_me"
                 return 0
             }
         fi
     else
-        o5;lG;echo "Integrity check passed. The script is authentic.";N
-        ${BINARIES[sed]} -i 's/^v=false$/v=true/' "$ca_me"
+        o5; lG; echo "Integrity check passed. The script is authentic."; N
+        ${X[sed]} -i 's/^v=false$/v=true/' "$ca_me"
     fi
     line '=' P 5/75
     return $r
@@ -123,19 +124,20 @@ integrity_check(){
 
 run_integrity_check(){
     if integrity_check; then
-        f;pf;G;echo "Integrity check passed. Please start script again"
+        f; pf; G; echo "Integrity check passed. Please start script again"
         exit 0
     else
         exit1
     fi
 }
 
-if $do_integrity_check; then
+if "${B[do_integrity_check]:-_}"; then
     run_integrity_check
 fi
-declare "$(${BINARIES[tail]} -n2 "$ca_me" | ${BINARIES[head]} -n1)"
-if ! "${v:-false}"; then
+
+declare $(tnh1)
+if ! "${v:-_}"; then
     f
-    o5;B;echo "First run, checking integrity:"
+    o5; B; echo "First run, checking integrity:"
     run_integrity_check
 fi
diff --git a/modules/nc/nextcloud_aio b/modules/nc/nextcloud_aio
--- a/modules/nc/nextcloud_aio
+++ b/modules/nc/nextcloud_aio
@@ -7,35 +7,31 @@ __copyright__
 __license__
 #
 
-${NEXTCLOUD_AIO_BASHLIB:-false} && return
+${NEXTCLOUD_AIO_BASHLIB:-_} && return
 NEXTCLOUD_AIO_BASHLIB=:
 
 . <(lrequire binaries)
 . <(lrequire basics)
 . <(lrequire sudo)
 
-globals="AIO DOCKER"
-for global in $globals; do q2 declare -g $global || declare $global; done
-unset -v global globals
-AIO=false DOCKER=false
+B[aio]=_ B[docker]=_
 
 aio_not_supported(){
-    $AIO || return 0
-    f;pf;R;echo "This script cannot be used with Nextcloud All-in-One …"
+    ${B[aio]} || return 0
+    f; pf; R; echo "This script cannot be used with Nextcloud All-in-One …"
     exit1
 }
 
-[ -n "${BINARIES[docker]}" ] || return
+[ -n "${X[docker]}" ] || return
 
 detect_aio(){
     docker_ps_json="$(tf)"
     # detect if any docker containers are running on the host (without -a, because only running containers matter here)
-    q2 ${BINARIES[docker]} ps --no-trunc --format=json > $docker_ps_json
+    q2 ${X[docker]} ps --no-trunc --format=json > $docker_ps_json
     mapfile -t docker_names< <(jq -r .Names $docker_ps_json)
     if (( ${#docker_names[@]} )); then
         if [[ "${docker_names[@]}" =~ nextcloud-aio-mastercontainer && "${docker_names[@]}" =~ nextcloud-aio-nextcloud ]]; then
-            AIO=true
-            DOCKER=true
+            B[aio]=: B[docker]=:
         fi
     fi
 }
@@ -50,14 +46,14 @@ aio_wrapper(){
     fi
     container_name="$1"
     shift
-    ${BINARIES[sudo]} ${BINARIES[docker]} exec $interactive_tty "nextcloud-aio-$container_name" bash -c "$*"
+    ${X[sudo]} ${X[docker]} exec $interactive_tty "nextcloud-aio-$container_name" bash -c "$*"
 }
 
-if (( $(id -u) )); then # you are not root
-    if ${BINARIES[ps]} aux | ${BINARIES[grep]} -qs "[d]ockerd"; then # dockerd is running
+if ${B[rt]}; then
+    detect_aio
+else
+    if ${X[ps]} aux | ${X[grep]} -qs "[d]ockerd"; then # dockerd is running
         su_root "to detect all-in-one"
     fi
-else
-    detect_aio
 fi
 
diff --git a/modules/php-updater/switch b/modules/php-updater/switch
--- a/modules/php-updater/switch
+++ b/modules/php-updater/switch
@@ -7,7 +7,7 @@ __copyright__
 __license__
 #
 
-${SWITCH_BASHLIB:-false} && return
+${SWITCH_BASHLIB:-_} && return
 SWITCH_BASHLIB=:
 
 . <(lrequire binaries)
@@ -26,7 +26,7 @@ SWITCH_BASHLIB=:
 . <(lrequire php/apache2)
 . <(lrequire $sin/linstalled)
 
-${BINARIES[mkdir]} -p $lincld/$sin/switch.d
+${X[mkdir]} -p $lincld/$sin/switch.d
 
 . <(lrequire $sin/switch.d/php_apache2_module)
 . <(lrequire $sin/switch.d/php_fpm)
@@ -37,110 +37,119 @@ switch_default_version(){
     local key
     local -a selections php_versions
     local -i i ret
-    mapfile -t php_versions< <(${BINARIES[phpquery]} -V | ${BINARIES[sort]})
+    mapfile -t php_versions< <(${X[phpquery]} -V | ${X[sort]})
     # update-alternatives
     cleanup_and_fix_alternatives before  # repair broken alternatives, remove not existing alternatives
     mapfile -t selections< <(list_alternatives)
     P; echo " -$(format_string "Here you can switch the default php version linked to the generic $(C)/usr/bin/php$(P) with the means of the Debian alternatives system. All php related packages maintained by the alternatives system will get switched to manual mode instead of automatic. That will prevent php from changing its version without your dessision. Therefore you can select the actually active version as well here. In this step there is no test, if all required php packages to run a server like Nextcloud are present in the version you choose. So it is recommended to first run $(C)$me${FLAG[forceflag]} \$old \$new$(P), where $(C)\$old$(P) should be the version that you know exactly that everything has been installed correctly and $(C)\$new$(P) should be the version that you want to switch to here and now." 3)"
-    echo "  $(format_string "In the subsequent next step it will switch your webserver to connect to the new php version as well. However, in some rare special cases, this step may fail though. In such a case you will have to edit the web server's configuration files yourself to connect it to the PHP socket of your choice." 3;N)"
+    echo "  $(format_string "In the subsequent next step it will switch your webserver to connect to the new php version as well. However, in some rare special cases, this step may fail though. In such a case you will have to edit the web server's configuration files yourself to connect it to the PHP socket of your choice." 3; N)"
     f
-    o3;dY;echo "this is how the alternatives system is configured at present:";N
+    o3; dY; echo "this is how the alternatives system is configured at present:"; N
     f
     for i in ${!selections[@]}; do
-        o3;pf;echo "$(lG)${selections[i]}";N
+        o3; pf; echo "$(lG)${selections[i]}";N
     done
-    N;f
+    N; f
 
-    o3;dY;echo "and this is how php is connected to the httpd:";N
+    o3; dY; echo "and this is how php is connected to the httpd:"; N
     f
     list_installed_sapi
     N
     line '=' P 2/78 b1
     f
-    pf;Y;echo "Switch default php version to:"
+    pf; Y; echo "Switch default php version to:"
     for i in ${!php_versions[@]}; do
-        f;o 10;echo "$(button $((i + 1))) - php${php_versions[i]} $(dY)supported by Nextcloud version $(listify_ C dY $(a_fld EXISTING ';' ${php_versions[i]} 5);Y)"
+        f; o 10; echo "$(button $((i + 1))) - php${php_versions[i]} $(dY)supported by Nextcloud version $(listify_ C dY $(a_fld EXISTING ';' ${php_versions[i]} 5); Y)"
     done
-    f;o 10;echo "$(button q) - do nothing, quit"
-    N;f
-    while :;do read -rsn 1 -p "$(pf;Y)Please make your choice: $(N)" key
-        case $key in
-                q)  f 2;break
-                    ;;
-            [1-9])  if [[ ${php_versions[$key-1]} ]]; then
-                        P;pf;echo "Your choice:$(Yi) php${php_versions[$key-1]}";N
-                        anykey
+    f; o 10; echo "$(button q) - do nothing, quit"
+    N; f
+    while :;do read -rsn 1 -p "$(pf; Y)Please make your choice: $(N)" key
+        if confirm_choice "$key" "You selected option $(button $key) Is this correct?"; then
+            f; P; pf; echo -n "Confirmed choice $(button $key)"; N
+            case $key in
+                    q)  P; echo ":$(Yi) quit, nothing changed"; N
                         separator
-                        q0 apt-mark manual $(${BINARIES[dpkg]} -l | ${BINARIES[gawk]} '/^[hiu]i.*php*/{print $2}')
-                        set_selections 'ph(ar|p)' 'manual' "${PHPVREGEX#php}" "${php_versions[$key-1]}"
-                        cleanup_and_fix_alternatives afterwards  # repair broken alternatives, remove not existing alternatives
-                        mapfile -t selections< <(update-alternatives --get-selections | ${BINARIES[grep]} -E "ph(ar|p)")
-                        o3;dY;echo "alternatives system is now switch to:";N
-                        f
-                        for i in ${!selections[@]}; do
-                            o3;pf;echo "$(lG)${selections[i]}";N
-                        done
-                        f
-                        Y;echo "  $(format_string "Please consider: $(dY)if some alternatives listed here are not switched to the selected version, then either the package that provides the binaries for that version is not installed or – in case of $(G)php-fpm.sock$(dY) – the default fpm-pool $(G)[www]$(dY) has been deactivated in the selected version but not in the version that it shows here." 3)"
-                        f
-                        anykey
-                        separator
-                        load_server_status
-                        populate_httpd_ enabled
-                        populate_httpd_ active
-                        populate_httpd_ wk_enabled
-                        populate_httpd_ wk_active
-                        (( ${#HTTPD_ENABLED[@]} )) || { o3;Pbg;bundle echo " - This script could not detect any enabled httpd (webserver). $(N)"; exit0; }
-                        switch_fpm_version ${php_versions[$key-1]}
-                        ret=$?
-                        if (( ret )); then
-                            o3;bundle echo "$(xpf; R; format_string "Something went wrong while switching the $(dY)Fast Process Manager SAPI $(GRAY)(php-fpm)$(R) version." 6;N)"
-                            case $ret in
-                                2)  o3; bundle echo "$(xpf; R; format_string "From the point of view of this script, it looks like the $(dY)PHP Fast Process Manager$(GRAY) php-fpm$(R) is not installed in any version." 6;N)"
-                                    ;;
-                                3)  o3; bundle echo "$(xpf; R; format_string "The $(dY)PHP Fast Process Manager$(R) for version $(Y)${php_versions[$key-1]} $(GRAY)(php${php_versions[$key-1]}-fpm)$(R) is not installed." 6;N)"
-                            esac
+                        break
+                        ;;
+                [1-9])  if [[ ${php_versions[$key-1]} ]]; then
+                            P; echo ":$(Yi) php${php_versions[$key-1]}"; N
+#                            anykey_noquit
+                            separator
+                            q0 apt-mark manual $(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*php*/{print $2}')
+                            set_selections 'ph(ar|p)' 'manual' "${PHPVREGEX#php}" "${php_versions[$key-1]}"
+                            cleanup_and_fix_alternatives afterwards  # repair broken alternatives, remove not existing alternatives
+                            mapfile -t selections< <(update-alternatives --get-selections | ${X[grep]} -E "ph(ar|p)")
+                            o3; dY; echo "alternatives system is now switch to:"; N
+                            f
+                            for i in ${!selections[@]}; do
+                                o3; pf; echo "$(lG)${selections[i]}"; N
+                            done
+                            f
+                            Y;echo "  $(format_string "Please consider: $(dY)if some alternatives listed here are not switched to the selected version, then either the package that provides the binaries for that version is not installed or – in case of $(G)php-fpm.sock$(dY) – the default fpm-pool $(G)[www]$(dY) has been deactivated in the selected version but not in the version that it shows here." 3)"
                             f
                             anykey
-                            break
-                        fi
-                        if (( ${HTTPD[apache2]} )); then
-                            switch_a2module_version ${php_versions[$key-1]}
+                            separator
+                            load_server_status
+                            populate_httpd_ enabled
+                            populate_httpd_ active
+                            populate_httpd_ wk_enabled
+                            populate_httpd_ wk_active
+                            (( ${#HTTPD_ENABLED[@]} )) || { o3; Pbg; bundle echo " - This script could not detect any enabled httpd (webserver). $(N)"; exit0; }
+                            switch_fpm_version ${php_versions[$key-1]}
                             ret=$?
                             if (( ret )); then
-                                o3;bundle echo "$(xpf; R; format_string "Something went wrong while switching the $(dY)apache2handler SAPI $(GRAY)(libapache2-mod-php)$(R) to version ${php_versions[$key-1]}." 6;N)"
+                                o3;bundle echo "$(xpf; R; format_string "Something went wrong while switching the $(dY)Fast Process Manager SAPI $(GRAY)(php-fpm)$(R) version." 6; N)"
                                 case $ret in
-                                    2)  o3; bundle echo "$(xpf; R; format_string "From the point of view of this script, it looks like the $(dY)apache2handler SAPI$(GRAY) libapache2-mod-php$(R) is not installed in any version." 6;N)"
+                                    2)  o3; bundle echo "$(xpf; R; format_string "From the point of view of this script, it looks like the $(dY)PHP Fast Process Manager$(GRAY) php-fpm$(R) is not installed in any version." 6; N)"
                                         ;;
-                                    3)  o3; bundle echo "$(xpf; R; format_string "The $(dY)apache2handler SAPI$(R) for version $(Y)${php_versions[$key-1]} $(GRAY)(libapache2-mod-php${php_versions[$key-1]})$(R) is not installed." 6;N)"
-                                        ;;
-                                    4)  o3;O;bundle echo "Skipped the apache2 server due to its inactive state.";N
-                                        o3;O;bundle echo "You should first start the apache2 server and run";N
-                                        f;G;bundle echo "$(prompt;P) $me${FLAG[forceflag]} --switch-version";N
-                                        f;o3;O;bundle echo ".. again if you want to switch the $(dY)apache2handler SAPI$(O) to $(C)${php_versions[$key-1]}";N
+                                    3)  o3; bundle echo "$(xpf; R; format_string "The $(dY)PHP Fast Process Manager$(R) for version $(Y)${php_versions[$key-1]} $(GRAY)(php${php_versions[$key-1]}-fpm)$(R) is not installed." 6; N)"
                                 esac
                                 f
                                 anykey
                                 break
                             fi
+                            if (( ${HTTPD[apache2]} )); then
+                                switch_a2module_version ${php_versions[$key-1]}
+                                ret=$?
+                                if (( ret )); then
+                                    o3; bundle echo "$(xpf; R; format_string "Something went wrong while switching the $(dY)apache2handler SAPI $(GRAY)(libapache2-mod-php)$(R) to version ${php_versions[$key-1]}." 6; N)"
+                                    case $ret in
+                                        2)  o3; bundle echo "$(xpf; R; format_string "From the point of view of this script, it looks like the $(dY)apache2handler SAPI$(GRAY) libapache2-mod-php$(R) is not installed in any version." 6; N)"
+                                            ;;
+                                        3)  o3; bundle echo "$(xpf; R; format_string "The $(dY)apache2handler SAPI$(R) for version $(Y)${php_versions[$key-1]} $(GRAY)(libapache2-mod-php${php_versions[$key-1]})$(R) is not installed." 6; N)"
+                                            ;;
+                                        4)  o3; O; bundle echo "Skipped the apache2 server due to its inactive state."; N
+                                            o3; O; bundle echo "You should first start the apache2 server and run"; N
+                                            f; G; bundle echo "$(prompt;P) $me${FLAG[forceflag]} --switch-version"; N
+                                            f; o3; O; bundle echo ".. again if you want to switch the $(dY)apache2handler SAPI$(O) to $(C)${php_versions[$key-1]}"; N
+                                    esac
+                                    f
+                                    anykey
+                                    break
+                                fi
+                            fi
+                            separator
+                            f
+                            o3; dY; echo "This is how php is connected to the httpd now:"; N
+                            f
+                            list_installed_sapi
+                            N
+                            line '=' P 2/78 b1
+                            f
+                            anykey_noquit
+                            o3; N; echo "If everything has gone as expected up to this point, you should once more run"
+                            f; G; echo "$(prompt;lB) $me${FLAG[forceflag]}$(C) --list-installed"; N
+                            f; o2; echo "$(format_string ".. until the end (do not quit in between), not only to look if the switch worked but to scan once more for possible configuration errors from the point of view of the new version. If everything looks good and is working well, considder to completely remove the old php version, to free up system resources." 3)"
+                            f
+                            anykey_noquit
+                            break
                         fi
-                        separator
-                        f
-                        o3;dY;echo "This is how php is connected to the httpd now:";N
-                        f
-                        list_installed_sapi
-                        N
-                        line '=' P 2/78 b1
-                        f
-                        anykey_noquit
-                        o3;N;echo "If everything has gone as expected up to this point, you should once more run"
-                        f;G;echo "$(prompt;lB) $me${FLAG[forceflag]}$(C) --list-installed";N
-                        f;o2;echo "$(format_string ".. until the end (do not quit in between), not only to look if the switch worked but to scan once more for possible configuration errors from the point of view of the new version. If everything looks good and is working well, considder to completely remove the old php version, to free up system resources." 3)"
-                        f
-                        anykey_noquit
-                        break
-                    fi
-        esac
+            esac
+        else
+            echo -e "\n\tChoice $(button $key) cancelled\n"
+            sleep 2
+            te0 8
+        fi
     done
     q0 di ff &
     contribute_
diff --git a/modules/tempfile b/modules/tempfile
--- a/modules/tempfile
+++ b/modules/tempfile
@@ -7,7 +7,7 @@ __copyright__
 __license__
 #
 
-${TEMPFILE_BASHLIB:-false} && return
+${TEMPFILE_BASHLIB:-_} && return
 TEMPFILE_BASHLIB=:
 
 . <(lrequire binaries)
@@ -18,21 +18,21 @@ TEMPFILE_BASHLIB=:
 [ -d "$TMPDIR" ] || TMPDIR='/temp'
 
 # unprivileged users need their own writable tmp dir:
-if (( $(${BINARIES[id]} -u) )); then
+if (( $(${X[id]} -u) )); then
     TMPDIR="${TMPDIR%/}"
-    if (( $(${BINARIES[gawk]} -F/ '{print NF-1}' <<< "$TMPDIR") == 1 )) && [ -w "$TMPDIR" ]; then
-        TMPDIR="$TMPDIR/user-$(${BINARIES[id]} -u)"
+    if (( $(${X[gawk]} -F/ '{print NF-1}' <<< "$TMPDIR") == 1 )) && [ -w "$TMPDIR" ]; then
+        TMPDIR="$TMPDIR/user-$(${X[id]} -u)"
     elif [ ! -w "$TMPDIR" ]; then
-        TMPDIR="$(${BINARIES[gawk]} -F/ '{print "/"$2}' <<< "$TMPDIR")/user-$(${BINARIES[id]} -u)"
+        TMPDIR="$(${X[gawk]} -F/ '{print "/"$2}' <<< "$TMPDIR")/user-$(${X[id]} -u)"
     fi
-    [ -d "$TMPDIR" ] || q0 ${BINARIES[mkdir]} -m 755 "$TMPDIR"
+    [ -d "$TMPDIR" ] || q0 ${X[mkdir]} -m 755 "$TMPDIR"
 fi
 declare ttf
-ttf="$(${BINARIES[mktemp]} -p "$TMPDIR")"
+ttf="$(${X[mktemp]} -p "$TMPDIR")"
 if [[ -n "$ttf" && -f "$ttf" ]]; then
-    ${BINARIES[rm]} -f -- "$ttf"
+    ${X[rm]} -f -- "$ttf"
 else
-    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '$(${BINARIES[id]} -un)'\e[0m" >&2
+    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '$(${X[id]} -un)'\e[0m" >&2
     [ -t 0 ] || exit 1
 fi
 unset ttf
@@ -46,13 +46,13 @@ tf(){
       666|777)  mode=$arg
         esac
     done
-    t="$(${BINARIES[mktemp]} -p $TMPDIR -${u}t ${bm}$$_XXXXXXXXXXXX)"
+    t="$(${X[mktemp]} -p $TMPDIR -${u}t ${bm}$$_XXXXXXXXXXXX)"
 # TODO 0 -->
-#    t="$(${BINARIES[mktemp]} -p $TMPDIR -${u}t ${bm:-$$}_XXXXXXXXXXXX)"
+#    t="$(${X[mktemp]} -p $TMPDIR -${u}t ${bm:-$$}_XXXXXXXXXXXX)"
 # TODO <-- 0
     if [ -z "$u" ]; then
         if [ -n "$mode" ]; then
-            ${BINARIES[chmod]} $mode "$t"
+            ${X[chmod]} $mode "$t"
         fi
     fi
     echo "$t"
diff --git a/scripts/nc-apps b/scripts/nc-apps
--- a/scripts/nc-apps
+++ b/scripts/nc-apps
@@ -9,30 +9,17 @@ __license__
 
 __scriptname__
 
-dependencies=(
-    "gawk#gawk#GNU awk"
-    "grep#grep#GNU grep, egrep and fgrep"
-    "less#less#A terminal pager similar to more"
-    "curl#curl#Command line file transfer tool with URL syntax"
-    "gpg#gnupg#GNU Privacy Guard"
-    "xmlstarlet#xmlstarlet#Command line XML toolkit"
-    "jq#jq#Command line JSON processor"
-    "sqlite3#sqlite3#Command line interface for SQLite 3"
-    "php#php-cli#PHP Commandline Interface"
-)
 modules=(
-    binaries basics awksed tempfile ansi prefix button exit spinner anykey line
-    array ask sudo dependency vdir integrity php/version nc/nextcloud xml
-    $sin/github_api $sin/app_update $sin/filters $sin/db $sin/appstore
-    $sin/data_refine $sin/assumed_version $sin/list $sin/install_overwrite
-    $sin/l10n $sin/help
+    binaries basics awksed tempfile ansi filter prefix button exit spinner
+    anykey line array ask sudo dependency xml vdir integrity php/version
+    nc/nextcloud $sin/github_api $sin/app_update $sin/filters $sin/db
+    $sin/appstore $sin/data_refine $sin/assumed_version $sin/list
+    $sin/install_overwrite $sin/l10n $sin/help
 )
 __debug__
 # use parallel running background jobs in order to dramatically increase speed
-#declare bgjobs=false debug=true pager
-#declare bgjobs=false debug=false pager
-declare bgjobs=true debug=false pager
-$bgjobs&&{ [[ -t 1&&! -p /dev/stdout ]]&&pager=false||pager=true;} # is piped to pager?
+B[bgjobs]=: B[trace]=_
+${B[bgjobs]} && { [[ -t 1 && ! -p /dev/stdout ]] && B[pager]=_ || B[pager]=:; } # is piped to pager?
 
 __when__
 
@@ -53,69 +40,87 @@ contribute_(){
 [[ "$@" =~ (donat|contrib) ]] && contribute_
 
 all_apps(){
-    stock_up_arrays filtered_appstore=true
-    local s=false ns=false up=false
+    stock_up_arrays filtered_appstore=:
+    local all_endis app
     local -a args
-$debug&&echo "$LINENO $*"
-$debug&&set -x
-    while (($#));do
-        case $1 in
-            shipped)
-                s=true
-                shift;;
-            not_shipped)
-                ns=true
-                shift;;
-            updatable)
-                up=true
-                shift;;
-            enabled|disabled|local|store|all)
-                all_endis=$1
-                shift;;
-            *)  args+=("$1")
-                shift
+    local -A bool
+# TODO 0 -->
+    if ${B[trace]:-_}; then
+        echo "==TRACE=start=" >/dev/tty
+        print_stack_trace >/dev/tty
+        echo -n "global bool values  -" >/dev/tty
+        local iter
+        for iter in ${!B[@]}; do echo -n " $iter=${B[$iter]}" >/dev/tty; done; echo >/dev/tty
+        unset iter
+        if q2 declare -p bool | ${X[grep]} -qs '^declare -A'; then
+            local iter
+            echo -n "local bool values   -" >/dev/tty
+            for iter in ${!bool[@]}; do echo -n " $iter=${bool[$iter]}" >/dev/tty; done; echo >/dev/tty
+            unset iter
+        fi
+        echo "app_id              - $id" >/dev/tty
+        echo "section             - $section" >/dev/tty
+        echo "v2i nc_version      - $(v2i ${nc_version%.*})" >/dev/tty
+        echo "v2i nc_key          - $(v2i $nc_key)" >/dev/tty
+        echo "==TRACE=end===" >/dev/tty
+    fi
+# TODO <-- 0
+    while (( $# )); do
+        shopt -s extglob
+        case "$1" in
+                        shipped) bool[s]=:;      shift ;;
+                    not_shipped) bool[ns]=:;     shift ;;
+                      updatable) bool[up]=:;     shift ;;
+ ?(en|dis)abled|local|store|all) all_endis="$1"; shift ;;
+                              *) args+=("$1");   shift
         esac
+        shopt -u extglob
     done
-    $s||$up&&[ "$all_endis" = all -o "$all_endis" = store ]&&all_endis=local
-    for app in $(apps_ $all_endis);do
-        if $s;then # shellcheck disable=SC2068 # only list the shipped apps
-            is_shipped_ "$app" -q&&list $app ${args[@]}
-        elif $ns;then # shellcheck disable=SC2068 # only list the not shipped apps
-            is_shipped_ "$app" -q||list $app ${args[@]}
-        elif $up;then # shellcheck disable=SC2068 # only list the updatable apps
-            echo ${availupd[@]%%#*}|${BINARIES[grep]} -qsw "$app"&&list $app ${args[@]}
-        else # shellcheck disable=SC2068 # list all apps
-            list $app ${args[@]}
+    ( ${bool[s]:-_} || ${bool[up:-_]} ) && [[ "$all_endis" =~ all|store ]] && all_endis=local
+    for app in $(apps_ "$all_endis"); do
+        if ${bool[s]:-_}; then     # only list the shipped apps
+            is_shipped_ "$app" -q && list "$app" "${args[@]}"
+        elif ${bool[ns]:-_}; then  # only list the not shipped apps
+            is_shipped_ "$app" -q || list "$app" "${args[@]}"
+        elif ${bool[up]:-_}; then  # only list the updatable apps
+            [[ " ${availupd[@]%%#*} " =~ " $app " ]] && list "$app" "${args[@]}"
+        else # list all apps
+            list "$app" "${args[@]}"
         fi
     done
 }
 
-# shellcheck disable=SC2068
-shipped(){ all_apps shipped $@;}
-# shellcheck disable=SC2068
-not_shipped(){ all_apps not_shipped $@;}
-# shellcheck disable=SC2068
-updatable(){ all_apps updatable $@;}
+shipped(){ all_apps shipped "$@" use_json_all=${B[use_json_all]}; }
 
-id(){ stock_up_arrays filtered_appstore=true all=true;local app
-     # shellcheck disable=SC2068
-#    for app in $(apps_ all);do echo $app|${BINARIES[grep]} -iqs "$app_id"&&list $app $@ use_json_all=true;done
-    for app in $(apps_ all);do [[ "$app" =~ $app_id ]]&&list $app $@ use_json_all=true;done
+not_shipped(){ all_apps not_shipped "$@" use_json_all=${B[use_json_all]}; }
+
+updatable(){ all_apps updatable "$@" use_json_all=${B[use_json_all]}; }
+
+id(){
+    stock_up_arrays filtered_appstore=: all=:
+    local app
+    for app in $(apps_ all); do [[ "${app,,}" =~ ${app_id,,} ]] && list "$app" "$@" use_json_all=:; done
 }
 
-ids(){ stock_up_arrays filtered_appstore=true all=true;local -i i
-    for i in ${!app_ids[@]};do list ${app_ids[i]} $@ use_json_all=true;done
+ids(){
+    stock_up_arrays filtered_appstore=: all=:
+    local app_id
+    for app_id in ${app_ids[@]}; do list "$app_id" "$@" use_json_all=:; done
 }
 
-name(){ stock_up_arrays filtered_appstore=true all=true
-    build_id_name_array(){ local app xml_f name tmp=$1;shift
-        appstore platform=all ".[]|select(.name|ascii_downcase|contains(\"$(tolower "$@")\"))|.id"|${BINARIES[jq]} -r >> $tmp
-        for app in $(apps_ all);do
-            if ! ${BINARIES[grep]} -qsw "$app" $tmp;then
+name(){
+    stock_up_arrays filtered_appstore=: all=:
+    build_id_name_array(){
+        local app xml_f name tmp
+        tmp="$1"
+        shift
+        appstore platform=all ".[]|select(.name|ascii_downcase|contains(\"$(tolower "$@")\"))|.id" | ${X[jq]} -r >> "$tmp"
+        for app in $(apps_ all); do
+            if ! ${X[grep]} -qsw "$app" "$tmp"; then
                 xml_f="$NC_DIR/apps/$app/appinfo/info.xml"
-                if [ -f "$xml_f" ];then
-                    name=$(xmls -v "(//info/name)" "$xml_f"|${BINARIES[sed]} '2,$d')
-                    echo "$name"|${BINARIES[grep]} -iqs "$*"&&echo "$app" >> $tmp
+                if [ -f "$xml_f" ]; then
+                    name=$(xmls -v "(//info/name)" "$xml_f" | ${X[sed]} '2,$d')
+                    echo "$name" | ${X[grep]} -iqs "$*" && echo "$app" >> "$tmp"
                 fi
             fi
         done
@@ -125,22 +130,25 @@ name(){ stock_up_arrays filtered_appstore=true all=true
     spinner &
     build_id_name_array $n_tmp "$app_name" & job_id=$!
     wait $job_id
-    mapfile id_name_array < $n_tmp
+    mapfile id_name_array < "$n_tmp"
     kill_spinner
-     # shellcheck disable=SC2068
-    for app in "${id_name_array[@]}";do list $app $@ use_json_all=true;done
+    for app in "${id_name_array[@]}";do list "$app" "$@" use_json_all=:; done
 }
 
-update(){ local -a args
-    stock_up_arrays filtered_appstore=true
-    while (($#));do
-        case $1 in
-            enabled|disabled|local|all) all_endis=$1;shift;;
-            *) args+=("$1");shift
+update(){
+    stock_up_arrays filtered_appstore=:
+    local -a args
+    while (($#)); do
+        case "$1" in
+            enabled|disabled|local|all)
+                all_endis=$1
+                shift ;;
+            *)  args+=("$1")
+                shift
         esac
     done
-    for app in $(apps_ $all_endis);do
-        echo ${availupd[@]%%#*}|${BINARIES[grep]} -qsw "$app"&&do_update_ $app "${args[@]}"
+    for app in $(apps_ $all_endis); do
+        echo ${availupd[@]%%#*} | ${X[grep]} -qsw "$app" && do_update_ $app "${args[@]}"
     done
 }
 
@@ -152,96 +160,103 @@ nc_version_string="$(nc_version_ string "$NC_DIR/version.php")"
 nc_version_tag="$(tolower "${nc_version_string// /}")"
 nc_min_version="${LATEST_EOL[0]}" # this is only prefilled here -> changed by assumed_version module
 
-if echo $(r_db .tables;) | ${BINARIES[grep]} -qs "database_created"; then
-    database_created=true
-fi
+# declared in $sin/db:
+echo $(r_db .tables;) | ${X[grep]} -qs "database_created" && B[database_created]=:
 
-# first search for options --nopager --markdown secondrun lang=xx, --(un)supported and remove from @() array
-# and then add the remaining arguments into the new array
-declare secondrun=false nopager=false markdown=false supported=false unsupported=false use_json_all=false update_first=false allow_unstable=false
-args=()
+declare bool arg
+declare -a bools args
+bools=(secondrun nopager markdown supported unsupported use_json_all update_first allow_unstable)
+for bool in ${bools[@]}; do B[$bool]=_; done
+unset -v bool bools
+
+shopt -s extglob
 for arg in "$@";do
-    if [ "$arg" = "secondrun" ];then secondrun=true
-    elif [ "${arg%=*}" = "lang" ];then lang="$(validate_language ${arg#*=})"
-    elif [ "$arg" = "--nopager" ];then nopager=true
-    elif [ "$arg" = "--no_pager" ];then nopager=true
-    elif [ "$arg" = "--no-pager" ];then nopager=true
-    elif [ "$arg" = "--markdown" ];then markdown=true
-    elif [ "$arg" = "--md" ];then markdown=true
-    elif [ "$arg" = "--supported" ];then supported=true
-    elif [ "$arg" = "--unsupported" ];then unsupported=true use_json_all=true
-    elif [ "$arg" = "--alt" ];then use_json_all=true
-    elif [ "$arg" = "-u" ];then update_first=true
-    elif [ "$arg" = "--update_first" ];then update_first=true
-    elif [ "$arg" = "--update-first" ];then update_first=true
-    elif [ "$arg" = "--allow_unstable" ];then allow_unstable=true
-    elif [ "$arg" = "--allow-unstable" ];then allow_unstable=true
-    elif [ "${arg%=*}" = "version" ];then declare nc_${arg}
-    elif [ "${arg%=*}" = "min_version" ];then declare nc_${arg}
-    elif [ "$arg" = "rebuild_db" ];then $database_created&&rebuild_db
-    elif [ "$arg" = "rebuild-db" ];then $database_created&&rebuild_db
-    elif [ "$arg" = "--rebuild_db" ];then $database_created&&rebuild_db
-    elif [ "$arg" = "--rebuild-db" ];then $database_created&&rebuild_db
-    else args+=("$arg")
-    fi
+    case "$arg" in
+               secondrun) B[secondrun]=:                          ;;
+                  lang=*) lang="$(validate_language "${arg#*=}")" ;;
+        --no?([_-])pager) B[nopager]=:                            ;;
+        --@(markdown|md)) B[markdown]=:                           ;;
+             --supported) B[supported]=:                          ;;
+           --unsupported) B[unsupported]=: B[use_json_all]=:      ;;
+                   --alt) B[use_json_all]=:                       ;;
+ -u|--update?([_-])first) B[update_first]=:                       ;;
+  --allow?([_-])unstable) B[allow_unstable]=:                     ;;
+        ?(min_)version=*) declare nc_$arg                         ;;
+      ?(--)rebuild[-_]db) ${B[database_created]} && rebuild_db    ;;
+              ?(--)trace) B[trace]=:                              ;;
+                       *) args+=("$arg")
+    esac
 done
-set -- "${args[@]}"&&unset -v args
+set -- "${args[@]}" && unset -v args
 
-if $supported && $unsupported; then
-    f;o2;R;echo "--supported and --unsupported are passed both but are mutually exclusive"
-    o2;echo "--supported and --unsupported will be ignored";N;f
-    supported=false unsupported=false
+if ${B[supported]} && ${B[unsupported]}; then
+    f; o2; R; echo "--supported and --unsupported are passed both but are mutually exclusive"
+    o2; echo "--supported and --unsupported will be ignored"; N; f
+    B[supported]=_ B[unsupported]=_
     anykey
 fi
 
-shopt -s extglob
-while (($#));do
-    case $1 in
+while (($#)); do
+    case "$1" in
         appstore)
             shift
             appstore platform=all "$@"
             break 2
             ;;
         install_overwrite)
-            database_created=true nopager=true command=$1
-            $update_first&&command="$1 -u"
-            $update_first&&$allow_unstable&&command="$1 -u --allow-unstable"
+            B[database_created]=: B[nopager]=: command="$1"
+            ${B[update_first]} && command="$1 -u"
+            ${B[update_first]} && ${B[allow_unstable]} && command="$1 -u --allow-unstable"
             break 2
             ;;
         ?(not_)shipped|all_apps|updat@(e|able))
-            case $1 in
+            case "$1" in
                 shipped|updat@(e|able))
-                    $supported&&{ f;o2;R;echo "--supported will be ignored since it is implied within \"$1\"";N;f;supported=false;anykey;}
-                    $unsupported&&{ f;o2;R;echo "--unsupported will be ignored since it is mutually exclusive with \"$1\"";N;f;unsupported=false;anykey;}
+                    if ${B[supported]}; then
+                        f; o2; R; echo "--supported will be ignored since it is implied within \"$1\""; N; f
+                        B[supported]=_
+                        anykey
+                    elif ${B[unsupported]}; then
+                        f; o2; R; echo "--unsupported will be ignored since it is mutually exclusive with \"$1\""; N; f
+                        B[unsupported]=_
+                        anykey
+                    fi
+                    ;;
+                *)  :
             esac
-            case $2 in
-                ?(en|dis)abled|local|store|all) command="$1 $2"
-                                    shift 2
-                                    ;;
-                *)                  command="$1 enabled"
-                                    shift
+            case "$2" in
+                ?(en|dis)abled|local|store|all)
+                    command="$1 $2"
+                    shift 2
+                    ;;
+                *)  command="$1 enabled"
+                    shift
             esac
-            $allow_unstable&&[[ "$command" =~ update ]]&&command="$command --allow-unstable"
+            ${B[allow_unstable]} && [[ "$command" =~ update ]] && command="$command --allow-unstable"
             ;;
         @(name|id)=+([a-zA-Z0-9-_ ]))
-            command=${1%=*}
+            command="${1%=*}"
             declare app_${1%=*}="${1#*=}"
-            nopager=true
-#            use_json_all=true
+            B[nopager]=:
+# TODO 1 -->
+            B[use_json_all]=:
+# TODO <-- 1
             shift
             ;;
         ids)
-            command=$1
+            command="$1"
             shift
             declare -a app_ids
             app_ids=("${@}")
-            nopager=true
+            B[nopager]=:
             break 2
             ;;
-#        version=[1-9]?([0-9]))
+# TODO 2 -->
+        version=[1-9]?([0-9]))
+# TODO <-- 2
         --min@(_|-)version=*)
             assumed_version_set ${1#*=} min_
-            use_json_all=true
+            B[use_json_all]=:
             shift
             ;;
         --version=*)
@@ -254,60 +269,70 @@ while (($#));do
             ;;
         -h|--help)
             command=print_help
-            $nopager&&command='print_help --cat'
+            ${B[nopager]} && command='print_help --cat'
             break 2
             ;;
         --php=*)
-            [[ " ${available_php_versions[*]} " =~ ${1#*=} ]]&&php_version="${1#*=}"||echo "$(Pbg) ERROR: php${1#*=} not found. $(N)"
+            [[ " ${available_php_versions[*]} " =~ ${1#*=} ]] && php_version="${1#*=}" || echo "$(Pbg) ERROR: php${1#*=} not found. $(N)"
             shift
             ;;
-#        *)  $@
-#            exit 0
+# TODO 3 -->
+        *)  $@
+            exit 0
+# TODO <-- 3
         *)  echo "unknown option $1"
             print_help
     esac
 done
 shopt -u extglob
 
-if $supported; then unsupported=false
-    declare suppunsupp="supp=true"
-elif $unsupported; then supported=false
-    declare suppunsupp="unsupp=true"
+${B[trace]} && B[bgjobs]=_
+if ${B[supported]}; then
+    B[unsupported]=_
+    declare suppunsupp="supp=:"
+elif ${B[unsupported]}; then
+    B[supported]=_
+    declare suppunsupp="unsupp=:"
 fi
 
-[ "${command:=print_help}" = "print_help" ]&&nopager=true
-[ "${command:=filters}" = "filters" ]&&nopager=true
+[ "${command:=print_help}" = "print_help" ] && B[nopager]=:
+[ "${command:=filters}" = "filters" ] && B[nopager]=:
 # yes, this must be "updat", since it must match with "update" AND "updatable"
-echo $command|${BINARIES[grep]} -qs updat&&nopager=true
+echo $command | ${X[grep]} -qs updat && B[nopager]=:
 
 # create the database if it does not exist
-$database_created||create_database
+${B[database_created]} || create_database
 
-if $secondrun||${nopager:=false};then
+if ${B[secondrun]} || ${B[nopager]:=_}; then
     line '-' GRAY 80 b1
     printf "command = \"$command\""
-    [ "$command" = "name" ]&&printf ", app_name = \"$app_name\""
-    [ "$command" = "id" ]&&printf ", app_id = \"$app_id\""
-    $supported&&printf ", only supported"
-    $unsupported&&printf ", only unsupported"
-    printf ", markdown = $markdown"
+    [ "$command" = "name" ] && printf ", app_name = \"$app_name\""
+    [ "$command" = "id" ] && printf ", app_id = \"$app_id\""
+    ${B[supported]} && printf ", only supported"
+    ${B[unsupported]} && printf ", only unsupported"
+    printf ", markdown = $(${B[markdown]} && printf 'true' || printf 'false')"
     printf ", nopager = "
-    $secondrun&&printf "false"||printf "$nopager"
+    ${B[secondrun]} && printf 'false' || { ${B[nopager]} && printf 'true' || printf 'false'; }
     echo ", lang = $lang"
     echo "Versions: assumed = $nc_version, is = $nc_version_long, min = $nc_min_version, php = $(php_ver)"
     line '-' GRAY 80
     line '=' N 80
-    $markdown&&command="$command md=true"
+    ${B[markdown]} && command="$command md=:"
+# TODO 4 -->
+    $command $suppunsupp use_json_all=${B[use_json_all]}
+# TODO <-- 4
     $command $suppunsupp
 else
-    if $supported; then
-        $me secondrun lang=$lang --supported --nopager min_version=$nc_min_version version=$nc_version $command|${BINARIES[less]} -R
-    elif $unsupported; then
-        $me secondrun lang=$lang --unsupported --nopager min_version=$nc_min_version version=$nc_version $command|${BINARIES[less]} -R
-#    elif $use_json_all; then
-#        $me secondrun lang=$lang --alt --nopager min_version=$nc_min_version version=$nc_version $command|${BINARIES[less]} -R
+    if ${B[supported]}; then
+        $me secondrun lang=$lang --supported --nopager min_version=$nc_min_version version=$nc_version $command | ${X[less]} -R
+    elif ${B[unsupported]}; then
+        $me secondrun lang=$lang --unsupported --nopager min_version=$nc_min_version version=$nc_version $command | ${X[less]} -R
+# TODO 5 -->
+    elif ${B[use_json_all]}; then
+        $me secondrun lang=$lang --alt --nopager min_version=$nc_min_version version=$nc_version $command | ${X[less]} -R
+# TODO <-- 5
     else
-        $me secondrun lang=$lang --nopager min_version=$nc_min_version version=$nc_version $command|${BINARIES[less]} -R
+        $me secondrun lang=$lang --nopager min_version=$nc_min_version version=$nc_version $command | ${X[less]} -R
     fi
     exit 0
 fi
diff --git a/scripts/nc-mimecheck b/scripts/nc-mimecheck
--- a/scripts/nc-mimecheck
+++ b/scripts/nc-mimecheck
@@ -25,21 +25,15 @@ __license__
 
 __scriptname__
 
-deps=(
-    "gawk#gawk#GNU awk"
-    "grep#grep#GNU grep, egrep and fgrep"
-    "gpg#gnupg#GNU Privacy Guard"
-    "jq#jq#command-line JSON processor"
-)
 modules=(
-    binaries basics awksed tempfile ansi prefix button exit anykey verbose line
-    array ask sudo dependency vdir integrity nc/nextcloud nc/nextcloud_db
-    $sin/mime_types $sin/help $sin/functions
+    binaries basics awksed tempfile ansi filter prefix button exit anykey line
+    verbose array ask sudo dependency vdir integrity nc/nextcloud
+    nc/nextcloud_db $sin/mime_types $sin/help $sin/functions
 )
 
-# make module loading quiet if -q or --quiet is passed
-for a in "$@";do [[ "$a" == '-q'||"$a" == '--quiet' ]]&&declare pager=:;done;unset -v a
 __debug__
+# make module loading quiet if -q or --quiet is passed
+for a in "$@"; do [[ "$a" == '-q' || "$a" == '--quiet' ]] && B[pager]=:; done; unset -v a
 __when__
 
 __whoami_whereami__
@@ -58,56 +52,63 @@ contribute_(){
 }; donate_(){ contribute_;}
 [[ "$@" =~ (donat|contrib) ]] && contribute_
 
-declare bools="listmimes recursive dryrun verbose debug quiet bak enabled_user"
-# declare options
+declare -a bools vars
+bools=(listmimes recursive dryrun verbose debug quiet enabled_user)
+vars=(grepopts gg mimedetector options bool basepath nc_path tempfile iid blacklist listmimesoftype wom1 wom2)
+
+# set all ${bools[@]} to '_'
 reset_bools(){ local bool
-    for bool in $bools;do declare -g $bool=false;done
-}
+    for bool in ${bools[@]}; do B[$bool]=_; done
+}; reset_bools
 
-declare variables="options basepath nc_path tempfile
-                   iid blacklist listmimesoftype wom1 wom2"
-for undeclared_option in $bools $variables;do
-   declare $undeclared_option
+# declare all ${vars[@]}
+declare var
+for var in ${vars[@]}; do
+   declare $var
 done
-declare grepopts='-qs'
-# "woa" stands for wrong options array
-# "woi" stands for wrong option index
-declare -a woa;declare -i woi=0
-# green good
-declare gg="$(lG)Good!$(N)"
+unset -v var
 
-declare mimedetector="mimetype -b"
+grepopts='-qs'
+# green good:
+gg="$(lG)Good!$(N)"
+# the default mimedetector
+mimedetector="mimetype -b"
 #mimedetector="file -b --mime-type"
 
-# set all bools to 'false'
-reset_bools
+# TODO: does this have to be global?
+# "woa" stands for wrong options array
+declare -a woa
+# "woi" stands for wrong option index
+declare -i woi=0
 
 # parsing options
 # Check if -l|--list option has an argument and add 'all' if missing
+declare -a shiftedoption
 shopt -s extglob
 while (($#));do
     case "$1" in
         -l|--list)
-            if [[ -n "${2}"&&"${2}" != -* ]];then :;else
-                shift;set -- "-l" "all" "$@"
+            if ! [[ -n "$2" && "$2" != -* ]]; then
+                shift
+                set -- "-l" "all" "$@"
             fi
             break 2
             ;;
         --detector)
-            if [[ -n "${2}"&&"${2}" != -* ]];then
-                shiftedoption="$shiftedoption ${1} ${2}"
+            if [[ -n "$2" && "$2" != -* ]]; then
+                shiftedoption+=("$1" "$2")
                 shift 2
             fi
             ;;
         @(-)+([a-z])p)
-            if [[ -n "${2}"&&"${2}" != -* ]];then
-                shiftedoption="$shiftedoption ${1} ${2}"
+            if [[ -n "$2" && "$2" != -* ]]; then
+                shiftedoption+=("$1" "$2")
                 shift 2
             fi
             ;;
         @(-)+([a-z])l)
-            if [[ -n "${2}"&&"${2}" != -* ]];then :;else
-                set -- "${1}" "all" "${@:2}"
+            if ! [[ -n "$2" && "$2" != -* ]]; then
+                set -- "$1" "all" "${@:2}"
             fi
             break 2
             ;;
@@ -117,25 +118,24 @@ while (($#));do
             ;;
         --) break 2
             ;;
-        *)  shiftedoption="$shiftedoption ${1}"
+        *)  shiftedoption+=("$1")
             shift
-            ;;
     esac
 done
 shopt -u extglob
-[ -n "$shiftedoption" ]&&set -- $shiftedoption $@
-unset shiftedoption
+(( ${#shiftedoption[@]} )) && set -- "${shiftedoption[@]}" "$@"
+unset -v shiftedoption
 
-options=$(${BINARIES[getopt]} -o dhl:qrv -l help,listmimes:,detector:,dryrun,recursive,quiet,verbose,debug -qn "$me" -- "$@")
-if (($?==0));then
+options=$(${X[getopt]} -o dhl:qrv -l help,listmimes:,detector:,dryrun,recursive,quiet,verbose,debug -qn "$me" -- "$@")
+if (($?==0)); then
     eval set -- "$options"
-    while :;do
-        case $1 in
+    while :; do
+        case "$1" in
             -h|--help)
                 print_help
                 ;;
             -l|--listmimes)
-                listmimes=true
+                B[listmimes]=:
                 if [ -n "$2" ];then
                     listmimesoftype="$2"
                     shift 2
@@ -145,33 +145,27 @@ if (($?==0));then
                 fi
                 ;;
             --detector)
-                mimedetector=$2
+                mimedetector="$2"
                 shift 2
                 ;;
             -d|--dryrun)
-                dryrun=true
+                B[dryrun]=:
                 shift
                 ;;
             -r|--recursive)
-                recursive=true
+                B[recursive]=:
                 shift
                 ;;
             -q|--quiet)
-                quiet=true
+                B[quiet]=:
                 shift
                 ;;
             -v|--verbose)
-                if $verbose;then
-                    debug=true;grepopts=''
-                else
-                    verbose=true;grepopts='-q'
-                fi
+                ${B[verbose]} && B[debug]=: grepopts='' || B[verbose]=: grepopts='-q'
                 shift
                 ;;
             --debug)
-                verbose=true
-                debug=true
-                grepopts=''
+                B[verbose]=: B[debug]=: grepopts=''
                 shift
                 ;;
             --) shift
@@ -179,31 +173,31 @@ if (($?==0));then
                 ;;
             *)  wrong_option -r "Missing or unknown option $1"
                 shift
-                ;;
         esac
     done
 else
     wrong_option "Missing or unknown option"
 fi
 
-$debug&&set -x
+${B[debug]} && set -x
 
 # some verbose echos
 v_echo "$(P)all available options after parsing arguments:$(N)"
-v_echo "$(pf;Y)detector$(N)=\"$(G)$mimedetector$(N)\""
-for bool in $bools;do
-    eval v_echo \"\$\(pf\;Y\)$bool\$\(N\)=\$$bool\"
+v_echo "$(pf; Y)detector$(N)=\"$(G)$mimedetector$(N)\""
+for bool in ${bools[@]}; do
+    v_echo "$(pf; Y)$bool$(N)=${B[$bool]}"
 done
-v_echo "$(pf;Y)basepath$(N)=\"$(G)$*$(N)\""
+unset -v bool
+v_echo "$(pf; Y)basepath$(N)=\"$(G)$*$(N)\""
 
 # print suported mimes and exit, no further checks
-$listmimes&&{
-    if [ $listmimesoftype != 'false' ];then
-        if [ $listmimesoftype = 'all' ];then
+${B[listmimes]} && {
+    if [ $listmimesoftype != '_' ]; then
+        if [ $listmimesoftype = 'all' ]; then
             list_mimes "all" $(echo "${mime_ext_regex_array[@]}")
             exit 0
         else
-            for ((i=0;i<${#listmimesoftype};i++));do
+            for ((i=0;i<${#listmimesoftype};i++)); do
                 case ${listmimesoftype:i:1} in
                 i) list_mimes image $(echo "${mime_ext_regex_image[@]}")
                    ;;
@@ -229,7 +223,7 @@ $listmimes&&{
 # gathering all further errors in array, then echo all of them together
 
 # check path
-if ! $listmimes; then
+if ! ${B[listmimes]}; then
     if [ -z "$*" ]; then
         wrong_option -r "Missing path to directory or file to scan"
     else
@@ -247,17 +241,17 @@ fi
 wrong_option -x
 
 # cd into NC_DATADIR because nextcloud understands pathes from there
-if nc_configkey_exist_ datadirectory;then
+if nc_configkey_exist_ datadirectory; then
     NC_DATADIR="$(nc_configkey datadirectory)"
-    if [ -d "$NC_DATADIR" ];then
-        v_echo "$(pf;Y)the nextcloud data directory is$(N) \"$(B)$NC_DATADIR$(N)\""
+    if [ -d "$NC_DATADIR" ]; then
+        v_echo "$(pf; Y)the nextcloud data directory is$(N) \"$(B)$NC_DATADIR$(N)\""
     else
         error "can not find nextcloud data directory."
     fi
-elif [ -d "$NC_DIR/data" ];then
+elif [ -d "$NC_DIR/data" ]; then
     NC_DATADIR="$NC_DIR/data"
-    v_echo "$(pf;Y)no information about the nextcloud data directory,$(N)"
-    v_echo "$(pf;Y)use the default directory$(N) \"$(B)$NC_DATADIR$(N)\""
+    v_echo "$(pf; Y)no information about the nextcloud data directory,$(N)"
+    v_echo "$(pf; Y)use the default directory$(N) \"$(B)$NC_DATADIR$(N)\""
 else
     error "can not find nextcloud data directory."
 fi
@@ -265,16 +259,16 @@ fi
 cd "$NC_DATADIR"
 
 # remove absolute path to NC_DATADIR if not invoked by nextcloud flow
-basepath="$(echo "$*"|${BINARIES[sed]} 's\'$NC_DATADIR'/\\1')"
+basepath="$(echo "$*" | ${X[sed]} 's\'$NC_DATADIR'/\\1')"
 user2check="$(check_username_case "${basepath%%/*}")"
-[ "$user2check" = "${basepath%%/*}" ]||{
-    v_echo "$(pf;Y)user case corrected:$(N) from \"$(B)${basepath%%/*}$(N)\" to \"$(B)$user2check$(N)\" "
+[ "$user2check" = "${basepath%%/*}" ] || {
+    v_echo "$(pf; Y)user case corrected:$(N) from \"$(B)${basepath%%/*}$(N)\" to \"$(B)$user2check$(N)\" "
 }
 basepath="$user2check/${basepath#*/}"
-v_echo "$(pf;Y)relative basepath now is:$(N) \"$(B)$basepath$(N)\""
+v_echo "$(pf; Y)relative basepath now is:$(N) \"$(B)$basepath$(N)\""
 
 # now as we entered the data dir, we can check relative dir (or file)
-if [ ! -e "$basepath" ];then
+if [ ! -e "$basepath" ]; then
     wom1="$(Pbg)$*$(R) does not exist"
     wom2="path must look like: $(GRAY)($PWD/)$(Y)%USER%/files/path..$(N)"
     wrong_option -r "$wom1#$wom2"
@@ -284,24 +278,24 @@ fi
 # thoroughly but slowly tests
 iid="$(nc_configkey instanceid)"
 blacklist="appdata_$iid|updater-$iid"
-if echo "$basepath"|${BINARIES[grep]} -Eqs  "$blacklist";then
+if echo "$basepath" | ${X[grep]} -Eqs  "$blacklist"; then
     wrong_option "blacklisted filepath $(Pbg)$basepath$(N)"
 else
-    v_echo "$(pf;Y)basepath is no system dir (appdata or backup). $gg"
+    v_echo "$(pf; Y)basepath is no system dir (appdata or backup). $gg"
 fi
 
 # TODO: enable groupfolders
 #    groupfolder = __groupfolders/$groupfolder_id/
 # if groupfolder, not occ files:scan but occ groupfolders:scan
-if echo "$basepath"|${BINARIES[grep]} $grepopts "__groupfolders/[0-9]";then
+if echo "$basepath" | ${X[grep]} $grepopts "__groupfolders/[0-9]"; then
     wrong_option "groupfolders not (yet) supported"
 else
-    v_echo "$(pf;Y)basepath is not a groupfolder. $gg"
+    v_echo "$(pf; Y)basepath is not a groupfolder. $gg"
 fi
 
 # check if basepath is a user
 #       user dir = $user_id/files/
-#occ user:info "${basepath%%/*}"|${BINARIES[grep]} $grepopts "enabled: true"
+#occ user:info "${basepath%%/*}"|${X[grep]} $grepopts "enabled: true"
     # this does not work with usernames containing spaces:
     #if enabled_user="$(occ user:info --output=json -- "'$user2check'"|jq '.enabled')"; then
 if $(user_exists "$user2check"); then
@@ -310,12 +304,12 @@ if $(user_exists "$user2check"); then
         wrong_option "\"${basepath%%/*}\" is not an enabled user"
     else
         v_echo "$(pf)\"$(C)${basepath%%/*}$(N)\"$(Y) is an enabled user. $gg"
-        if [ "${basepath%%/*}" = "$basepath" ];then
+        if [ "${basepath%%/*}" = "$basepath" ]; then
             basepath="$basepath/files/"
-            v_echo "$(pf;Y)relative basepath now is:$(N) \"$(B)$basepath$(N)\""
+            v_echo "$(pf; Y)relative basepath now is:$(N) \"$(B)$basepath$(N)\""
         fi
-        if echo "$basepath/"|${BINARIES[grep]} $grepopts "^${basepath%%/*}/files/";then
-            v_echo "$(pf;Yi)basepath check succeeded. $gg"
+        if echo "$basepath/"|${X[grep]} $grepopts "^${basepath%%/*}/files/"; then
+            v_echo "$(pf; Yi)basepath check succeeded. $gg"
         else
             wom1="basepath $(Pbg)$basepath$(R)"
             wom2="is not in /files/ directory of user \"${basepath%%/*}\""
@@ -330,71 +324,71 @@ else
 fi
 
 # checks are done, now the work can begin
-$quiet||echo "$(Y)cd into nextcloud data directory:$(N) \"$(B)$NC_DATADIR$(N)\""
-v_echo "$(pf;Y)working directory (PWD) now is:$(N) \"$(B)$PWD$(N)\""
+${B[quiet]} || echo "$(Y)cd into nextcloud data directory:$(N) \"$(B)$NC_DATADIR$(N)\""
+v_echo "$(pf; Y)working directory (PWD) now is:$(N) \"$(B)$PWD$(N)\""
 
-$recursive&&v_echo "$(pf;Y)recursive set to$(N) \"$recursive\""
+${B[recursive]} && v_echo "$(pf; Y)recursive set to$(N) \"$recursive\""
 
 # define a temporary file
 tempfile="$(tf)"
-v_echo "$(pf;Y)temporary file:$(N) \"$(B)$tempfile$(N)\"$(Y) created$(N)"
+v_echo "$(pf; Y)temporary file:$(N) \"$(B)$tempfile$(N)\"$(Y) created$(N)"
 
 # function to write and read in the temporary file,
-# returns 'true'' or 'false'
-do_occ_filesscan(){ [ "$1" = "set" ]&&echo "$2" > $tempfile||cat $tempfile;}
-do_occ_filesscan set false
+# returns ':'' or '_'
+do_occ_filesscan(){ [ "$1" = "set" ] && echo "$2" > $tempfile || ${X[cat]} $tempfile; }
+do_occ_filesscan set _
 
-v_echo "$(pf;Y)do_occ_filesscan preset to$(N) $(do_occ_filesscan)"
+v_echo "$(pf; Y)do_occ_filesscan preset to$(N) $(do_occ_filesscan)"
 
-if [ -d "$basepath" ];then
+if [ -d "$basepath" ]; then
     # if $actualpath a directory, all files inside will be treated
     path="${basepath%/}"
-    if $recursive;then
-        $quiet||echo "$(G)check all files in$(N) \"$(B)$path$(N)\"$(G) recursively$(N)"
-        v_echo "$(pf;Y)do_occ_filesscan$(N)=$(do_occ_filesscan)"
-        find "$path" -type d|while read subpath;do
-            $quiet||echo "   $(pf;B)$subpath$(N)"
+    if $recursive; then
+        ${B[quiet]} || echo "$(G)check all files in$(N) \"$(B)$path$(N)\"$(G) recursively$(N)"
+        v_echo "$(pf; Y)do_occ_filesscan$(N)=$(do_occ_filesscan)"
+        find "$path" -type d | while read subpath; do
+            ${B[quiet]} || echo "   $(pf;B)$subpath$(N)"
             scan_dir "$subpath"
-            if [ $? -eq 0 ];then
-                v_echo "$(pf;Y)changed path:$(N) \"$(B)$subpath$(N)\""
-                v_echo "$(pf;Y)do_occ_filesscan$(N)=$(do_occ_filesscan)"
+            if [ $? -eq 0 ]; then
+                v_echo "$(pf; Y)changed path:$(N) \"$(B)$subpath$(N)\""
+                v_echo "$(pf; Y)do_occ_filesscan$(N)=$(do_occ_filesscan)"
             fi
         done
     else
-        $quiet||echo "check all files in: \"$path\""
+        ${B[quiet]} || echo "check all files in: \"$path\""
         scan_dir "$path"
     fi
 #set -x
 else
 # if $actualpath is a file, only that file will be treated.
     #exract path for occ files:scan at the end
-    path="$(${BINARIES[dirname]} "$basepath")"
+    path="$(${X[dirname]} "$basepath")"
     mimetype="$($mimedetector "$basepath")"
-    echo "${mime_ext_regex_array[@]%%:*}"|${BINARIES[grep]} -qsw "$mimetype"||error "MIME type '$mimetype' not supported"
+    echo "${mime_ext_regex_array[@]%%:*}" | ${X[grep]} -qsw "$mimetype" || error "MIME type '$mimetype' not supported"
     extension="$(a_fld mime_ext_regex_array ':' "$mimetype" 2)"
     regex="$(a_fld mime_ext_regex_array ':' "$mimetype" 3)"
     main "$basepath" "$regex" "$extension" "$mimetype"
 fi
-v_echo "$(pf;Y)do_occ_filesscan at end of script:$(N) $(do_occ_filesscan)"
+v_echo "$(pf; Y)do_occ_filesscan at end of script:$(N) $(do_occ_filesscan)"
 # if anything changed, $(occ files:scan) the affected directory
 if $(do_occ_filesscan);then
-    $recursive&&occshallow=""||occshallow=" --shallow"
+    ${B[recursive]} && occshallow="" || occshallow=" --shallow"
     occdebug=""
-    $quiet&&occdebug=" --quiet"
-    $verbose&&occdebug=" -v"
-    $debug&&occdebug=" -vvv"
+    ${B[quiet]} && occdebug=" --quiet"
+    ${B[verbose]} && occdebug=" -v"
+    ${B[debug]} && occdebug=" -vvv"
     occcommand="files:scan"
     occstring="$occcommand$occshallow$occdebug"
-    $quiet||G;echo "running$(N;f)$PWD# occ $occstring --path=\"$(B)$path$(N)\""
-    if $dryrun;then
+    ${B[quiet]} || G; echo "running$(N; f)$PWD# occ $occstring --path=\"$(B)$path$(N)\""
+    if ${B[dryrun]}; then
         echo " -$(G) option$(N) --dryrun$(G) was set, nothing changed$(N)"
     else
         occ $occstring --path="$path"
     fi
 else
-    $quiet||echo " -$(G) nothing changed$(N)"
+    ${B[quiet]} || echo " -$(G) nothing changed$(N)"
 fi
-$debug&&set +x
+${B[debug]} && set +x
 
-$quiet&&exit 0||exit0
+${B[quiet]} && exit 0 || exit0
 
