refactor: use `&&` syntax in single load logic to reduce indentation

diff --git a/modules/exit b/modules/exit
--- a/modules/exit
+++ b/modules/exit
@@ -7,51 +7,50 @@ __copyright__
 __license__
 #
 
-${EXIT_BASHLIB:-false} || {
-    EXIT_BASHLIB=:
+${EXIT_BASHLIB:-false} && return
+EXIT_BASHLIB=:
 
-    # for backwards compatibility
-    declare -f lrequire &>/dev/null||lrequire(){ require $@;}
+# for backwards compatibility
+declare -f lrequire &>/dev/null||lrequire(){ require $@;}
 
-    . <(lrequire basics)
-    . <(lrequire ansi)
+. <(lrequire basics)
+. <(lrequire ansi)
 
-    exit0(){
-        G; echo "exiting script."
-        N; echo "generous? run '$me --donate'"
-        N; exit 0
-    }
-
-    exit1(){
-        R; echo "exiting…"
-        N; exit 1
-    }
-
-    # define a trap to clean up the temporary file
-    exit_trap(){
-        [ -f "$spinner_pid_file" ] && kill_spinner
-        ${local_server:-false} && ls_ stop
-        nonullglob "$TMPDIR/${bm}$$_*" && (rm -f $TMPDIR/${bm}$$_*) 2>/dev/null
-        nonullglob "$TMPDIR/${bm:-$$}_*" && (rm -f $TMPDIR/${bm:-$$}_*) 2>/dev/null
-        ansi_reset
-    }
-
-    interrupted(){
-        if [ -z "$bm" ]; then
-            return 0
-        else
-            te1; Yi; echo "TRAP: interrupted by sig$1"
-            if [ -f "$spinner_pid_file" ]; then
-                te1; Yi; echo "TRAP: - spinner killed"
-            fi
-            if nonullglob "$TMPDIR/${bm}_*"; then
-                te1; Yi; echo "TRAP: - temporary files removed"
-            fi
-            exit1
-        fi
-    }
-
-    trap 'exit_trap' EXIT
-    trap 'interrupted INT' INT
-    trap 'interrupted TERM' TERM
+exit0(){
+    G; echo "exiting script."
+    N; echo "generous? run '$me --donate'"
+    N; exit 0
 }
+
+exit1(){
+    R; echo "exiting…"
+    N; exit 1
+}
+
+# define a trap to clean up the temporary file
+exit_trap(){
+    [ -f "$spinner_pid_file" ] && kill_spinner
+    ${local_server:-false} && ls_ stop
+    nonullglob "$TMPDIR/${bm}$$_*" && (rm -f $TMPDIR/${bm}$$_*) 2>/dev/null
+    nonullglob "$TMPDIR/${bm:-$$}_*" && (rm -f $TMPDIR/${bm:-$$}_*) 2>/dev/null
+    ansi_reset
+}
+
+interrupted(){
+    if [ -z "$bm" ]; then
+        return 0
+    else
+        te1; Yi; echo "TRAP: interrupted by sig$1"
+        if [ -f "$spinner_pid_file" ]; then
+            te1; Yi; echo "TRAP: - spinner killed"
+        fi
+        if nonullglob "$TMPDIR/${bm}_*"; then
+            te1; Yi; echo "TRAP: - temporary files removed"
+        fi
+        exit1
+    fi
+}
+
+trap 'exit_trap' EXIT
+trap 'interrupted INT' INT
+trap 'interrupted TERM' TERM
diff --git a/modules/integrity b/modules/integrity
--- a/modules/integrity
+++ b/modules/integrity
@@ -7,20 +7,20 @@ __copyright__
 __license__
 #
 
-${INTEGRITY_BASHLIB:-false} || {
-    INTEGRITY_BASHLIB=:
+${INTEGRITY_BASHLIB:-false} && return
+INTEGRITY_BASHLIB=:
 
-    # for backwards compatibility
-    declare -f lrequire &>/dev/null||lrequire(){ require $@;}
+# for backwards compatibility
+declare -f lrequire &>/dev/null||lrequire(){ require $@;}
 
-    . <(lrequire awksed)
-    . <(lrequire line)
-    . <(lrequire sudo)
-    . <(lrequire vdir)
+. <(lrequire awksed)
+. <(lrequire line)
+. <(lrequire sudo)
+. <(lrequire vdir)
 
 
-    public_key(){
-        cat << PUBLIC_KEY_ASC
+public_key(){
+    cat << PUBLIC_KEY_ASC
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 
 mQINBGSXjUIBEADbt4/706Fw6YNHMPwHT+qtq4ZxJCdUclzovEnCvECtylYCK1M5
@@ -52,92 +52,91 @@ YP2ebH/z
 =PJji
 -----END PGP PUBLIC KEY BLOCK-----
 PUBLIC_KEY_ASC
-    }
+}
 
-    integrity_check(){
-        local -i r=1
-        local signed key mail aut itf="$(tf)" vtf="$(tf)" vdir ddir shash ehash
-        signed=:
-        key="$(sed -n 's/^# OpenPGP_Key\s*\(.*\)$/\1/p' "$ca_me")"
-        mail="$(sed -n 's/^# Email\s*\(.*\)$/\1/p' "$ca_me")"
-        aut="$(sed -n 's/^# Copyright.*\[\(.*\)\]/\\[\1\\]/p' "$ca_me")"
-        su_root "to run the integrity check" integrity_check
-        delp2ei '^-----BEGIN PGP SIGNATURE-----$' "$ca_me" "$itf"
-        if [ -n "$vdirname" ]; then
-            vdir=$(eval echo \$$vdirname) ddir=$(eval echo \$dflt_$vdirname)
-            [ "$vdir" != "$ddir" ] && setvdir v d "$itf"
+integrity_check(){
+    local -i r=1
+    local signed key mail aut itf="$(tf)" vtf="$(tf)" vdir ddir shash ehash
+    signed=:
+    key="$(sed -n 's/^# OpenPGP_Key\s*\(.*\)$/\1/p' "$ca_me")"
+    mail="$(sed -n 's/^# Email\s*\(.*\)$/\1/p' "$ca_me")"
+    aut="$(sed -n 's/^# Copyright.*\[\(.*\)\]/\\[\1\\]/p' "$ca_me")"
+    su_root "to run the integrity check" integrity_check
+    delp2ei '^-----BEGIN PGP SIGNATURE-----$' "$ca_me" "$itf"
+    if [ -n "$vdirname" ]; then
+        vdir=$(eval echo \$$vdirname) ddir=$(eval echo \$dflt_$vdirname)
+        [ "$vdir" != "$ddir" ] && setvdir v d "$itf"
+    fi
+    shash="$(sha256sum "$itf" | awk '{print $1}')"
+    ehash="$(tail -n1 "$ca_me" | awk '{print $NF}')"
+    line '=' P 5/75
+    if ! [[ $ehash =~ ^[a-fA-F0-9]{64}$ ]]; then
+        . <(lrequire ask)
+        signed=false
+        o5;R;echo "- No sha256sum hash, looks like script has not been signed!"
+        line '-' P 5/75
+    elif [ "$shash" != "$ehash" ]; then
+        o5;R;echo "- Wrong hash, looks like script has been tampered with!"
+        line '-' P 5/75
+    fi
+    gpg --list-keys|grep -qs "$key"||gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys "$key" 2>/dev/null
+    gpg --list-keys|grep -qs "$key"||gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key" 2>/dev/null
+    gpg --list-keys|grep -qs "$key"||public_key|gpg --import 2>/dev/null
+    gpg --list-keys|grep -qs "$key"||{
+        . <(lrequire ask)
+        o5;R;echo "- import of public key failed."
+        qpf;ask "Continue at own risk without check?" "$NO"&&{
+            sed -i 's/^v=false$/v=true/' "$ca_me"
+            return 0
+        }
+    }
+    gpg --verify "$ca_me" "$itf">"$vtf" 2>&1
+    r=$?
+    grep "$key" "$vtf"
+    grep "$aut (codesigning) <${mail//<at>/@}>" "$vtf"
+    line '-' P 5/75
+    if (( r )); then
+        o5;R;echo -n "- Integrity check $(blinkR)failed$(R). "
+        if $signed; then
+            echo "The script may have been modified or tampered with!"
+        else
+            echo "This script does not appear to be signed!"
         fi
-        shash="$(sha256sum "$itf" | awk '{print $1}')"
-        ehash="$(tail -n1 "$ca_me" | awk '{print $NF}')"
-        line '=' P 5/75
-        if ! [[ $ehash =~ ^[a-fA-F0-9]{64}$ ]]; then
-            . <(lrequire ask)
-            signed=false
-            o5;R;echo "- No sha256sum hash, looks like script has not been signed!"
-            line '-' P 5/75
-        elif [ "$shash" != "$ehash" ]; then
-            o5;R;echo "- Wrong hash, looks like script has been tampered with!"
-            line '-' P 5/75
-        fi
-        gpg --list-keys|grep -qs "$key"||gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys "$key" 2>/dev/null
-        gpg --list-keys|grep -qs "$key"||gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key" 2>/dev/null
-        gpg --list-keys|grep -qs "$key"||public_key|gpg --import 2>/dev/null
-        gpg --list-keys|grep -qs "$key"||{
-            . <(lrequire ask)
-            o5;R;echo "- import of public key failed."
-            qpf;ask "Continue at own risk without check?" "$NO"&&{
-                sed -i 's/^v=false$/v=true/' "$ca_me"
+        line '-' P 5/75
+        o5;B;echo "You should run:"
+        o5;GRAY;echo "sudo wget -O $ca_me $my_url"
+        if $signed; then
+            o5;B;echo "to fix this.";N
+        else
+            o5;B;echo "to get a signed version of this script or disable the integrity check.";N
+            qpf;ask "Do you want to disable the integrity check at own risk" "$NO"&&{
+                echo -e "v=true\nnohash" >> "$ca_me"
                 return 0
             }
-        }
-        gpg --verify "$ca_me" "$itf">"$vtf" 2>&1
-        r=$?
-        grep "$key" "$vtf"
-        grep "$aut (codesigning) <${mail//<at>/@}>" "$vtf"
-        line '-' P 5/75
-        if (( r )); then
-            o5;R;echo -n "- Integrity check $(blinkR)failed$(R). "
-            if $signed; then
-                echo "The script may have been modified or tampered with!"
-            else
-                echo "This script does not appear to be signed!"
-            fi
-            line '-' P 5/75
-            o5;B;echo "You should run:"
-            o5;GRAY;echo "sudo wget -O $ca_me $my_url"
-            if $signed; then
-                o5;B;echo "to fix this.";N
-            else
-                o5;B;echo "to get a signed version of this script or disable the integrity check.";N
-                qpf;ask "Do you want to disable the integrity check at own risk" "$NO"&&{
-                    echo -e "v=true\nnohash" >> "$ca_me"
-                    return 0
-                }
-            fi
-        else
-            o5;lG;echo "Integrity check passed. The script is authentic.";N
-            sed -i 's/^v=false$/v=true/' "$ca_me"
         fi
-        line '=' P 5/75
-        return $r
-    }
-
-    run_integrity_check(){
-        if integrity_check; then
-            f;pf;G;echo "Integrity check passed. Please start script again"
-            exit 0
-        else
-            exit1
-        fi
-    }
-
-    if $do_integrity_check; then
-        run_integrity_check
+    else
+        o5;lG;echo "Integrity check passed. The script is authentic.";N
+        sed -i 's/^v=false$/v=true/' "$ca_me"
     fi
-    declare "$(tail -n2 "$ca_me" | head -n1)"
-    if ! "${v:-false}"; then
-        f
-        o5;B;echo "First run, checking integrity:"
-        run_integrity_check
+    line '=' P 5/75
+    return $r
+}
+
+run_integrity_check(){
+    if integrity_check; then
+        f;pf;G;echo "Integrity check passed. Please start script again"
+        exit 0
+    else
+        exit1
     fi
 }
+
+if $do_integrity_check; then
+    run_integrity_check
+fi
+declare "$(tail -n2 "$ca_me" | head -n1)"
+if ! "${v:-false}"; then
+    f
+    o5;B;echo "First run, checking integrity:"
+    run_integrity_check
+fi
diff --git a/modules/nc-apps/assumed_version b/modules/nc-apps/assumed_version
--- a/modules/nc-apps/assumed_version
+++ b/modules/nc-apps/assumed_version
@@ -7,91 +7,90 @@ __copyright__
 __license__
 #
 
-${ASSUMED_VERSION_BASHLIB:-false} || {
-    ASSUMED_VERSION_BASHLIB=:
+${ASSUMED_VERSION_BASHLIB:-false} && return
+ASSUMED_VERSION_BASHLIB=:
 
-    # for backwards compatibility
-    declare -f lrequire &>/dev/null||lrequire(){ require $@;}
+# for backwards compatibility
+declare -f lrequire &>/dev/null||lrequire(){ require $@;}
 
-    . <(lrequire $sin/db)
+. <(lrequire $sin/db)
 
 # TODO 0 -->
-    # min_version(){ $(echo $(r_db "SELECT CASE WHEN major = (SELECT MIN(major) FROM versions) THEN platform ELSE NULL END AS result FROM versions;"));}
+# min_version(){ $(echo $(r_db "SELECT CASE WHEN major = (SELECT MIN(major) FROM versions) THEN platform ELSE NULL END AS result FROM versions;"));}
 # TODO <-- 0
-    assumed_version_select(){
-        local major='' query
-        if (( $# )); then
-            major="WHERE major == ${1%%.*}"
-        fi
-        query="SELECT platform FROM versions $major ORDER BY major DESC, minor DESC;"
-        read -ra available_versions < <(r_db "$query")
-        local -i n i version_num selected_index
-        echo "Please select the $2version you want to assume:"
-        while true; do
-          # Display the numbered list of available versions
-            for i in "${!available_versions[@]}"; do
-                echo "$((n + i)). ${available_versions[$i]}"
-            done
-          # Prompt for user input
-            read -rp "Enter the number of the $2version of your choice: " version_num
-          # Validate user input
-            if ! [[ "$version_num" =~ ^[0-9]+$ ]]; then
-                echo "Invalid input. Please enter a valid number."
-                continue
-            fi
-          # Check if the chosen version number is within the valid range
-            if (( version_num < n || version_num >= (n+${#available_versions[@]}) )); then
-                echo "Invalid $2version number. Please choose a number from the list."
-                continue
-            fi
-          # Get the selected backup directory
-            selected_index=$((version_num - n))
-            if [ "$2" = "min_" ]; then
-                nc_min_version="${available_versions[$selected_index]}"
-            else
-                nc_version="${available_versions[$selected_index]}"
-            fi
-            eval echo \"Your choice: \$nc_$2version\"
-            echo "Do you want to assume this as $2version?"
-            anykey
-          # Exit the loop if a valid input is provided
-            break
+assumed_version_select(){
+    local major='' query
+    if (( $# )); then
+        major="WHERE major == ${1%%.*}"
+    fi
+    query="SELECT platform FROM versions $major ORDER BY major DESC, minor DESC;"
+    read -ra available_versions < <(r_db "$query")
+    local -i n i version_num selected_index
+    echo "Please select the $2version you want to assume:"
+    while true; do
+      # Display the numbered list of available versions
+        for i in "${!available_versions[@]}"; do
+            echo "$((n + i)). ${available_versions[$i]}"
         done
-        return 0
-    }
-
-    assumed_version_set(){
-        local cquery query nc_lowest
-        nc_lowest="${LATEST_EOL[0]}"
-        $database_created || create_database
-        if [[ ! ${1%%.*} =~ ^[0-9]+$ ]]; then
-            assumed_version_select
-        elif [ 0${1%%.*} -lt 0${nc_lowest%%.*} ]; then
-            o2;echo "the min version supported by this script is $nc_lowest"
-            if [ "$2" = "min_" ]; then
-                nc_min_version="$nc_lowest"
-            else
-                nc_version="$nc_lowest"
-            fi
-        else
-            cquery="SELECT COUNT(platform) FROM versions WHERE major == ${1%%.*};"
-            query="SELECT platform FROM versions WHERE major == ${1%%.*};"
-            case $(r_db "$cquery") in
-                0)  if [ "$2" = "min_" ]; then
-                        nc_min_version=${1%%.*}.0.0
-                    else
-                        nc_version=${1%%.*}.0.0
-                    fi
-                    ;;
-                1)  if [ "$2" = "min_" ]; then
-                        nc_min_version=$(r_db "$query")
-                    else
-                        nc_version=$(r_db "$query")
-                    fi
-                    ;;
-                *)  assumed_version_select ${1%%.*} $2
-            esac
+      # Prompt for user input
+        read -rp "Enter the number of the $2version of your choice: " version_num
+      # Validate user input
+        if ! [[ "$version_num" =~ ^[0-9]+$ ]]; then
+            echo "Invalid input. Please enter a valid number."
+            continue
         fi
-        return 0
-    }
+      # Check if the chosen version number is within the valid range
+        if (( version_num < n || version_num >= (n+${#available_versions[@]}) )); then
+            echo "Invalid $2version number. Please choose a number from the list."
+            continue
+        fi
+      # Get the selected backup directory
+        selected_index=$((version_num - n))
+        if [ "$2" = "min_" ]; then
+            nc_min_version="${available_versions[$selected_index]}"
+        else
+            nc_version="${available_versions[$selected_index]}"
+        fi
+        eval echo \"Your choice: \$nc_$2version\"
+        echo "Do you want to assume this as $2version?"
+        anykey
+      # Exit the loop if a valid input is provided
+        break
+    done
+    return 0
+}
+
+assumed_version_set(){
+    local cquery query nc_lowest
+    nc_lowest="${LATEST_EOL[0]}"
+    $database_created || create_database
+    if [[ ! ${1%%.*} =~ ^[0-9]+$ ]]; then
+        assumed_version_select
+    elif [ 0${1%%.*} -lt 0${nc_lowest%%.*} ]; then
+        o2;echo "the min version supported by this script is $nc_lowest"
+        if [ "$2" = "min_" ]; then
+            nc_min_version="$nc_lowest"
+        else
+            nc_version="$nc_lowest"
+        fi
+    else
+        cquery="SELECT COUNT(platform) FROM versions WHERE major == ${1%%.*};"
+        query="SELECT platform FROM versions WHERE major == ${1%%.*};"
+        case $(r_db "$cquery") in
+            0)  if [ "$2" = "min_" ]; then
+                    nc_min_version=${1%%.*}.0.0
+                else
+                    nc_version=${1%%.*}.0.0
+                fi
+                ;;
+            1)  if [ "$2" = "min_" ]; then
+                    nc_min_version=$(r_db "$query")
+                else
+                    nc_version=$(r_db "$query")
+                fi
+                ;;
+            *)  assumed_version_select ${1%%.*} $2
+        esac
+    fi
+    return 0
 }
diff --git a/modules/nc/first_run b/modules/nc/first_run
--- a/modules/nc/first_run
+++ b/modules/nc/first_run
@@ -7,120 +7,118 @@ __copyright__
 __license__
 #
 
-${FIRST_RUN_BASHLIB:-false} || {
-    FIRST_RUN_BASHLIB=:
+${FIRST_RUN_BASHLIB:-false} && return
+FIRST_RUN_BASHLIB=:
 
-    . <(lrequire sudo)
-    . <(lrequire button)
-    . <(lrequire anykey)
-    . <(lrequire vdir)
-    . <(lrequire httpd)
-    . <(lrequire ask)
+. <(lrequire sudo)
+. <(lrequire button)
+. <(lrequire anykey)
+. <(lrequire vdir)
+. <(lrequire httpd)
+. <(lrequire ask)
 
-    first_run(){
-        te1
+first_run(){
+    te1
 
-        complete(){
-            mh "vdir: $1" &
-            setvdir v "$1"
-            f
-            o2; echo "- $(lG)first run wizard completed successfully."; N
-            f
-            $me "json=$my_json" $my_args
-            exit 0
-        }
-
-        local p h
-        local -l ans num
-        local -i c2=9 i n=1
-        h="$(box h) to enter path by hand or $(q2q)"
-        if (( $(id -u) )) && [ -d "$NC_DIR" ]; then
-            su_root "to run this script"
-        fi
-        if ! $irun2; then
-            f
-            o2; GRAY; echo "This step is required once after a new installation or sometimes after an update:"; N
-        fi
-        su_root "for the first run wizard" irun2
-        populate_httpd_ nc-dir
+    complete(){
+        mh "vdir: $1" &
+        setvdir v "$1"
         f
-        o2; B; echo "Hello, this is the first run wizard of \"$(Y)$me$(B)\""
-        if (( ${#HTTPD_NC_DIR[@]} == 1 )); then
-            p="${HTTPD_NC_DIR[0]}"
-            o2; echo "nextcloud installation detected in $(C)$p"; N
-            o2; printf "is that correct $(box Y) / $(box n) ($(GRAY)or $(q2q; N)) "
-            while :; do
-                read -rsn 1 ans; te1
-                case ${ans:-y} in
-                    q)  exit 0
-                        ;;
-                    y)  complete "$p"
-                        ;;
-                    n)  break
-                        ;;
-                    *)  printf "$invi Please enter $(box y), $(box n) or $(q2q) "
-                esac
-            done
-        elif (( ${#HTTPD_NC_DIR[@]} > 1 )); then
-            line '=' P 2/78 b1
-            o3; B; echo "Detected nextcloud installations"
-            o4; Y; echo "Num$(o $c2)Directory"
-            line '-' P 2/78
-            for i in "${!HTTPD_NC_DIR[@]}"; do
-                p="${HTTPD_NC_DIR[i]}"
-                o3; echo "- $((n+i))$(o $c2)$p"
-            done
-            line '-' P 2/78 a2
-            o2; printf "Enter the corresponding number, $h"
-            while :; do
-                read -rsn 1 num
-                te1
-                case $num in
-                    q)  exit 0
-                        ;;
-                    h)  break
-                        ;;
-                [1-9])  (( num < n || num >= (n+${#HTTPD_NC_DIR[@]}) )) && {
-                            printf "$(o2)Invalid number. Please choose a number from the list, $h"
-                            continue
-                        }
-                        i="$((num-n))"
-                        p="${HTTPD_NC_DIR[i]}"
-                        o2; echo "Your choice: \"$(C)$p$(N)\""
-                        f
-                        o2; echo "is this the right Nextcloud installation path?"
-                        o2; echo "Press $(box y) for yes, $(box n) for no, $(box h) enter path by hand or $(q2q): "
-                        while :; do
-                            read -rsn 1 ans
-                            te1
-                            case $ans in
-                                q)  exit 0
-                                    ;;
-                                h)  break
-                                    ;;
-                                n)  continue
-                                    ;;
-                                y)  complete "$p"
-                                    ;;
-                                *)  printf "$invi Please enter $(box y), $(box n), $(box h) or $(q2q) "
-                            esac
-                        done
-                        ;;
-                    *)  o2
-                        printf "$invi Please enter a valid number, $h"
-                        continue
-                esac
-            done
-        fi
-        while :; do
-            o2; echo "enter the directory where your Nextcloud is installed ($(C)or $(q2q; N)):"; N
-            read -rp "  --> " p
-            te1
-            [ "${p,}" = "q" ] && exit 0
-            [ -f "$p/occ" ] && complete "$p" || echo "$(Pbg)  * I can not detect a Nextcloud installation in \"$p\" $(N)"
-        done
+        o2; echo "- $(lG)first run wizard completed successfully."; N
+        f
+        $me "json=$my_json" $my_args
+        exit 0
     }
-# TODO 0 -->
-#    [ -r "$NC_DIR/lib/base.php" ] || first_run
-# TODO <-- 0
+
+    local p h
+    local -l ans num
+    local -i c2=9 i n=1
+    h="$(box h) to enter path by hand or $(q2q)"
+    if (( $(id -u) )) && [ -d "$NC_DIR" ]; then
+        su_root "to run this script"
+    fi
+    if ! $irun2; then
+        f
+        o2; GRAY; echo "This step is required once after a new installation or sometimes after an update:"; N
+    fi
+    su_root "for the first run wizard" irun2
+    populate_httpd_ nc-dir
+    f
+    o2; B; echo "Hello, this is the first run wizard of \"$(Y)$me$(B)\""
+    if (( ${#HTTPD_NC_DIR[@]} == 1 )); then
+        p="${HTTPD_NC_DIR[0]}"
+        o2; echo "nextcloud installation detected in $(C)$p"; N
+        o2; printf "is that correct $(box Y) / $(box n) ($(GRAY)or $(q2q; N)) "
+        while :; do
+            read -rsn 1 ans; te1
+            case ${ans:-y} in
+                q)  exit 0
+                    ;;
+                y)  complete "$p"
+                    ;;
+                n)  break
+                    ;;
+                *)  printf "$invi Please enter $(box y), $(box n) or $(q2q) "
+            esac
+        done
+    elif (( ${#HTTPD_NC_DIR[@]} > 1 )); then
+        line '=' P 2/78 b1
+        o3; B; echo "Detected nextcloud installations"
+        o4; Y; echo "Num$(o $c2)Directory"
+        line '-' P 2/78
+        for i in "${!HTTPD_NC_DIR[@]}"; do
+            p="${HTTPD_NC_DIR[i]}"
+            o3; echo "- $((n+i))$(o $c2)$p"
+        done
+        line '-' P 2/78 a2
+        o2; printf "Enter the corresponding number, $h"
+        while :; do
+            read -rsn 1 num
+            te1
+            case $num in
+                q)  exit 0
+                    ;;
+                h)  break
+                    ;;
+            [1-9])  (( num < n || num >= (n+${#HTTPD_NC_DIR[@]}) )) && {
+                        printf "$(o2)Invalid number. Please choose a number from the list, $h"
+                        continue
+                    }
+                    i="$((num-n))"
+                    p="${HTTPD_NC_DIR[i]}"
+                    o2; echo "Your choice: \"$(C)$p$(N)\""
+                    f
+                    o2; echo "is this the right Nextcloud installation path?"
+                    o2; echo "Press $(box y) for yes, $(box n) for no, $(box h) enter path by hand or $(q2q): "
+                    while :; do
+                        read -rsn 1 ans
+                        te1
+                        case $ans in
+                            q)  exit 0
+                                ;;
+                            h)  break
+                                ;;
+                            n)  continue
+                                ;;
+                            y)  complete "$p"
+                                ;;
+                            *)  printf "$invi Please enter $(box y), $(box n), $(box h) or $(q2q) "
+                        esac
+                    done
+                    ;;
+                *)  o2
+                    printf "$invi Please enter a valid number, $h"
+                    continue
+            esac
+        done
+    fi
+    while :; do
+        o2; echo "enter the directory where your Nextcloud is installed ($(C)or $(q2q; N)):"; N
+        read -rp "  --> " p
+        te1
+        [ "${p,}" = "q" ] && exit 0
+        [ -f "$p/occ" ] && complete "$p" || echo "$(Pbg)  * I can not detect a Nextcloud installation in \"$p\" $(N)"
+    done
 }
+# COMMENT -->
+#    [ -r "$NC_DIR/lib/base.php" ] || first_run
diff --git a/modules/nc/nextcloud_aio b/modules/nc/nextcloud_aio
--- a/modules/nc/nextcloud_aio
+++ b/modules/nc/nextcloud_aio
@@ -7,55 +7,54 @@ __copyright__
 __license__
 #
 
-${NEXTCLOUD_AIO_BASHLIB:-false} || {
-    NEXTCLOUD_AIO_BASHLIB=:
+${NEXTCLOUD_AIO_BASHLIB:-false} && return
+NEXTCLOUD_AIO_BASHLIB=:
 
-    # for backwards compatibility
-    declare -f lrequire &>/dev/null||lrequire(){ require $@;}
+# for backwards compatibility
+declare -f lrequire &>/dev/null||lrequire(){ require $@;}
 
-    . <(lrequire sudo)
+. <(lrequire sudo)
 
-    declare AIO DOCKER
-    AIO=false DOCKER=false
+declare AIO DOCKER
+AIO=false DOCKER=false
 
-    detect_aio(){
-        docker_ps_json="$(tf)"
-        # detect if any docker containers are running on the host (without -a, because only running containers matter here)
-        docker ps --no-trunc --format=json 2>/dev/null > $docker_ps_json
-        mapfile -t docker_names< <(jq -r .Names $docker_ps_json)
-        if (( ${#docker_names[@]} )); then
-            if [[ "${docker_names[@]}" =~ nextcloud-aio-mastercontainer && "${docker_names[@]}" =~ nextcloud-aio-nextcloud ]]; then
-                AIO=true
-                DOCKER=true
-            fi
+detect_aio(){
+    docker_ps_json="$(tf)"
+    # detect if any docker containers are running on the host (without -a, because only running containers matter here)
+    docker ps --no-trunc --format=json 2>/dev/null > $docker_ps_json
+    mapfile -t docker_names< <(jq -r .Names $docker_ps_json)
+    if (( ${#docker_names[@]} )); then
+        if [[ "${docker_names[@]}" =~ nextcloud-aio-mastercontainer && "${docker_names[@]}" =~ nextcloud-aio-nextcloud ]]; then
+            AIO=true
+            DOCKER=true
         fi
-    }
-
-    aio_wrapper(){
-        local interactive_tty container_name
-        if [ "$1" = '-it' ]; then
-            interactive_tty='-it'
-            shift
-        else
-            interactive_tty=''
-        fi
-        container_name="$1"
-        shift
-        sudo docker exec $interactive_tty "nextcloud-aio-$container_name" bash -c "$*"
-    }
-
-    aio_not_supported(){
-        $AIO || return 0
-        f;pf;R;echo "This script cannot be used with Nextcloud All-in-One …"
-        exit1
-    }
-
-    if (( $(id -u) )); then # you are not root
-        if ps aux | grep -qs "[d]ockerd"; then # dockerd is running
-            su_root "to detect all-in-one"
-        fi
-    else
-        detect_aio
     fi
 }
+
+aio_wrapper(){
+    local interactive_tty container_name
+    if [ "$1" = '-it' ]; then
+        interactive_tty='-it'
+        shift
+    else
+        interactive_tty=''
+    fi
+    container_name="$1"
+    shift
+    sudo docker exec $interactive_tty "nextcloud-aio-$container_name" bash -c "$*"
+}
+
+aio_not_supported(){
+    $AIO || return 0
+    f;pf;R;echo "This script cannot be used with Nextcloud All-in-One …"
+    exit1
+}
+
+if (( $(id -u) )); then # you are not root
+    if ps aux | grep -qs "[d]ockerd"; then # dockerd is running
+        su_root "to detect all-in-one"
+    fi
+else
+    detect_aio
+fi
 
diff --git a/modules/verbose b/modules/verbose
--- a/modules/verbose
+++ b/modules/verbose
@@ -7,36 +7,35 @@ __copyright__
 __license__
 #
 
-${VERBOSE_BASHLIB:-false} || {
-    VERBOSE_BASHLIB=:
+${VERBOSE_BASHLIB:-false} && return
+VERBOSE_BASHLIB=:
 
-    # for backwards compatibility
-    declare -f lrequire &>/dev/null||lrequire(){ require $@;}
+# for backwards compatibility
+declare -f lrequire &>/dev/null||lrequire(){ require $@;}
 
-    . <(lrequire button)
-    . <(lrequire exit)
-    . <(lrequire anykey)
+. <(lrequire button)
+. <(lrequire exit)
+. <(lrequire anykey)
 
-    # error handling
-    error(){
-        if ! ${quiet:-false}; then
-            R; echo "ERROR: $*$(N)" >&2
-            exit1
-        fi
-    }
+# error handling
+error(){
+    if ! ${quiet:-false}; then
+        R; echo "ERROR: $*$(N)" >&2
+        exit1
+    fi
+}
 
-    # verbose-echo
-    v_echo(){
-        if ${verbose:-false}; then
-            R; echo "VERBOSE:$(N) $*"
-        fi
-    }
+# verbose-echo
+v_echo(){
+    if ${verbose:-false}; then
+        R; echo "VERBOSE:$(N) $*"
+    fi
+}
 
-    # verbose-echo
-    d_echo(){
-        if ${debug:-false}; then
-            R; echo "DEBUG:$(N) $*"
-            anykey
-        fi
-    }
+# verbose-echo
+d_echo(){
+    if ${debug:-false}; then
+        R; echo "DEBUG:$(N) $*"
+        anykey
+    fi
 }
