added ability to disable check

diff --git a/modules/integrity b/modules/integrity
--- a/modules/integrity
+++ b/modules/integrity
@@ -57,7 +57,8 @@ PUBLIC_KEY_ASC
 
     integrity_check(){
         local -i r=1
-        local key mail aut itf="$(tf)" vtf="$(tf)" vdir ddir shash ehash
+        local signed key mail aut itf="$(tf)" vtf="$(tf)" vdir ddir shash ehash
+        signed=:
         key="$(sed -n 's/^# OpenPGP_Key\s*\(.*\)$/\1/p' "$ca_me")"
         mail="$(sed -n 's/^# Email\s*\(.*\)$/\1/p' "$ca_me")"
         aut="$(sed -n 's/^# Copyright.*\[\(.*\)\]/\\[\1\\]/p' "$ca_me")"
@@ -70,7 +71,12 @@ PUBLIC_KEY_ASC
         shash="$(sha256sum "$itf" | awk '{print $1}')"
         ehash="$(tail -n1 "$ca_me" | awk '{print $NF}')"
         line '=' P 5/75
-        if [ "$shash" != "$ehash" ]; then
+        if ! [[ $ehash =~ ^[a-fA-F0-9]{64}$ ]]; then
+            . <(require ask)
+            signed=false
+            o5;R;echo "- No sha256sum hash, looks like script has not been signed!"
+            line '-' P 5/75
+        elif [ "$shash" != "$ehash" ]; then
             o5;R;echo "- Wrong hash, looks like script has been tampered with!"
             line '-' P 5/75
         fi
@@ -78,6 +84,7 @@ PUBLIC_KEY_ASC
         gpg --list-keys|grep -qs "$key"||gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key" 2>/dev/null
         gpg --list-keys|grep -qs "$key"||public_key|gpg --import 2>/dev/null
         gpg --list-keys|grep -qs "$key"||{
+            . <(require ask)
             o5;R;echo "- import of public key failed."
             qpf;ask "Continue at own risk without check?" $NO&&{
                 sed -i 's/^v=false$/v=true/' "$ca_me"
@@ -90,11 +97,24 @@ PUBLIC_KEY_ASC
         grep "$aut (codesigning) <${mail//<at>/@}>" "$vtf"
         line '-' P 5/75
         if (( r )); then
-            o5;R;echo "- Integrity check $(blinkR)failed$(R). The script may have been modified or tampered with!"
+            o5;R;echo -n "- Integrity check $(blinkR)failed$(R). "
+            if $signed; then
+                echo "The script may have been modified or tampered with!"
+            else
+                echo "This script does not appear to be signed!"
+            fi
             line '-' P 5/75
             o5;B;echo "You should run:"
             o5;GRAY;echo "sudo wget -O $ca_me $my_url"
-            o5;B;echo "to fix this.";N
+            if $signed; then
+                o5;B;echo "to fix this.";N
+            else
+                o5;B;echo "to get a signed version of this script or disable the integrity check.";N
+                qpf;ask "Do you want to disable the integrity check at own risk?" $NO&&{
+                    echo -e "v=true\nnohash" >> "$ca_me"
+                    return 0
+                }
+            fi
         else
             o5;lG;echo "Integrity check passed. The script is authentic.";N
             sed -i 's/^v=false$/v=true/' "$ca_me"
@@ -111,7 +131,7 @@ PUBLIC_KEY_ASC
         fi
     fi
     declare "$(tail -n2 "$ca_me" | head -n1)"
-    if ! $v; then
+    if ! "${v:-false}"; then
         f
         o5;B;echo "First run, checking integrity:"
         if integrity_check; then
