bulk commit week 19-20 2025

diff --git a/modules/integrity b/modules/integrity
--- a/modules/integrity
+++ b/modules/integrity
@@ -26,33 +26,31 @@ INTEGRITY_BASHLIB=:
 : ${D[vts]:=${D[vt]}/scripts}
 
 convene(){
+    [[ "$(declare -p D)" == 'declare -A D=('* ]] || return 0
     local script link
-    ${C[ms]} ${D[vts]}
-    # return if ${D[vts]} already is equal to the cannonical dir of runing script or if one of the commands is not yet in X array:
-    [[ ${D[vts]} == $MD || -z ${X[cmp]} || -z ${X[ln]} ]] && return 0
+    ${X[mkdir]} -pm 1777 "${D[vts]}" &> >(log_trace)
+    # return if ${D[vts]} is not a directory or if ${D[vts]} already is equal to the cannonical dir of runing script or if one of the commands is not yet in X array:
+    [[ ! -d ${D[vts]} || ${D[vts]} == $MD || -z ${X[cmp]} || -z ${X[ln]} ]] && return 0
     # copy from old to new path, remove old path and replace it with a symlink pointing to new path:
-    ${X[cp]} --preserve=all "$MP" "${D[vts]}/${M[n]}" &&
-        ${X[cmp]} -s "$MP" "${D[vts]}/${M[n]}" &&
-        ${X[rm]} -f -- "$MP" &&
-        mh "$(funcname_and_lineno) moved $MP to ${D[vts]}/${M[n]}"
+    ${X[cp]} --preserve=all "$MP" "${D[vts]}/${M[n]}" &> >(log_trace) &&
+        ${X[cmp]} -s "$MP" "${D[vts]}/${M[n]}" &> >(log_trace) &&
+        ${X[rm]} -f -- "$MP" &> >(log_trace) &&
+        mh "$(fn_ln) moved $MP to ${D[vts]}/${M[n]}"
     [[ ${M[b]} != ${M[n]} ]] &&
-        ${X[ln]} -sfT "${D[vts]}/${M[n]}" "$MP" &&
-        mh "$(funcname_and_lineno) created symlink: $MP -> ${D[vts]}/${M[n]}"
+        ${X[ln]} -sfT "${D[vts]}/${M[n]}" "$MP" &> >(log_trace) &&
+        mh "$(fn_ln) created symlink: $MP -> ${D[vts]}/${M[n]}"
     for script in "${D[vts]}"/*; do
         [[ -x "$script" && -f "$script" ]] || continue
         link="${D[ulb]}/$(${X[basename]} "$script")"
         if [[ ! -L "$link" || "$(${X[realpath]} "$link")" != "$script" ]]; then
-            ${X[ln]} -sfT "$script" "$link"
-            mh "$(funcname_and_lineno) created symlink: $link -> $script"
+            ${X[ln]} -sfT "$script" "$link" &> >(log_trace) &&
+            mh "$(fn_ln) created symlink: $link -> $script"
         fi
     done
-    if [ "$(${X[realpath]} "$MP")" = "${D[vts]}/${M[n]}" ]; then
-        return 0
-    else
-        something_went_wrong "simlink creation with “${X[ln]} -sfT ${D[vts]}/${M[n]} $MP” failed"
-#        mh "$(funcname_and_lineno) simlink creation failed"
-        return 1
+    if ! [[ $(${X[realpath]} "$MP") = ${D[vts]}/${M[n]} ]]; then
+        log_trace "'${X[ln]} -sfT ${D[vts]}/${M[n]} $MP' failed. 'realpath $MP' = $(${X[realpath]} "$MP")"
     fi
+    return 0
 }
 
 integrity_check(){
@@ -73,12 +71,12 @@ integrity_check(){
     ehash="$(${X[tail]} -n1 "$MP" | ${X[gawk]} '{print $NF}')"
     line '=' P 5/a
     if ! [[ $ehash =~ ^[a-fA-F0-9]{64}$ ]]; then
-        mh "$(funcname_and_lineno) no sha256sum hash!"
+        mh "$(fn_ln) no sha256sum hash!"
         bool[signed]=_
         o5; R; echo "- No sha256sum hash, looks like script has not been signed!"
         line '-' P 5/a
     elif [ "$shash" != "$ehash" ]; then
-        mh "$(funcname_and_lineno) wrong sha256sum hash!"
+        mh "$(fn_ln) wrong sha256sum hash!"
         o5; R; echo "- Wrong hash, looks like script has been tampered with!"
         line '-' P 5/a
     fi
@@ -86,7 +84,7 @@ integrity_check(){
     ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 ${X[gpg]} --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key"
     ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 gpg_assemble_key_ import ernolf_pubkey
     ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || {
-        mh "$(funcname_and_lineno) import of public key failed"
+        mh "$(fn_ln) import of public key failed"
         o5; R; echo "- import of public key failed."
         qpf; ask "Continue at own risk without check?" "$NO" && {
             sed_ 's/^v=false$/v=true/' "$MP" '-i' # this step must be done before convene, to not write back over the created symlink
@@ -107,10 +105,10 @@ integrity_check(){
     if (( r )); then
         o5; R; echo -n "- Integrity check of ${M[n]} $(blinkR)failed$(R). "
         if ${bool[signed]}; then
-            mh "$(funcname_and_lineno) failed! modified"
+            mh "$(fn_ln) failed! modified"
             echo "The script may have been modified or tampered with!"
         else
-            mh "$(funcname_and_lineno) failed! not signed"
+            mh "$(fn_ln) failed! not signed"
             echo "This script does not appear to be signed!"
         fi
         line '-' P 5/a
@@ -136,7 +134,7 @@ integrity_check(){
         convene
         ebtb_is_installed janitor || { ebtb_install_script janitor && o5; Y; echo "The 'janitor' script provides system information. Simply run 'janitor'"; }
         cleanup_dangling_links ${D[ulb]}
-        mh "$(funcname_and_lineno) passed"
+        mh "$(fn_ln) passed"
         ${X[sleep]} .1
         o5; lG; echo "Integrity check of ${M[n]} passed. The script is authentic."; N
     fi
@@ -146,7 +144,7 @@ integrity_check(){
 }
 
 run_integrity_check(){
-    mh "$(funcname_and_lineno) checking integrity"
+    mh "$(fn_ln) checking integrity"
     if integrity_check; then
         f
         o5; G; echo "Integrity check of ${M[n]} passed. Please start script again"
@@ -162,7 +160,7 @@ fi
 
 declare $(tnh1 2)
 if ! "${v:-_}"; then
-    mh "$(funcname_and_lineno) first run"
+    mh "$(fn_ln) first run"
     f
     o5; B; echo "First run of ${M[n]}, checking integrity:"
     run_integrity_check
