feat(gpg): introducing new gpg library

diff --git a/modules/integrity b/modules/integrity
--- a/modules/integrity
+++ b/modules/integrity
@@ -18,7 +18,9 @@ INTEGRITY_BASHLIB=:
 . <(lrequire sudo)
 . <(lrequire vdir)
 # TODO <-- 0
+. <(lrequire gpg)
 . <(lrequire cleanup)
+. <(lrequire ebtb)
 
 : ${D[ulb]:=/usr/local/bin}
 : ${D[vts]:=${D[vt]}/scripts}
@@ -53,41 +55,6 @@ convene(){
     fi
 }
 
-public_key(){
-    ${X[cat]} << PUBLIC_KEY_ASC
------BEGIN PGP PUBLIC KEY BLOCK-----
-
-mQINBGSXjUIBEADbt4/706Fw6YNHMPwHT+qtq4ZxJCdUclzovEnCvECtylYCK1M5
-TNpM4CQH9eNVhpyav8Wfi0aZZFwoTX+z7+xCfYcPAGZ1N7rBBIYDxwu59S65zWz6
-04Lm/P0E3FQ9RM80x8HelA9QYA+Y2hBvPjySrK2w2dQRm+L3K114Phg2j2UQKxxh
-2mwEOg/FP35YIMJYiS2QIsOKvfVi7df6UqOMy0aSsgD38NwV+aok9Of3cvKqKsBr
-mQseIFewLd9W7qjGvtHFZfncPDak49zdnOLBNGutj2McknVevAK9AznQ+q3hqBbo
-8tJT8O8XfjSeqf1dYj31H0Q5jY54kJN9NyP57MGLDtfEmKcwEwEYVkY/xt1Uq64K
-9Dj+WxJAczWs/6jZN9bou32/2StIF/wvkvw2GxF8H6kWue1zD9sa7A/xv9WHLy8M
-tHjz9Klcjz2OcsGL6JXk0ro6ySsE7EjTm3LyGdBQsRqe/JHjvmUgUREJxuXW7B3e
-NVdz/OyHX0P2+6hmcsy9CVdxocI6ntUo0/KdoSxdWSIn4k50ywHiqsVYo4QwDzR+
-4yBtcZz+Lp8C9Fs1GWMJ5FlGGfOlLhl3Z7lPO/7j5Tlys/6ZzREBByMNX2lNX6QY
-SN8P+vGbjvGiNEp7ATtkkMv9Zc6KfZtaGv6FUutBziLlCPvMxXCPaL8lBQARAQAB
-tE1bZXJub2xmXSBSYXBoYWVsIEdyYWRlbndpdHogKGNvZGVzaWduaW5nKSA8cmFw
-aGFlbC5ncmFkZW53aXR6QGdvb2dsZW1haWwuY29tPokCVAQTAQoAPhYhBD7kOoTS
-umNalOEDOwsUUTmhcHFcBQJkl41CAhsDBQkFo5qABQsJCAcCBhUKCQgLAgQWAgMB
-Ah4BAheAAAoJEAsUUTmhcHFcjfUP/igMNwF8jd97Uslvz4U/2msaUdEEKinOzejZ
-LN6PrZOcsjGijAs+4UfepPxTShqW3gBIhUNK3Ox4D8WBs36l1H86fbHnXAOHyS7S
-qPOaqpUsSMW3cxt17k7FtXMCROvQWXfOu/vIJ2Nfz8yXyyGxoDLxwRLy3sVsf634
-+D2F4Dg4rNs6S44yjPWIWmabXDAgqrD7pCRSw+H3tIXCf8fAgx619DioCv8HDKAZ
-tC0FzOA9rB9OGrXG2DZAOlocIxAvzuEOr3zN33i41j7Vk1Nsbd1mMkJJmSy6AdqD
-RKwLBI/iC8aK4BHBI7O8xXQNT/9BcrSUux1Q751cS61utQVqBVtGFkewRsNvWptP
-qBhNWRftkbev14K0hTGNGC9dK/qKxk+Bkl2GmmYbNnrdFtt0uSZZxAnd/5B4u8X4
-DyUzoCq5SrGJ5LCoGjlUd5TmPUGCZR8gBl+S27URWXSf8ULmBAILcQudm0Eg+l6m
-wt/fw/zM12qd2q8K9JutMw5wDZAYsXen5qb6LljA0F9mhVvrEsrf1ll2X9XbZvXe
-wMVBD9xFEjIAVYCph4A1mkunkyBHVF4CwICxxehecRGrT73xyTVa0+7XDM9C+xWn
-Le6J7RWkwvTfGz3AByNLB1OY3fcpO3z0NNAW/S5fVFFoOHyxityOhDruMCU42Qr4
-YP2ebH/z
-=PJji
------END PGP PUBLIC KEY BLOCK-----
-PUBLIC_KEY_ASC
-}
-
 integrity_check(){
     local key mail aut vdir ddir shash ehash
     local -i r
@@ -117,13 +84,14 @@ integrity_check(){
     fi
     ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 ${X[gpg]} --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys "$key"
     ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 ${X[gpg]} --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$key"
-    ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 public_key|${X[gpg]} --import
+    ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || q2 gpg_assemble_key_ import ernolf_pubkey
     ${X[gpg]} --list-keys | ${X[grep]} -qs "$key" || {
         mh "$(funcname_and_lineno) import of public key failed"
         o5; R; echo "- import of public key failed."
         qpf; ask "Continue at own risk without check?" "$NO" && {
             ${X[sed]} -i 's/^v=false$/v=true/' "$MP" # this step must be done before convene, to not write back over the created symlink
             convene
+            ebtb_is_installed janitor || { ebtb_install_script janitor && o5; Y; echo "The 'janitor' script provides system information. Simply run 'janitor'"; }
             cleanup_dangling_links ${D[ulb]}
             ${X[sleep]} .1
             line '=' P 5/a
@@ -137,7 +105,7 @@ integrity_check(){
     ${X[grep]} "$aut (codesigning) <${mail//<at>/@}>" "${tf[v]}"
     line '-' P 5/a
     if (( r )); then
-        o5; R; echo -n "- Integrity check $(blinkR)failed$(R). "
+        o5; R; echo -n "- Integrity check of ${M[n]} $(blinkR)failed$(R). "
         if ${bool[signed]}; then
             mh "$(funcname_and_lineno) failed! modified"
             echo "The script may have been modified or tampered with!"
@@ -155,6 +123,7 @@ integrity_check(){
             qpf; ask "Do you want to disable the integrity check at own risk" "$NO" && {
                 echo -e "v=true\nnohash" >> "$MP" # this step must be done before convene, to not write back over the created symlink
                 convene
+                ebtb_is_installed janitor || { ebtb_install_script janitor && o5; Y; echo "The 'janitor' script provides system information. Simply run 'janitor'"; }
                 cleanup_dangling_links ${D[ulb]}
                 ${X[sleep]} .1
                 line '=' P 5/a
@@ -165,10 +134,11 @@ integrity_check(){
     else
         ${X[sed]} -i 's/^v=false$/v=true/' "$MP" # this step must be done before convene, to not write back over the created symlink
         convene
+        ebtb_is_installed janitor || { ebtb_install_script janitor && o5; Y; echo "The 'janitor' script provides system information. Simply run 'janitor'"; }
         cleanup_dangling_links ${D[ulb]}
         mh "$(funcname_and_lineno) passed"
         ${X[sleep]} .1
-        o5; lG; echo "Integrity check passed. The script is authentic."; N
+        o5; lG; echo "Integrity check of ${M[n]} passed. The script is authentic."; N
     fi
     line '=' P 5/a
     cleanup "${tf[i]}" "${tf[v]}"
@@ -179,7 +149,7 @@ run_integrity_check(){
     mh "$(funcname_and_lineno) checking integrity"
     if integrity_check; then
         f
-        pf; G; echo "Integrity check passed. Please start script again"
+        o5; G; echo "Integrity check of ${M[n]} passed. Please start script again"
         exit 0
     else
         exit1
@@ -194,6 +164,6 @@ declare $(tnh1 2)
 if ! "${v:-_}"; then
     mh "$(funcname_and_lineno) first run"
     f
-    o5; B; echo "First run, checking integrity:"
+    o5; B; echo "First run of ${M[n]}, checking integrity:"
     run_integrity_check
 fi
