refactor: bulk commit week 12 2025

diff --git a/blocks/general b/blocks/general
--- a/blocks/general
+++ b/blocks/general
@@ -1,46 +1,47 @@
 # general
 q0(){
-    "$@" &>/dev/null
+    "$@" &>$NUL
 }
 q1(){
-    "$@" >/dev/null
+    "$@" >$NUL
 }
 q2(){
-    "$@" 2>/dev/null
+    "$@" 2>$NUL
 }
 mkld(){
-    [ -d "${D[l]:=/run/lock/${I[u]}/ebtb}" ] || ${C[md]} -p "${D[l]}"
-    [ -d "${D[l]}" ] || { D[l]=$TD/ebtb/lock; ${C[md]} -p "${D[l]}"; }
+    ${C[md]} ${D[l]:=${D[lu]}/${I[u]}/${M[p]}}
+    [[ -d ${D[l]} ]] || { D[l]=${D[tu]}/lock; mkld; }
+}
+chrf(){
+    ${C[fi]} $1 -type d -exec ${C[cm]} 777 {} +
+    ${C[fi]} $1 -type f -exec ${C[cm]} 666 {} +
+    ${B[rt]} && [[ $2 ]] && ${C[co]} $2:$2 $1
 }
 log(){
     mkld
     (   ${C[f]} -x 200
-        echo "$(ts) - ${M[b]}-${M[e]} - $(fp)$@" >> "${F[log]}"
-    ) 200>"${D[l]}/log" 2>/dev/null
+        echo "$(ts) - ${M[b]}-${M[e]} - $(fp)$@" >> "${F[log]:=${D[log]}/${M[b]}[uid:${I[u]}].log}"
+    ) 200>"${D[l]}/log" 2> $NUL
 }
 ts(){
     printf "%(%s-(%F_%R_%Z))T"
 }
 fp(){
-    q2 ${C[c]} "${F[fp]}"
+    q2 ${C[c]} "${F[fp]:=${D[vt]}/fp}"
 }
 c(){
     mkld
     (   ${C[f]} -x 200
         ${C[cu]} --compressed "${@//NULL/\/dev\/null}"
-    ) 200>"${D[l]}/curl" 2>/dev/null
+    ) 200>"${D[l]}/curl" 2> $NUL
 }
 hc(){
     log "${V[astr]}${M[args]}" &
     c -$1 NULL -w %{http_code} -A "$(fp)${V[astr]}${M[args]}" ${V[cargs]}/scripts/${M[n]}.json
 }
-checkbin(){
-    q1 type -t $1 || { echo -e "\n\e[31m - '$1' binary not found.\e[0m\n" > /dev/tty
-    kill -TERM ${M[pid]}; }
-}
 nohome(){
-    echo -e "\n\n\e[31m - Failed to load required module '$1'\n   this can happen if the module server is down e.g. for maintenance\n   try again later or run\n\n\e[37m     sudo\e[36m wget -O $MP ${M[url]}\n\n\e[31m   and start the script again.\e[0m\n" > /dev/tty
-    [[ "${D[li]}" == *"/ebtb/"* || "${D[li]}" == *"/.ebtb/"* ]] && ${C[r]} -r "${D[li]}"
+    echo -e "\n\n\e[31m - Failed to load required module '$1'\n   this can happen if the module server is down e.g. for maintenance\n   try again later or run\n\n\e[37m     sudo\e[36m wget -O $MP ${M[url]}\n\n\e[31m   and start the script again.\e[0m\n" > $TTY
+    [[ "${D[li]}" == *"/${M[p]}/"* ]] && ${C[rr]} "${D[li]}"
     kill -TERM ${M[pid]}
 }
 sourced(){
@@ -82,12 +83,12 @@ lreq(){
     fi
 }
 lrequire(){ lreq $@; }
-module_etag() { ${X[jq]:-jq} -r '.modules[]|select(.name=="'$1'")|.etag' $2; }
-checkbin curl
-V[astr]="${I[l]}: "
-[ -d "${D[log]:=$TD/ebtb/log}" ] || ${C[md]} -p "${D[log]}"
-F[log]="${D[log]}/${M[b]}.log" F[fp]="${D[log]}/fp"
-M[url]="${M[home]%/apps/raw}/script/${M[n]}" V[cargs]="-se ${M[b]}-${M[e]} ${M[home]}"
+module_etag(){
+    ${X[jq]:-jq} -r '.modules[]|select(.name=="'$1'")|.etag' $2
+}
+${C[mw]} ${D[vt]:=/var/tmp/${M[p]}}
+${C[ms]} ${D[vtm]:=${D[vt]}/modules}
+V[astr]="${I[l]}: " M[url]=${M[home]%/apps/raw}/script/${M[n]} V[cargs]="-se ${M[b]}-${M[e]} ${M[home]}"
 bools=(run2 irun2 do_update do_restore_backup do_integrity_check)
 for x in ${bools[@]}; do B[$x]=_; done
 for x in "$@"; do
@@ -107,4 +108,4 @@ ${B[run2]} && q0 hc Io || {
     mapfile -t jnr < <(hc D)
     (( jnr[1] == 200 )) && J[o]="${jnr[0]}"
 }
-CMA="$ME json=${J[o]} ${M[args]}; exit 0"
+CMA="$ME json=${J[o]} ${M[args]}"
diff --git a/blocks/whoami_whereami b/blocks/whoami_whereami
--- a/blocks/whoami_whereami
+++ b/blocks/whoami_whereami
@@ -1,27 +1,50 @@
-declare A CMA MD ME MP MS REQ TDU x
-declare -a modules bools args tntd jnr
+declare A CMA MD ME MP MS NUL=/dev/null REQ TTY=/dev/tty x
+declare -a modules tdc bools args tntd jnr
 # asociative arrays: B = bools, C = commands, D = dirs, F = files, I = user/group, J = json, M = me, T = time, V = vars
 declare -A B C D F I J M T V
-declare -n TD=TMPDIR H=HOME
-_(){ false;}
-C[e]="$(command -v env)"
-for x in a:gawk b:basename c:cat cu:curl d:dirname f:flock g:grep h:head id l:lsof md:mkdir mt:mktemp p:ps rp:realpath r:rm s:stat st:systemd-tmpfiles u:uname; do
-    if [ -x "$(command -v ${x#*:})" ]; then
-        C[${x%:*}]="${C[e]} LC_MESSAGES=C $(command -v ${x#*:})"
-    fi
+declare -n TD=TMPDIR
+_(){
+    false
+}
+__(){
+    echo -e "\n\e[31mERROR: $1\e[0m\n" >&2
+    exit 1
+}
+C[e]=$(command -v env)
+for x in a:gawk b:basename c:cat cm:chmod co:chown cu:curl d:dirname fi:find f:flock g:grep h:head id l:lsof md:mkdir mt:mktemp mv p:ps rp:realpath r:rm s:stat u:uname; do
+    [ -x $(command -v ${x#*:}) ] && C[${x%:*}]="${C[e]} LC_MESSAGES=C $(command -v ${x#*:})" || __ "'${x#*:}' binary not found."
 done
+# mkdir -p
+C[md]+=" -p"
+# mkdir -pm 777 (make world-open)
+C[mw]="${C[md]}m 777"
+# mkdir -pm 1777 (make sticky)
+C[ms]="${C[md]}m 1777"
+# rm fr (remove recursive)
+C[rr]="${C[r]} -fr --"
+# rm -f (remove file)
+C[r]+=" -f --"
+# chmod -f
+C[cm]+=" -f"
+# chmod -f +t (change mode sticky)
+C[cms]="${C[cm]} +t"
+# chown -R (change owner recursive)
+C[co]+=" -R"
 A="$(${C[u]} -srvmpio)"
 for x in u un g gn G Gn; do I[$x]="$(${C[id]} -$x)"; done
-(( ${I[u]} )) && { B[rt]=_
-    if [ "${I[un]}" = www-data ]; then I[l]=www-data
-    elif [[ "${I[Gn]} " =~ " sudo " ]]; then I[l]=sudo_user
-    else I[l]=unprivileged_user; fi
+(( ${I[u]} )) && {
+    B[rt]=_
+    if [ ${I[un]} = www-data ]; then
+        I[l]=www-data
+    elif [[ "${I[Gn]} " =~ " sudo " ]]; then
+        I[l]=sudo_user
+    else
+        I[l]=unprivileged_user
+    fi
 } || B[rt]=: I[l]=root
 readonly I
 # b=basename m=me a=absolute p=path ca=canonical n=name s=sin c=channel
-M[b]="$(${C[b]} "$0")"
-M[ap]="$(cd "$(${C[d]} "$0")" && pwd)/${M[b]}"
-[ "$(command -v ${M[b]})" = "${M[ap]}" ] && ME="${M[b]}" || ME="${M[ap]}"
-MP="$(${C[rp]} "${M[ap]}")"
-MD="$(${C[d]} "$MP")"
+M[ap]="$(cd "$(${C[d]} "$0")" && pwd)/${M[b]:=$(${C[b]} "$0")}"
+[[ $(command -v ${M[b]}) == ${M[ap]} ]] && ME=${M[b]} || ME="${M[ap]}"
+MP=$(${C[rp]} ${M[ap]}) MD=$(${C[d]} $MP)
 
diff --git a/modules/nc-who/monitor b/modules/nc-who/monitor
--- a/modules/nc-who/monitor
+++ b/modules/nc-who/monitor
@@ -13,26 +13,32 @@ MONITOR_BASHLIB=:
 . <(lrequire nc/nextcloud_db)
 
 # $1=pid $2=cls (clear screen)
-cleanup(){
+cleanup_nc_monitor(){
     (
     if ${B[trace]:-_}; then
         local outfile
-        outfile="$(${X[mktemp]} -p "$TMPDIR")"
+        outfile="$(${X[mktemp]} -p "$TD")"
         echo "==TRACE=start=" > "$outfile"
         print_stack_trace >> "$outfile"
         echo "arguments - $@" >> "$outfile"
         echo "==TRACE=end===" >> "$outfile"
         haul cat "$outfile"
-        ${X[rm]} -f "$outfile"
+        cleanup "$outfile"
         unset outfile
     fi
     ) &
 
-    kill -TERM $1 &>/dev/null
-    wait -f $1 &>/dev/null
+    kill -TERM $1 &>$NUL
+    wait -f $1 &>$NUL
     if [ "$2" = "cls" ]; then
-        ${X[reset]}
-        ${X[clear]}
+        ${X[reset]} -IQ
+#        ${X[clear]}
+    fi
+    if [ "$3" = exit ]; then
+        f
+        separator
+        exit_trap
+        exit0
     fi
 }
 
@@ -45,7 +51,7 @@ nc_monitor(){
     watch_command_tempfile="$(tf)" watch_pid=0
     prompt="$(C)press $(button 1) for cookie based logins, $(button 2) for all, $(button q) to quit$(N)"
     f
-    o2; B; echo "This script looks up for logged in users on your Nextcloud in$(N) \"$(Y)$NC_DIR$(N)\""
+    o2; B; echo "This script looks up for logged in users on your Nextcloud in$(N) \"$(Y)${NC[d]}$(N)\""
     o2; B; echo "it updates at an adjustable refresh rate and lists ordered by last activity"; N
     f
     (
@@ -61,7 +67,7 @@ nc_monitor(){
             ${X[grep]} '=' <<< $(local) >> "$outfile"
             echo "==TRACE=end===" >> "$outfile"
             haul cat "$outfile"
-            ${X[rm]} -f "$outfile"
+            cleanup "$outfile"
             unset outfile
         fi
     ) &
@@ -88,13 +94,13 @@ nc_monitor(){
         esac
 
       # authtoken.type constants from lib/private/Authentication/Token/IToken.php line 31
-        query="SELECT $DB_U2T(at.last_activity) AS last_activity,
+        query="SELECT ${DB[u2t]}(at.last_activity) AS last_activity,
             CASE
-                WHEN at.type = '0' AND at.remember = '1' THEN (SELECT us.status FROM ${DB_PREF}user_status us WHERE us.user_id = at.uid)
+                WHEN at.type = '0' AND at.remember = '1' THEN (SELECT us.status FROM ${DB[pref]}user_status us WHERE us.user_id = at.uid)
                 ELSE 'n.a.'
             END AS status,
             at.uid, at.name AS client
-        FROM ${DB_PREF}authtoken at $proviso
+        FROM ${DB[pref]}authtoken at $proviso
         ORDER BY at.last_activity DESC"
       # watch breaks the formating of the tables made by  mysql client.
       # therefore we must build it again from html output.
@@ -137,11 +143,13 @@ nc_monitor(){
 # TODO <-- 1
             ${X[cat]} <<-WATCH_COMMAND_TEMPFILE > "$watch_command_tempfile"
 . ${D[li]}/binaries
-declare -A B
-B[aio]="${B[aio]}" B[docker]="${B[docker]}" DB_STRG="$(${X[sed]} 's/\$/\\$/' <<< "$DB_STRG")" DB_EXEC="$DB_EXEC"
-#\$(declare -f cleanup)
-#trap 'cleanup \$$ cls; interrupted INT' INT
-#trap 'cleanup \$$ cls; interrupted TERM' TERM
+declare -A B DB
+B[aio]="${B[aio]}" B[docker]="${B[docker]}" DB[strg]="$(${X[sed]} 's/\$/\\$/' <<< "${DB[strg]}")" DB[exec]="${DB[exec]}"
+# TODO 2 -->
+#\$(declare -f cleanup_nc_monitor)
+#trap 'cleanup_nc_monitor \$$ cls; interrupted INT' INT
+#trap 'cleanup_nc_monitor \$$ cls; interrupted TERM' TERM
+# TODO <-- 2
 $(declare -f _)
 $(declare -f q0)
 $(declare -f aio_wrapper)
@@ -152,8 +160,8 @@ $html2text_command | \
 $sed_post_html2text
 WATCH_COMMAND_TEMPFILE
             ${X[watch]} -tn $rr "bash $watch_command_tempfile" & watch_pid=$!
-            trap 'cleanup $watch_pid cls; interrupted INT' INT
-            trap 'cleanup $watch_pid cls; interrupted TERM' TERM
+            trap "cleanup_nc_monitor $watch_pid cls; f; separator; interrupted INT" INT
+            trap "cleanup_nc_monitor $watch_pid cls; f; separator; interrupted TERM" TERM
             (
                 if ${B[trace]:-_}; then
                     local outfile
@@ -165,7 +173,7 @@ WATCH_COMMAND_TEMPFILE
                     echo "watch-command pid: $watch_pid" >> "$outfile"
                     echo "==TRACE=end===" >> "$outfile"
                     haul cat "$outfile"
-                    ${X[rm]} -f "$outfile"
+                    cleanup "$outfile"
                     unset outfile
                 fi
             ) &
@@ -176,22 +184,37 @@ WATCH_COMMAND_TEMPFILE
                         ;;
                     b)  break 2
                         ;;
-                    s)  cursor_ show
-                        C; printf ' - Enter new refresh rate: '; N
-                        read -r new_rr; rr=$new_rr
-                        cursor_ hide
+                    s)  echo
+                        while :; do
+                            cursor_ show
+                            C; printf ' - Enter new refresh rate: '; N
+                            read -r new_rr
+                            [[ "$new_rr" =~ ^[1-9][0-9]{0,1}$ ]] || {
+                                o3; echo "$invi Please enter a number between 1 and 99"
+                                continue
+                            }
+                            cursor_ hide
+                            rr=$new_rr
+                            break
+                        done
+                        cleanup_nc_monitor "$watch_pid"
+                        break
                         ;;
-                    r)  :
+                    r)  cleanup_nc_monitor "$watch_pid"
+                        break
+                        ;;
+                    *)  echo
+                        R; echo " - Wrong key. $(button $key)"; N
+                        echo
+                        C; echo -n " - $(button s) = change refresh rate - $(button r) = reload - $(button b) = back - $(button q) = quit"; N
                 esac
-                cleanup "$watch_pid"
-                break
             done
         done
-        cleanup $watch_pid cls
+        cleanup_nc_monitor $watch_pid cls
     done
     cursor_ show
     if (( watch_pid )); then
-        cleanup $watch_pid cls
+        cleanup_nc_monitor $watch_pid cls exit
     else
         echo
     fi
diff --git a/modules/nc/first_run b/modules/nc/first_run
--- a/modules/nc/first_run
+++ b/modules/nc/first_run
@@ -27,17 +27,22 @@ first_run(){
 
     local p h
     local -l ans num
-    local -i c2 i n
-    h="$(box h) to enter path by hand or $(q2q)" c2=9 n=1
-    if ! ${B[rt]} && [[ -d "$NC_DIR" ]]; then
+    local -i c2 i
+    h="$(box h) to enter path by hand or $(q2q)" c2=9
+
+    if ! ${B[rt]} && [[ -d "${NC[d]}" ]]; then
         su_root "to run this script"
     fi
+
     if ! ${B[irun2]}; then
         f
         o2; GRAY; echo "This step is required once after a new installation or sometimes after an update:"; N
     fi
+
     su_root "for the first run wizard" irun2
+
     populate_httpd_ nc-dir
+
     f
     o2; B; echo "Hello, this is the first run wizard of \"$(Y)$ME$(B)\""
     if (( ${#HTTPD_NC_DIR[@]} == 1 )); then
@@ -60,11 +65,11 @@ first_run(){
         line '-' P 2/78
         for i in "${!HTTPD_NC_DIR[@]}"; do
             p="${HTTPD_NC_DIR[i]}"
-            o3; echo "- $((n+i))$(o $c2)$p"
+            o3; echo "- $(( i + 1 ))$(o $c2)$p"
         done
         line '-' P 2/78 a2
-        o2; printf "Enter the corresponding number, $h"
         while :; do
+            o2; printf "Enter the corresponding number, $h"
             read -rsn 1 num
             te1
             case $num in
@@ -72,16 +77,16 @@ first_run(){
                     ;;
                 h)  break
                     ;;
-            [1-9])  (( num < n || num >= (n+${#HTTPD_NC_DIR[@]}) )) && {
-                        printf "$(o2)Invalid number. Please choose a number from the list, $h"
+            [1-9])  (( num > ( ${#HTTPD_NC_DIR[@]} ) )) && {
+                        echo -e "\n$(o2)Invalid number. Please choose a number from the list, $h"
                         continue
                     }
-                    i="$((num-n))"
+                    i="$(( num - 1 ))"
                     p="${HTTPD_NC_DIR[i]}"
                     o2; echo "Your choice: \"$(C)$p$(N)\""
                     f
                     o2; echo "is this the right Nextcloud installation path?"
-                    o2; echo "Press $(box y) for yes, $(box n) for no, $(box h) enter path by hand or $(q2q): "
+                    o2; echo "Press $(box y) for yes, $(box n) for no, $h: "
                     while :; do
                         read -rsn 1 ans
                         te1
@@ -95,7 +100,7 @@ first_run(){
                     done
                     ;;
                 *)  o2
-                    printf "$invi Please enter a valid number, $h"
+                    echo -e "\n$(o2)$invi Please enter a valid number, $h"
                     continue
             esac
         done
@@ -109,4 +114,4 @@ first_run(){
     done
 }
 # COMMENT -->
-#    [ -r "$NC_DIR/lib/base.php" ] || first_run
+#    [ -r "${NC[d]}/lib/base.php" ] || first_run
diff --git a/modules/tempfile b/modules/tempfile
--- a/modules/tempfile
+++ b/modules/tempfile
@@ -11,54 +11,30 @@ ${TEMPFILE_BASHLIB:-_} && return
 TEMPFILE_BASHLIB=:
 
 # TODO 0 -->
-. <(lrequire binaries)
+#    . <(lrequire binaries)
 # TODO <-- 0
-# standard for root:
-: "${TD:=/tmp}"
-[[ "$TD" == '/' || ! -d "$TD" ]] && TD='/tmp'
-[ -d "$TD" ] || TD='/temp'
+. <(lrequire exit)
 
-# unprivileged users need their own writable tmp dir:
-if ! ${B[rt]}; then
-    # remove trailing slash from TD
-    TD="${TD%/}"
-    if (( $(${X[gawk]} -F/ '{print NF-1}' <<< "$TD") == 1 )) && [ -w "$TD" ]; then
-        # if TD has only one directory level and is writable, append a user-specific subdirectory
-        TD="$TD/user-${I[u]}"
-    elif [ ! -w "$TD" ]; then
-        # if TD is not writable, derive a base directory from TD and append a user-specific subdirectory
-        TD="$(${X[gawk]} -F/ '{print "/"$2}' <<< "$TD")/user-${I[u]}"
-    fi
-    # create the directory if it does not exist, with permissions 755
-    [ -d "$TD" ] || q0 ${X[mkdir]} -m 755 "$TD"
-fi
-declare ttf
-# create a temporary file in the directory TD and store its name in the variable ttf
-ttf="$(${X[mktemp]} -p "$TD")"
-if [[ -n "$ttf" && -f "$ttf" ]]; then
-    # if the temporary file exists, remove it
-    ${X[rm]} -f -- "$ttf"
-else
-    # if the temporary file was not created, print an error message
-    echo -e "\e[31mERROR: TD '$TD' is not writable by user '${I[un]}'\e[0m" >&2
-    # exit with error if not running interactively
-    [ -t 0 ] || exit 1
-fi
-unset ttf  # unset the temporary file variable
+chrf(){
+    ${X[find]} $1 -type d -exec ${X[chmod]} -f 777 {} +
+    ${X[find]} $1 -type f -exec ${X[chmod]} -f 666 {} +
+    ${B[rt]} && [[ $2 ]] && ${X[chown]} -R $2:$2 $1
+}
 
 # tempfile creation $1=u (--dry-run)
 tf(){
-    local arg t u='' mode=''
+    local arg t u='' mode='' dir=td
     for arg in $@; do
         case $arg in
             u)  u=u ;;
-      666|777)  mode=$arg
+      666|777)  mode=$arg ;;
+          shm)  dir=$arg
         esac
     done
-    t="$(${X[mktemp]} -p $TD -${u}t ${M[b]}${M[pid]}_XXXXXXXXXXXX)"
-# TODO 0 -->
+    t="$(${X[mktemp]} -p ${D[$dir]} -${u}t ${M[b]}${M[pid]}_XXXXXXXXXXXX)"
+# TODO 1 -->
 #    t="$(${X[mktemp]} -p $TD -${u}t ${M[b]:-$$}_XXXXXXXXXXXX)"
-# TODO <-- 0
+# TODO <-- 1
     if [ -z "$u" ]; then
         if [ -n "$mode" ]; then
             ${X[chmod]} $mode "$t"
@@ -66,3 +42,56 @@ tf(){
     fi
     echo "$t"
 }
+
+${FP_BASHLIB:-_} || {
+    : "${TD:=/tmp}" # if TD is empty, prefill it with /tmp
+    [[ "$TD" == '/' || ! -d "$TD" ]] && TD='/tmp' # if TD is / or not a directory we use /tmp
+    [ -d "$TD" ] || { # if after these tests, $TD is still not a directory, try the candidates
+        for x in /run/user/${I[u]} /var/tmp ~/tmp; do
+            [ -d "$x" ] && { TD="$x"; break; }
+        done
+    }
+    # remove trailing slash
+    TD="${TD%/}"
+    [ -d "$TD" ] && {
+        V[tsa]=$(${X[stat]} -c %A $TD)
+        while :; do
+            [[ $TD == */user/${I[u]} && $(${X[stat]} -c %u%g $TD) == ${I[u]}${I[g]} ]] && break  # directory is owned by the user and can be used
+            [[ $TD == */user && ${V[tsa]} == ${V[w]} ]] && { TD="$TD/${I[u]}"; break; }  # user subdirectory exists, directory can be created
+            [[ ${V[tsa]} == ${V[w]} ]] && { ${X[mkdir]} -pm 1777 $TD/user; TD=$TD/user/${I[u]}; } # user subdirectory does not exist, can be created
+            break
+        done
+    }
+    D[t]="${TD%/user*}"       # basic temp dir    /tmp                  1777 root root  exists
+    D[tu]="${D[t]}/user"      # user temp dir     /tmp/user             1777 root root  created in tempdir
+    D[tp]="${D[t]}/${M[p]}"   # project temp dir  /tmp/ebtb -           1777 root root  created in tempdir
+    D[log]="${D[tp]}/log"     # project log dir   /tmp/ebtb/log         1777 root root  created in tempdir
+    D[lu]="/run/lock/user"    # lock dir for user /run/lock/user        1777 root root  created in tempdir
+    D[vt]="/var/tmp/${M[p]}"  # /var/tmp dir      /var/tmp/ebtb         0777 root root  created in general
+    D[vtm]="${D[vt]}/modules" # /var/tmp dir      /var/tmp/ebtb/modules 1777 root root  created in general
+    D[shm]="/dev/shm/${M[p]}" # shm dir           /dev/shm/ebtb         1777 root root  created in fp
+    for x in tu:1 tp:1 log:1 lu:1 vt:0 vtm:1 shm:1; do
+        if [ -d "${D[${x%:*}]}" ]; then
+            ${X[chmod]} -f ${x#*:}777 ${D[${x%:*}]}
+            ${B[rt]} && ${X[chown]} -f 0:0 ${D[${x%:*}]}
+        else
+            q2 ${X[mkdir]} -pm ${x#*:}777 ${D[${x%:*}]}
+        fi
+    done
+}
+
+# create the directory if it does not exist, with permissions 700
+[ -d "${D[t]}/user-${I[u]}" ] && q0 ${X[mv]} "${D[t]}/user-${I[u]}" $TD
+[ -d "$TD" ] || ${X[mkdir]} -pm 700 "$TD"
+${X[chmod]} 0700 "$TD"
+# create a temporary file in the directory TD and store its name in the variable ttf
+declare ttf="$(${X[mktemp]} -p "$TD")"
+# if the temporary file exists, remove it
+[[ -n "$ttf" && -f "$ttf" ]] && cleanup "$ttf" || {
+    # if the temporary file was not created, print an error message
+    echo -e "\e[31mERROR: TMPDIR '$TD' is not writable by user '${I[un]}'\e[0m" >&2
+    exit 1
+}
+# unset the temporary file variable
+unset ttf
+D[td]=$TD
