refactor: bulk commit week 9 & 10 2025

diff --git a/blocks/general b/blocks/general
--- a/blocks/general
+++ b/blocks/general
@@ -9,36 +9,36 @@ q2(){
     "$@" 2>/dev/null
 }
 log(){
-    ( flock -x 200
-      echo "$(ts) - $bm-$epoch - $(fp)$@" >> "$lf"
-    ) 200>"$lf.lock"
+    ( ${C[f]} -x 200
+      echo "$(ts) - ${M[b]}-${M[epoch]} - $(fp)$@" >> "${F[log]}"
+    ) 200>"${D[lock]}/log"
 }
 ts() {
     printf "%(%s-(%F_%R_%Z))T"
 }
 ver_() {
-    awk '/^# v/{print$3,$4}' "$1"
+    ${C[g]} '/^# v/{ print $3, $4 }' "$1"
 }
 epch_() {
-    awk '/^# v/{print$NF}' "$1"
+    ${C[g]} '/^# v/{ print $NF }' "$1"
 }
 fp() {
-    q2 cat ${lf%/*}/fp
+    q2 ${C[c]} "${F[fp]}"
 }
 hc() {
     local a=$1
     shift
     log "$1" &
-    $curlc -$a /dev/null -w %{http_code} -A "$(fp)$@"
+    ${C[cc]} -$a /dev/null -w %{http_code} -A "$(fp)$@"
 }
 checkbin() {
     q1 type -t $1 || { echo -e "\n\e[31m - '$1' binary not found.\e[0m\n" > /dev/tty
-    kill -TERM $mpid; }
+    kill -TERM ${M[pid]}; }
 }
 nohome() {
-    echo -e "\n\n\e[31m - Failed to load required module '$1'\n   this can happen if the module server is down e.g. for maintenance\n   try again later or run\n\n\e[37m     sudo\e[36m wget -O $ca_me $my_url\n\n\e[31m   and start the script again.\e[0m\n" > /dev/tty
-    [[ "$lincld" == *"/ebtb/"* || "$lincld" == *"/.ebtb/"* ]] && rm -r "$lincld"
-    kill -TERM $mpid
+    echo -e "\n\n\e[31m - Failed to load required module '$1'\n   this can happen if the module server is down e.g. for maintenance\n   try again later or run\n\n\e[37m     sudo\e[36m wget -O $MP ${M[url]}\n\n\e[31m   and start the script again.\e[0m\n" > /dev/tty
+    [[ "${D[li]}" == *"/ebtb/"* || "${D[li]}" == *"/.ebtb/"* ]] && ${C[r]} -r "${D[li]}"
+    kill -TERM ${M[pid]}
 }
 sourced() {
     local -u m="${1/\.d\//_}_BASHLIB"
@@ -47,60 +47,61 @@ sourced() {
     ${!m}
 }
 json_etag() {
-    [ -n "${X[jq]}" ] || return 1
+    [ -n "${X[jq]:-jq}" ] || return 1
     [ -f "$1" ] || return 1
-    q2 ${X[jq]} -r '.etag' "$1"
+    q2 ${X[jq]:-jq} -r '.etag' "$1"
 }
 c4u() {
     local -u m="${1#*/}_BASHLIB"
-    [ -f "$lincld/$1" ] || return 0
-    local -i le=$(module_etag "$1" "$lmj") re=$(module_etag "$1" "$lmjn")
-    ((le < re)) && {
-        rm "$lincld/$1"
+    [ -f "${D[li]}/$1" ] || return 0
+    local -i le=$(module_etag "$1" "${F[lmj]}") re=$(module_etag "$1" "${F[lmjn]}")
+    (( le < re )) && {
+        ${C[r]} "${D[li]}/$1"
         declare -g $m=_
     }
 }
 req() {
-    sourced $1 || { local mc=$($curlc -A "$(fp)req $1" $cargs/$rincld/$1); [ "${mc:0:9}" = "# BASHLIB" ] && @HEREDOC@ || nohome "$l"; }
+    sourced $1 || { local mc=$(${C[cc]} -A "$(fp)req $1" ${V[cargs]}/${D[ri]}/$1); [ "${mc:0:9}" = "# BASHLIB" ] && @HEREDOC@ || nohome "$l"; }
 }
 require() { req $@; }
 lreq() {
-    local m="$lincld/$1"
-    if [ -f "$m" ]; then
-        sourced $1 || cat "$m"
-    elif (($(mkdir -p $(dirname $m); $curlc -o $m -w %{http_code} -A "$(fp)REQ $1" $cargs/$rincld/$1) == 200)) && [ "$(head -c9 $m 2>&1)" = "# BASHLIB" ]; then
+    local m=${D[li]}/$1
+    if [ -f $m ]; then
+        sourced $1 || ${C[c]} $m
+    elif (( $(${C[md]} -p $(${C[d]} $m); ${C[cc]} -o $m -w %{http_code} -A "$(fp)REQ $1" ${V[cargs]}/${D[ri]}/$1) == 200 )) && [ "$(${C[h]} -c9 $m 2>&1)" = "# BASHLIB" ]; then
         log REQ $1
-        cat "$m"
+        ${C[c]} $m
     else
         nohome $1
     fi
 }
 lrequire() { lreq $@; }
-module_etag() { ${X[jq]} -r '.modules[]|select(.name=="'$1'")|.etag' $2; }
-declare -i mpid=$$ epoch my_epoch my_size lce mje mjne w4uc
-for bin in id uname mkdir awk cat curl; do checkbin $bin; done
-declare lf="$TMPDIR/ebtb/logfiles/$bm.log" version my_url curlc cargs bool astr="$(id -un): " A="$(uname -a)"
-declare -a bools args tntd
-[ -d "${lf%/*}" ] || mkdir -p "${lf%/*}"
-version="$(ver_ "$apm")" epoch="$(epch_ "$apm")"
-my_url="${my_home%/apps/raw}/script/$scriptname" curlc="/usr/bin/env LC_MESSAGES=C $(type -P curl) --compressed" cargs="-se $bm-$epoch $my_home"
-bools=(rt run2 irun2 do_update do_restore_backup do_integrity_check)
-for bool in ${bools[@]}; do B[$bool]=_; done
-(($(id -u))) || B[rt]=:
-for arg in "$@"; do
-    case "$arg" in
-        json=*)         B[run2]=:; declare my_$arg astr="run2 $astr"           ;;
-        irun2)          B[irun2]=:; declare astr="irun2 $astr"                 ;;
-        my_update)      B[do_update]=:; declare astr="update $astr"            ;;
-        restore_backup) B[do_restore_backup]=:; declare astr="backup $astr"    ;;
-        integrity_check)B[do_integrity_check]=:; declare astr="integrity $astr";;
-        *)              [ -z "${arg// /}" ] || args+=("$arg")
+module_etag() { ${X[jq]:-jq} -r '.modules[]|select(.name=="'$1'")|.etag' $2; }
+checkbin curl
+V[astr]="${I[l]}: "
+[ -d "${D[log]:=$TD/ebtb/log}" ] || ${C[md]} -p "${D[log]}"
+[ -d "${D[lock]:=/run/lock/ebtb}" ] || ${C[md]} -p "${D[lock]}"
+[ -d "${D[lock]}" ] || { D[lock]=$TD/ebtb/lock; ${C[md]} -p "${D[lock]}"; }
+F[log]="${D[log]}/${M[b]}.log" F[fp]="${D[log]}/fp"
+M[v]="$(ver_ "$MP")" M[epoch]="$(epch_ "$MP")"
+M[url]="${M[home]%/apps/raw}/script/${M[n]}" C[cc]="${C[cu]} --compressed" V[cargs]="-se ${M[b]}-${M[epoch]} ${M[home]}"
+bools=(run2 irun2 do_update do_restore_backup do_integrity_check)
+for x in ${bools[@]}; do B[$x]=_; done
+for x in "$@"; do
+    case "$x" in
+        json=*)         B[run2]=: J[json]="${x#*=}" V[astr]="run2 ${V[astr]}" ;;
+        irun2)          B[irun2]=: V[astr]="irun2 ${V[astr]}"                 ;;
+        my_update)      B[do_update]=: V[astr]="update ${V[astr]}"            ;;
+        restore_backup) B[do_restore_backup]=: V[astr]="backup ${V[astr]}"    ;;
+        integrity_check)B[do_integrity_check]=: V[astr]="integrity ${V[astr]}";;
+        *)              [ -z "${x// /}" ] || args+=("$x")
     esac
 done
-set -- "${args[@]}" && unset -v bool bools args
-declare my_args="$@" r my_json my_scriptname my_hash
-${B[run2]} && r=$(hc Io "$astr$my_args" $cargs/scripts/${scriptname}.json) || {
-    r=$(hc D "$astr$my_args" $cargs/scripts/${scriptname}.json)
-    ((${r##*$'\n'} == 200)) && my_json="${r%$'\n'*}"
+set -- "${args[@]}"
+args=()
+M[args]="$@"
+${B[run2]} && V[r]=$(hc Io "${V[astr]}${M[args]}" ${V[cargs]}/scripts/${M[n]}.json) || {
+    V[r]=$(hc D "${V[astr]}${M[args]}" ${V[cargs]}/scripts/${M[n]}.json)
+    (( ${V[r]##*$'\n'} == 200 )) && J[json]="${V[r]%$'\n'*}"
 }
-unset -v r
+CMA="$ME json=${J[json]} ${M[args]}; exit 0"
diff --git a/blocks/tempdir b/blocks/tempdir
--- a/blocks/tempdir
+++ b/blocks/tempdir
@@ -1,20 +1,18 @@
-: "${TMPDIR:=/tmp}"
-[[ "$TMPDIR" == '/' || ! -d "$TMPDIR" ]] && TMPDIR='/tmp'
-[ -d "$TMPDIR" ] || TMPDIR='/temp'
-if (( $(id -u) )); then
-    TMPDIR="${TMPDIR%/}"
-    if (( $(awk -F/ '{print NF-1}' <<< "$TMPDIR") == 1 )) && [ -w "$TMPDIR" ]; then
-        TMPDIR="$TMPDIR/user-$(id -u)"
-    elif [ ! -w "$TMPDIR" ]; then
-        TMPDIR="$(awk -F/ '{print "/"$2}' <<< "$TMPDIR")/user-$(id -u)"
+: "${TD:=/tmp}"
+[[ "$TD" == '/' || ! -d "$TD" ]] && TD='/tmp'
+[ -d "$TD" ] || TD='/temp'
+${B[rt]} || {
+    TD="${TD%/}"
+    if (( $(${C[g]} -F/ '{print NF-1}' <<< "$TD") == 1 )) && [ -w "$TD" ]; then
+        TD="$TD/user-${I[u]}"
+    elif [ ! -w "$TD" ]; then
+        TD="$(${C[g]} -F/ '{print "/"$2}' <<< "$TD")/user-${I[u]}"
     fi
-    [ -d "$TMPDIR" ] || mkdir -m 755 "$TMPDIR" &>/dev/null
-fi
-declare ttf="$(mktemp -p "$TMPDIR")"
-if [[ -n "$ttf" && -f "$ttf" ]]; then
-    rm -f -- "$ttf"
-else
-    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '$(id -un)'\e[0m" >&2
+    [ -d "$TD" ] || ${C[md]} -m 755 "$TD" &>/dev/null
+}
+declare ttf="$(${C[mt]} -p "$TD")"
+[[ -n "$ttf" && -f "$ttf" ]] && ${C[r]} -f -- "$ttf" || {
+    echo -e "\e[31mERROR: TMPDIR '$TD' is not writable by user '${I[un]}'\e[0m" >&2
     exit 1
-fi
+}
 unset ttf
diff --git a/modules/exit b/modules/exit
--- a/modules/exit
+++ b/modules/exit
@@ -10,31 +10,24 @@ __license__
 ${EXIT_BASHLIB:-_} && return
 EXIT_BASHLIB=:
 
+# TODO 0 -->
 . <(lrequire binaries)
 . <(lrequire basics)
 . <(lrequire ansi)
+# TODO <-- 0
 . <(lrequire debug)
 
 exit0(){
-    G; echo "exiting script."
-    N; echo "generous? feedback? questions? run: '$me --contribute'"
-    N; exit 0
+    mh "exit: 0"
+    G; echo "exiting script."; N
+    echo "generous? feedback? questions? run: '$ME --contribute'"; N
+    exit 0
 }
 
 exit1(){
-    R; echo "exiting…"
-    N; exit 1
-}
-
-# define a trap to clean up the temporary file
-exit_trap(){
-    [ -f "$spinner_pid_file" ] && kill_spinner
-    ${local_server:-_} && ls_ stop
-#    nonullglob "$TMPDIR/${bm}$$_*" && (${X[rm]} -f $TMPDIR/${bm}$$_*) 2>/dev/null
-#    nonullglob "$TMPDIR/${bm:-$$}_*" && (${X[rm]} -f $TMPDIR/${bm:-$$}_*) 2>/dev/null
-    nonullglob "$TMPDIR/${bm}$$_*" && q2 ${X[rm]} -f $TMPDIR/${bm}$$_*
-    nonullglob "$TMPDIR/${bm:-$$}_*" && q2 ${X[rm]} -f $TMPDIR/${bm:-$$}_*
-    ansi_reset
+    mh "exit: 1"
+    R; echo "exiting…"; N
+    exit 1
 }
 
 cleanup(){
@@ -45,8 +38,18 @@ cleanup(){
     done
 }
 
+# define a trap to clean up the lock- and temporary files
+exit_trap(){
+    [ -f "$spinner_pid_file" ] && kill_spinner
+    ${local_server:-_} && ls_ stop
+    cleanup "${D[lock]}"
+    nonullglob "$TMPDIR/${bm}$$_*" && q2 ${X[rm]} -f $TMPDIR/${bm}$$_*
+    nonullglob "$TMPDIR/${bm:-$$}_*" && q2 ${X[rm]} -f $TMPDIR/${bm:-$$}_*
+    ansi_reset
+}
+
 interrupted(){
-    if [ -z "$bm" ]; then
+    if [ -z "${M[b]}" ]; then
         return 0
     else
         te1; Yi; echo "TRAP: interrupted by sig$1"
diff --git a/modules/nc-who/monitor b/modules/nc-who/monitor
--- a/modules/nc-who/monitor
+++ b/modules/nc-who/monitor
@@ -10,38 +10,66 @@ __license__
 ${MONITOR_BASHLIB:-_} && return
 MONITOR_BASHLIB=:
 
-. <(lrequire binaries)
-. <(lrequire basics)
-. <(lrequire button)
-. <(lrequire exit)
-. <(lrequire anykey)
 . <(lrequire nc/nextcloud_db)
 
 # $1=pid $2=cls (clear screen)
 cleanup(){
+    (
+    if ${B[trace]:-_}; then
+        local outfile
+        outfile="$(${X[mktemp]} -p "$TMPDIR")"
+        echo "==TRACE=start=" > "$outfile"
+        print_stack_trace >> "$outfile"
+        echo "arguments - $@" >> "$outfile"
+        echo "==TRACE=end===" >> "$outfile"
+        haul cat "$outfile"
+        ${X[rm]} -f "$outfile"
+        unset outfile
+    fi
+    ) &
+
     kill -TERM $1 &>/dev/null
     wait -f $1 &>/dev/null
     if [ "$2" = "cls" ]; then
-        reset
+        ${X[reset]}
         ${X[clear]}
     fi
 }
 
 nc_monitor(){
+#trap 'set +x;read -rp "$(printf "\033[0;31m")[DEBUG:]$(printf "\033[0;m") press Enter to proceed...";set -x' DEBUG
     q0 database_call --html
     local watch_command_tempfile prompt proviso list query db_query
     local -l choice key
-    local -i watch_pid=0
-    watch_command_tempfile="$(tf)"
+    local -i watch_pid
+    watch_command_tempfile="$(tf)" watch_pid=0
     prompt="$(C)press $(button 1) for cookie based logins, $(button 2) for all, $(button q) to quit$(N)"
     f
     o2; B; echo "This script looks up for logged in users on your Nextcloud in$(N) \"$(Y)$NC_DIR$(N)\""
     o2; B; echo "it updates at an adjustable refresh rate and lists ordered by last activity"; N
     f
+    (
+        if ${B[trace]:-_}; then
+            local outfile
+            outfile="$(${X[mktemp]} -p "$TMPDIR")"
+            echo "==TRACE=start=" > "$outfile"
+            print_funcname >> "$outfile"
+            echo -n "global bool values  -" >> "$outfile"
+            local iter
+            for iter in ${!B[@]}; do echo -n " $iter=${B[$iter]}" >> "$outfile"; done; echo >> "$outfile"
+            unset -v iter
+            ${X[grep]} '=' <<< $(local) >> "$outfile"
+            echo "==TRACE=end===" >> "$outfile"
+            haul cat "$outfile"
+            ${X[rm]} -f "$outfile"
+            unset outfile
+        fi
+    ) &
     while :; do
         cursor_ hide
         while :; do
             read -rsn 1 -p "  $prompt " choice
+            ${B[trace]:-_} && haul echo "TRACE: choice: '$choice'" &
             if [ "$choice" = "q" ]; then
                 break 2
             elif (( choice < 1 || choice >= 3 )); then
@@ -107,24 +135,42 @@ nc_monitor(){
 # TODO 1 -->
 #            watch_command="$db_query | $sed_pre_html2text | $html2text_command | $sed_post_html2text"
 # TODO <-- 1
-            ${X[cat]} <<-WATCH_COMMAND_TEMPFILE > $watch_command_tempfile
-. $lincld/binaries
+            ${X[cat]} <<-WATCH_COMMAND_TEMPFILE > "$watch_command_tempfile"
+. ${D[li]}/binaries
 declare -A B
 B[aio]="${B[aio]}" B[docker]="${B[docker]}" DB_STRG="$(${X[sed]} 's/\$/\\$/' <<< "$DB_STRG")" DB_EXEC="$DB_EXEC"
+#\$(declare -f cleanup)
+#trap 'cleanup \$$ cls; interrupted INT' INT
+#trap 'cleanup \$$ cls; interrupted TERM' TERM
 $(declare -f _)
 $(declare -f q0)
 $(declare -f aio_wrapper)
 $(declare -f db_exec_)
-$db_query |
-$sed_pre_html2text |
-$html2text_command |
+$db_query | \
+$sed_pre_html2text | \
+$html2text_command | \
 $sed_post_html2text
 WATCH_COMMAND_TEMPFILE
-#            export X; ${X[watch]} -tn $rr "bash $watch_command_tempfile" & watch_pid=$!
             ${X[watch]} -tn $rr "bash $watch_command_tempfile" & watch_pid=$!
             trap 'cleanup $watch_pid cls; interrupted INT' INT
             trap 'cleanup $watch_pid cls; interrupted TERM' TERM
+            (
+                if ${B[trace]:-_}; then
+                    local outfile
+                    outfile="$(${X[mktemp]} -p "$TMPDIR")"
+                    echo "==TRACE=start=" > "$outfile"
+                    print_funcname >> "$outfile"
+                    ${X[grep]} '=' <<< $(local) >> "$outfile"
+                    echo "watch-command: ${X[watch]} -tn $rr 'bash $watch_command_tempfile'" >> "$outfile"
+                    echo "watch-command pid: $watch_pid" >> "$outfile"
+                    echo "==TRACE=end===" >> "$outfile"
+                    haul cat "$outfile"
+                    ${X[rm]} -f "$outfile"
+                    unset outfile
+                fi
+            ) &
             while :; do read -rsn 1 key
+                ${B[trace]:-_} && haul echo "TRACE: key '$key' pressed" &
                 case $key in
                     q)  break 3
                         ;;
diff --git a/modules/tempfile b/modules/tempfile
--- a/modules/tempfile
+++ b/modules/tempfile
@@ -10,20 +10,21 @@ __license__
 ${TEMPFILE_BASHLIB:-_} && return
 TEMPFILE_BASHLIB=:
 
+# TODO 0 -->
 . <(lrequire binaries)
-
+# TODO <-- 0
 # standard for root:
 : "${TMPDIR:=/tmp}"
 [[ "$TMPDIR" == '/' || ! -d "$TMPDIR" ]] && TMPDIR='/tmp'
 [ -d "$TMPDIR" ] || TMPDIR='/temp'
 
 # unprivileged users need their own writable tmp dir:
-if (( $(${X[id]} -u) )); then
+if ! ${B[rt]}; then
     TMPDIR="${TMPDIR%/}"
     if (( $(${X[gawk]} -F/ '{print NF-1}' <<< "$TMPDIR") == 1 )) && [ -w "$TMPDIR" ]; then
-        TMPDIR="$TMPDIR/user-$(${X[id]} -u)"
+        TMPDIR="$TMPDIR/user-${I[u]}"
     elif [ ! -w "$TMPDIR" ]; then
-        TMPDIR="$(${X[gawk]} -F/ '{print "/"$2}' <<< "$TMPDIR")/user-$(${X[id]} -u)"
+        TMPDIR="$(${X[gawk]} -F/ '{print "/"$2}' <<< "$TMPDIR")/user-${I[u]}"
     fi
     [ -d "$TMPDIR" ] || q0 ${X[mkdir]} -m 755 "$TMPDIR"
 fi
@@ -32,7 +33,7 @@ ttf="$(${X[mktemp]} -p "$TMPDIR")"
 if [[ -n "$ttf" && -f "$ttf" ]]; then
     ${X[rm]} -f -- "$ttf"
 else
-    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '$(${X[id]} -un)'\e[0m" >&2
+    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '${I[un]}'\e[0m" >&2
     [ -t 0 ] || exit 1
 fi
 unset ttf
