refactor: massive rewrite of code

diff --git a/blocks/general b/blocks/general
--- a/blocks/general
+++ b/blocks/general
@@ -1,4 +1,13 @@
 # general
+q0(){
+  "$@" &>/dev/null
+}
+q1(){
+  "$@" >/dev/null
+}
+q2(){
+  "$@" 2>/dev/null
+}
 log(){
     ( flock -x 200
       echo "$(ts) - $bm-$epoch - $(fp)$@" >> "$lf"
@@ -14,13 +23,17 @@ epch_() {
     awk '/^# v/{print$NF}' "$1"
 }
 fp() {
-    cat $lincld/fp 2>/dev/null
+    q2 cat $lincld/fp
 }
 hc() {
     local a=$1
     shift
     log "$1" &
-    curl -$a /dev/null -w %{http_code} -A "$(fp)$@"
+    $curlc -$a /dev/null -w %{http_code} -A "$(fp)$@"
+}
+checkbin() {
+    q1 type -t $1 || { echo -e "\n\e[31m - '$1' binary not found.\e[0m\n" > /dev/tty
+    kill -TERM $mpid; }
 }
 nohome() {
     echo -e "\n\n\e[31m - Failed to load required module '$1'\n   this can happen if the module server is down e.g. for maintenance\n   try again later or run\n\n\e[37m     sudo\e[36m wget -O $ca_me $my_url\n\n\e[31m   and start the script again.\e[0m\n" > /dev/tty
@@ -34,8 +47,8 @@ sourced() {
     ${am:-false}
 }
 json_etag() {
-    command -v jq >/dev/null || return 1
-    jq -r '.etag' "$1" 2>/dev/null
+    [ -n "${BINARIES[jq]}" ] || return 1
+    q2 ${BINARIES[jq]} -r '.etag' "$1"
 }
 c4u() {
     local -u m="${1#*/}_BASHLIB"
@@ -47,7 +60,7 @@ c4u() {
     }
 }
 req() {
-    sourced $1 || { local mc=$(curl -A "$(fp)req $1" $cargs/$rincld/$1); [ "${mc:0:9}" = "# BASHLIB" ] && @HEREDOC@ || nohome "$l"; }
+    sourced $1 || { local mc=$($curlc -A "$(fp)req $1" $cargs/$rincld/$1); [ "${mc:0:9}" = "# BASHLIB" ] && @HEREDOC@ || nohome "$l"; }
 }
 require() { req $@; }
 lreq() {
@@ -56,7 +69,7 @@ lreq() {
         sourced $1 || cat "$m"
     elif ! $rt; then
         req $1
-    elif (($(mkdir -p $(dirname $m); curl -o $m -w %{http_code} -A "$(fp)REQ $1" $cargs/$rincld/$1) == 200)) && [ "$(head -c9 $m 2>&1)" = "# BASHLIB" ]; then
+    elif (($(mkdir -p $(dirname $m); $curlc -o $m -w %{http_code} -A "$(fp)REQ $1" $cargs/$rincld/$1) == 200)) && [ "$(head -c9 $m 2>&1)" = "# BASHLIB" ]; then
         log REQ $1
         cat "$m"
     else
@@ -65,13 +78,13 @@ lreq() {
 }
 lrequire() { lreq $@; }
 module_etag() { jq -r '.modules[]|select(.name=="'$1'")|.etag' $2; }
-declare lf version my_url cargs opt opts astr="$(id -un): " A="$(uname -a)"
-declare -i mpid epoch my_epoch my_size lce mje mjne w4uc
+declare -i mpid=$$ epoch my_epoch my_size lce mje mjne w4uc
+for bin in id uname mkdir awk cat curl; do checkbin $bin; done
+declare lf="$TMPDIR/ebtb-logfiles/$bm.log" version my_url curlc cargs opt opts astr="$(id -un): " A="$(uname -a)"
 declare -a args tntd
-mpid=$$ lf="$TMPDIR/ebtb-logfiles/$bm.log"
 [ -d "${lf%/*}" ] || mkdir -p "${lf%/*}"
 version="$(ver_ "$apm")" epoch="$(epch_ "$apm")"
-my_url="${my_home%/apps/raw}/script/$scriptname" cargs="-se $bm-$epoch $my_home"
+my_url="${my_home%/apps/raw}/script/$scriptname" curlc="/usr/bin/env LC_MESSAGES=C $(type -P curl) --compressed" cargs="-se $bm-$epoch $my_home"
 opts="rt run2 irun2 do_update do_restore_backup do_integrity_check"
 for opt in $opts; do declare $opt=false; done
 (($(id -u))) || rt=:
diff --git a/modules/nc/nextcloud_aio b/modules/nc/nextcloud_aio
--- a/modules/nc/nextcloud_aio
+++ b/modules/nc/nextcloud_aio
@@ -10,20 +10,27 @@ __license__
 ${NEXTCLOUD_AIO_BASHLIB:-false} && return
 NEXTCLOUD_AIO_BASHLIB=:
 
-# for backwards compatibility
-declare -f lrequire &>/dev/null||lrequire(){ require $@;}
-
+. <(lrequire binaries)
+. <(lrequire basics)
 . <(lrequire sudo)
 
 globals="AIO DOCKER"
-for global in $globals; do declare -g $global 2>/dev/null || declare $global; done
+for global in $globals; do q2 declare -g $global || declare $global; done
 unset -v global globals
 AIO=false DOCKER=false
+
+aio_not_supported(){
+    $AIO || return 0
+    f;pf;R;echo "This script cannot be used with Nextcloud All-in-One …"
+    exit1
+}
+
+[ -n "${BINARIES[docker]}" ] || return
 
 detect_aio(){
     docker_ps_json="$(tf)"
     # detect if any docker containers are running on the host (without -a, because only running containers matter here)
-    docker ps --no-trunc --format=json 2>/dev/null > $docker_ps_json
+    q2 ${BINARIES[docker]} ps --no-trunc --format=json > $docker_ps_json
     mapfile -t docker_names< <(jq -r .Names $docker_ps_json)
     if (( ${#docker_names[@]} )); then
         if [[ "${docker_names[@]}" =~ nextcloud-aio-mastercontainer && "${docker_names[@]}" =~ nextcloud-aio-nextcloud ]]; then
@@ -43,17 +50,11 @@ aio_wrapper(){
     fi
     container_name="$1"
     shift
-    sudo docker exec $interactive_tty "nextcloud-aio-$container_name" bash -c "$*"
-}
-
-aio_not_supported(){
-    $AIO || return 0
-    f;pf;R;echo "This script cannot be used with Nextcloud All-in-One …"
-    exit1
+    ${BINARIES[sudo]} ${BINARIES[docker]} exec $interactive_tty "nextcloud-aio-$container_name" bash -c "$*"
 }
 
 if (( $(id -u) )); then # you are not root
-    if ps aux | grep -qs "[d]ockerd"; then # dockerd is running
+    if ${BINARIES[ps]} aux | ${BINARIES[grep]} -qs "[d]ockerd"; then # dockerd is running
         su_root "to detect all-in-one"
     fi
 else
diff --git a/scripts/nc-mimecheck b/scripts/nc-mimecheck
--- a/scripts/nc-mimecheck
+++ b/scripts/nc-mimecheck
@@ -26,12 +26,14 @@ __license__
 __scriptname__
 
 deps=(
+    "gawk#gawk#GNU awk"
+    "grep#grep#GNU grep, egrep and fgrep"
     "gpg#gnupg#GNU Privacy Guard"
     "jq#jq#command-line JSON processor"
 )
 modules=(
-    basics awksed tempfile ansi prefix button exit anykey verbose line array
-    ask sudo dependency vdir integrity nc/nextcloud nc/nextcloud_db
+    binaries basics awksed tempfile ansi prefix button exit anykey verbose line
+    array ask sudo dependency vdir integrity nc/nextcloud nc/nextcloud_db
     $sin/mime_types $sin/help $sin/functions
 )
 
@@ -131,7 +133,7 @@ shopt -u extglob
 [ -n "$shiftedoption" ]&&set -- $shiftedoption $@
 unset shiftedoption
 
-options=$(getopt -o dhl:qrv -l help,listmimes:,detector:,dryrun,recursive,quiet,verbose,debug -qn "$me" -- "$@")
+options=$(${BINARIES[getopt]} -o dhl:qrv -l help,listmimes:,detector:,dryrun,recursive,quiet,verbose,debug -qn "$me" -- "$@")
 if (($?==0));then
     eval set -- "$options"
     while :;do
@@ -270,7 +272,7 @@ fi
 cd "$NC_DATADIR"
 
 # remove absolute path to NC_DATADIR if not invoked by nextcloud flow
-basepath="$(echo "$*"|sed 's\'$NC_DATADIR'/\\1')"
+basepath="$(echo "$*"|${BINARIES[sed]} 's\'$NC_DATADIR'/\\1')"
 user2check="$(check_username_case "${basepath%%/*}")"
 [ "$user2check" = "${basepath%%/*}" ]||{
     v_echo "$(pf;Y)user case corrected:$(N) from \"$(B)${basepath%%/*}$(N)\" to \"$(B)$user2check$(N)\" "
@@ -289,7 +291,7 @@ fi
 # thoroughly but slowly tests
 iid="$(nc_configkey instanceid)"
 blacklist="appdata_$iid|updater-$iid"
-if echo "$basepath"|grep -Eqs  "$blacklist";then
+if echo "$basepath"|${BINARIES[grep]} -Eqs  "$blacklist";then
     wrong_option "blacklisted filepath $(Pbg)$basepath$(N)"
 else
     v_echo "$(pf;Y)basepath is no system dir (appdata or backup). $gg"
@@ -298,7 +300,7 @@ fi
 # TODO: enable groupfolders
 #    groupfolder = __groupfolders/$groupfolder_id/
 # if groupfolder, not occ files:scan but occ groupfolders:scan
-if echo "$basepath"|grep $grepopts "__groupfolders/[0-9]";then
+if echo "$basepath"|${BINARIES[grep]} $grepopts "__groupfolders/[0-9]";then
     wrong_option "groupfolders not (yet) supported"
 else
     v_echo "$(pf;Y)basepath is not a groupfolder. $gg"
@@ -306,7 +308,7 @@ fi
 
 # check if basepath is a user
 #       user dir = $user_id/files/
-#occ user:info "${basepath%%/*}"|grep $grepopts "enabled: true"
+#occ user:info "${basepath%%/*}"|${BINARIES[grep]} $grepopts "enabled: true"
     # this does not work with usernames containing spaces:
     #if enabled_user="$(occ user:info --output=json -- "'$user2check'"|jq '.enabled')"; then
 if $(user_exists "$user2check"); then
@@ -319,7 +321,7 @@ if $(user_exists "$user2check"); then
             basepath="$basepath/files/"
             v_echo "$(pf;Y)relative basepath now is:$(N) \"$(B)$basepath$(N)\""
         fi
-        if echo "$basepath/"|grep $grepopts "^${basepath%%/*}/files/";then
+        if echo "$basepath/"|${BINARIES[grep]} $grepopts "^${basepath%%/*}/files/";then
             v_echo "$(pf;Yi)basepath check succeeded. $gg"
         else
             wom1="basepath $(Pbg)$basepath$(R)"
@@ -373,9 +375,9 @@ if [ -d "$basepath" ];then
 else
 # if $actualpath is a file, only that file will be treated.
     #exract path for occ files:scan at the end
-    path="$(dirname "$basepath")"
+    path="$(${BINARIES[dirname]} "$basepath")"
     mimetype="$($mimedetector "$basepath")"
-    echo "${mime_ext_regex_array[@]%%:*}"|grep -qsw "$mimetype"||error "MIME type '$mimetype' not supported"
+    echo "${mime_ext_regex_array[@]%%:*}"|${BINARIES[grep]} -qsw "$mimetype"||error "MIME type '$mimetype' not supported"
     extension="$(a_fld mime_ext_regex_array ':' "$mimetype" 2)"
     regex="$(a_fld mime_ext_regex_array ':' "$mimetype" 3)"
     main "$basepath" "$regex" "$extension" "$mimetype"
