refactor: make scripts handleable for non-root users

diff --git a/modules/nc/first_run b/modules/nc/first_run
--- a/modules/nc/first_run
+++ b/modules/nc/first_run
@@ -20,13 +20,13 @@ FIRST_RUN_BASHLIB=:
 first_run(){
     te1
 
-    complete(){
+    finish(){
         mh "vdir: $1" &
         setvdir v "$1"
         f
-        o2; echo "- $(lG)first run wizard completed successfully."; N
+        o2; echo "- $(lG)first run wizard completed successfully. Please start script again"; N
+        o2; echo "- $(lG)No further root rights are required to use the script except for updating."; N
         f
-        $me "json=$my_json" $my_args
         exit 0
     }
 
@@ -54,7 +54,7 @@ first_run(){
             case ${ans:-y} in
                 q)  exit 0
                     ;;
-                y)  complete "$p"
+                y)  finish "$p"
                     ;;
                 n)  break
                     ;;
@@ -100,7 +100,7 @@ first_run(){
                                 ;;
                             n)  continue
                                 ;;
-                            y)  complete "$p"
+                            y)  finish "$p"
                                 ;;
                             *)  printf "$invi Please enter $(box y), $(box n), $(box h) or $(q2q) "
                         esac
@@ -117,7 +117,7 @@ first_run(){
         read -rp "  --> " p
         te1
         [ "${p,}" = "q" ] && exit 0
-        [ -f "$p/occ" ] && complete "$p" || echo "$(Pbg)  * I can not detect a Nextcloud installation in \"$p\" $(N)"
+        [ -f "$p/occ" ] && finish "$p" || echo "$(Pbg)  * I can not detect a Nextcloud installation in \"$p\" $(N)"
     done
 }
 # COMMENT -->
diff --git a/modules/tempfile b/modules/tempfile
--- a/modules/tempfile
+++ b/modules/tempfile
@@ -12,9 +12,32 @@ TEMPFILE_BASHLIB=:
 
 . <(lrequire binaries)
 
-# tempfile creation $1=u (--dry-run)
+# standard for root:
 : "${TMPDIR:=/tmp}"
+[[ "$TMPDIR" == '/' || ! -d "$TMPDIR" ]] && TMPDIR='/tmp'
+[ -d "$TMPDIR" ] || TMPDIR='/temp'
 
+# unprivileged users need their own writable tmp dir:
+if (( $(${BINARIES[id]} -u) )); then
+    TMPDIR="${TMPDIR%/}"
+    if (( $(${BINARIES[gawk]} -F/ '{print NF-1}' <<< "$TMPDIR") == 1 )) && [ -w "$TMPDIR" ]; then
+        TMPDIR="$TMPDIR/user-$(${BINARIES[id]} -u)"
+    elif [ ! -w "$TMPDIR" ]; then
+        TMPDIR="$(${BINARIES[gawk]} -F/ '{print "/"$2}' <<< "$TMPDIR")/user-$(${BINARIES[id]} -u)"
+    fi
+    [ -d "$TMPDIR" ] || q0 ${BINARIES[mkdir]} -m 755 "$TMPDIR"
+fi
+declare ttf
+ttf="$(${BINARIES[mktemp]} -p "$TMPDIR")"
+if [[ -n "$ttf" && -f "$ttf" ]]; then
+    ${BINARIES[rm]} -f -- "$ttf"
+else
+    echo -e "\e[31mERROR: TMPDIR '$TMPDIR' is not writable by user '$(${BINARIES[id]} -un)'\e[0m" >&2
+    [ -t 0 ] || exit 1
+fi
+unset ttf
+
+# tempfile creation $1=u (--dry-run)
 tf(){
     local arg t u='' mode=''
     for arg in $@; do
