feat: add list_installed_sapi function and --list-sapi option

diff --git a/modules/php-updater/linstalled b/modules/php-updater/linstalled
--- a/modules/php-updater/linstalled
+++ b/modules/php-updater/linstalled
@@ -28,6 +28,103 @@ ${LINSTALLED_BASHLIB:-false} || {
     . <(lrequire php/fpm)
     . <(lrequire $sin/tasks)
 
+    list_installed_sapi(){
+        cursor_ hide
+        local sapi pkg fullpath pv httpd modstring
+        local -a sockets
+        local -i c2 c3 i
+        c2=28 c3=74 SAPI_A2=() SAPI_FPM=()
+        populate_pkgs_by_dpkg_array
+        populate_httpd_ active
+
+        for i in "${!HTTPD_ACTIVE[@]}"; do mh "active-httpd - $(printf '%02d' $((i+1))): ${HTTPD_ACTIVE[i]}"; done
+
+        for pkg in "${PKGS_BY_DPKG[@]%%/*}"; do
+            if [[ "$pkg" =~ libapache2-mod-$phpvregex ]]; then
+                SAPI_A2[${pkg#libapache2-mod-php}]='installed'
+            elif [[ "$pkg" =~ $phpvregex-fpm ]]; then
+                pkg=${pkg#php}
+                SAPI_FPM[${pkg%-fpm}]='installed'
+            fi
+        done
+        if [[ "${HTTPD_ACTIVE[@]}" =~ apache2 ]] && (( ${#SAPI_A2[@]} )); then
+            if ! apache2_mpm prefork; then
+                modstring="$(listify C $(p_sort ${!SAPI_A2[@]}))"
+                bundle echo "$(xpf;format_string "$(R)The Apache2handler libapache2-mod-php is installed$(N) for $modstring, $(R)but the mpm_prefork module required by this SAPI is not loaded, so this SAPI is effectively inactive." 3;N)"
+                if apache2_mpm event; then
+                    bundle echo "$(ipf;format_string "$(Yi)Instead, the mpm_event module is loaded, which is required by the PHP Fast Process Manager (php-fpm). Only one mpm module can be loaded, they exclude each other." 3;N)"
+                fi
+                f
+            fi
+            for pv in $(p_sort ${!SAPI_A2[@]}); do
+                pkg="libapache2-mod-php$pv"
+                Y;echo "$(pf)$pkg";N
+                fullpath=$(eval echo \"\$\{${pkg//[.-]/_}\[0\]\}\")
+                o5;fO;echo -n "\\apache2handler$(O) $fullpath";N
+                if (( ${SERVER_STATUS[apache2]} > 2 )); then
+                    if [[ "${A2CONFFILES[@]}" =~ php$pv.conf && "${A2CONFFILES[@]}" =~ php$pv.load ]]; then
+                        SAPI_A2[$pv]='a'
+                        o $c3;lG;echo " <ACTIVE> loaded";N
+                    else
+                        SAPI_A2[$pv]='i'
+                        o $c3;W;echo " <<INACTIVE";N
+                    fi
+                else
+                    o $c3;W;W;echo " <<INACTIVE";N
+                fi
+            done
+            f
+        fi
+        if (( ${#SAPI_FPM[@]} )); then
+            if [[ "${HTTPD_ACTIVE[@]}" =~ apache2 ]] && ! apache2_mpm event; then
+                modstring="$(listify C $(p_sort ${!SAPI_FPM[@]}))"
+                bundle echo "$(xpf;format_string "$(R)The PHP Fast Process Manager (php-fpm) is installed$(N) for $modstring, $(R)but the mpm_event module for apache2 required by this SAPI is not loaded, so this SAPI is effectively inactive on the apache2 httpd." 3;N)"
+                bundle echo "  $(format_string "If a socket here shows as $(lG)<CONNECTED> apache2$(N) though, that means that at least one conf file from your apache2 webserver is configured to connect to that socket, which will fail." 3;N)"
+                if apache2_mpm prefork; then
+                    bundle echo "$(ipf;format_string "$(Yi)You can switch to fpm when you call this script again without arguments, it will detect the malconfiguration and offer you to switch the API" 3;N)"
+                    bundle echo "$(ipf;format_string "$(Yi)Instead, the mpm_prefork module is loaded, which is required by the Apache2handler. Only one mpm module can be loaded, they exclude each other." 3;N)"
+                else
+                    bundle echo "$(ipf;format_string "$(Yi)But since the mpm_prefork module is not loaded either, I will try to load the required modules for fpm to work.." 3;N)"
+                    php_fpm_module_ enable
+                fi
+                f
+            fi
+            for pv in $(p_sort ${!SAPI_FPM[@]}); do
+                sockets=()
+                pkg="php$pv-fpm"
+                sockets=($(ss -lx | awk '/'$pkg'/{print $5}'))
+                Y;echo "$(pf)$pkg";N
+                if (( ${#sockets[@]} )); then
+                    populate_httpd_ wk_enabled
+                    local connected_httpd socket
+                    for i in ${!sockets[@]}; do
+                        connected_httpd=''
+                        socket=${sockets[i]}
+                        if (( ${#WK_HTTPD_ENABLED[@]} )); then
+                            for httpd in ${WK_HTTPD_ENABLED[@]}; do
+                                case $httpd in
+                                    apache2)grep -qs "^[^#]*unix:$socket" ${A2CONFFILES[@]} || continue
+                                            ;;
+                                    nginx)  grep -qs "^[^#]*unix:$socket" ${NGINXCONFFILES[@]} || continue
+                                esac
+                                case ${SERVER_STATUS["$httpd"]} in
+                                    2)  connected_httpd="$connected_httpd $(N;GRAY)$httpd(inactive)$(N;lG)" ;;
+                                    3)  connected_httpd=" $httpd $connected_httpd"
+                                esac
+                            done
+                        fi
+                        o $((5+i));fO;printf "\\listening on unix socket$(O) $socket";N
+                        if [ -z "$connected_httpd" ]; then
+                            SAPI_FPM[$pv]='i';W;echo " <<NOT CONNECTED";N
+                        else
+                            SAPI_FPM[$pv]='a';lG;echo " <CONNECTED>$connected_httpd";N
+                        fi
+                    done
+                fi
+            done
+        fi
+    }
+
     list_installed(){
         cursor_ hide
         local arg sapi quiet only pkg plu fullpath mod pv httpd pkgmod
