refactor: rename and reorganize some global assoc arrays

diff --git a/modules/php-updater/tasks.d/change_sapi b/modules/php-updater/tasks.d/change_sapi
--- a/modules/php-updater/tasks.d/change_sapi
+++ b/modules/php-updater/tasks.d/change_sapi
@@ -15,11 +15,11 @@ change_sapi(){
         case "$1" in
             explain_the_diference)
                 separator
-                echo "- FYI: $(Y; format_string "diferences between the '$(dY)${SAPIDESCR[apache2]}$(Y)' and the '$(dY)${SAPIDESCR[fpm]}$(Y)':" 7)"
+                echo "- FYI: $(Y; format_string "diferences between the '$(dY)${DESCR[apache2]}$(Y)' and the '$(dY)${DESCR[fpm]}$(Y)':" 7)"
                 f
-                echo "$(o 6; GRAY; pf; format_string "the '$(dY)${SAPIDESCR[apache2]}$(GRAY)' integrates php as an apache2 module (package $(B)libapache2-mod-php$(GRAY)\$$(C)ver$(GRAY)) It is the default SAPI for apache2 and relies on the old but stable Multi-Processing Module (MPM) 'mpm-prefork' which is not particularly scalable and $(W)doesn't support http2" 9)"
+                echo "$(o 6; GRAY; pf; format_string "the '$(dY)${DESCR[apache2]}$(GRAY)' integrates php as an apache2 module (package $(B)libapache2-mod-php$(GRAY)\$$(C)ver$(GRAY)) It is the default SAPI for apache2 and relies on the old but stable Multi-Processing Module (MPM) 'mpm-prefork' which is not particularly scalable and $(W)doesn't support http2" 9)"
                 f
-                echo "$(o 6; GRAY; pf; format_string "the '$(dY)${SAPIDESCR[fpm]}$(GRAY)' (package $(B)php$(GRAY)\$$(C)ver$(B)-fpm$(GRAY)) is a little bit more complicated to administer, it relies on the more scalable threaded MPM 'mpm-event' which $(W)supports http2" 9)"
+                echo "$(o 6; GRAY; pf; format_string "the '$(dY)${DESCR[fpm]}$(GRAY)' (package $(B)php$(GRAY)\$$(C)ver$(B)-fpm$(GRAY)) is a little bit more complicated to administer, it relies on the more scalable threaded MPM 'mpm-event' which $(W)supports http2" 9)"
                 f
                 echo "$(o 7; Y; format_string "Due to the dependency on different multi-processing modules, of which only one can be loaded into the Apache core at a time, these two SAPIs are mutually exclusive in any use case with Apache2. Although both can be installed side by side, this is not recommended, especially if php-fpm is used, as after an update the apache2 module always tries to load the mpm it needs and may render the server inaccessible" 7; N)"
                 f
@@ -61,8 +61,8 @@ change_sapi(){
                 fi
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(ipf; format_string "The '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) is connected while the '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)php-fpm$(N) seems not to be connected." 3)"
-                ${bool[alt]} || { bundle echo "$(ipf; B; format_string "php$(dY)$active_a2_version$(B)-fpm$(N) is not installed, only $(listify B "$(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*php'${PHP[vregex]}'-fpm/{print $2}')"), $(message_ no_switch) '$(dY)${SAPIDESCR[fpm]}$(N)'." 3)"; }
+                bundle echo "$(ipf; format_string "The '$(dY)${DESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) is connected while the '$(dY)${DESCR[fpm]}$(N)' $(B)php-fpm$(N) seems not to be connected." 3)"
+                ${bool[alt]} || { bundle echo "$(ipf; B; format_string "php$(dY)$active_a2_version$(B)-fpm$(N) is not installed, only $(listify B "$(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*php'${PHP[vregex]}'-fpm/{print $2}')"), $(message_ no_switch) '$(dY)${DESCR[fpm]}$(N)'." 3)"; }
                 pf; Y; echo "Since php-fpm still consumes resources despite not being connected, you should either:"; N
                 f
                 bundle echo "$(es 10; button 1; pf)completely remove php*-fpm"
@@ -120,8 +120,8 @@ change_sapi(){
                 read_prompt="$(os; C)press $(button 1), $(button 2), $(button 3), $(button 4) or $(button q) to leave it unchanged$(N)"
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(ipf; format_string "It looks like the '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) is connected while the '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)php-fpm$(N) seems not to be connected." 3)"
-                bundle echo "$(xpf; R; format_string "$(message_ wrong_mpm) ('$(dY)prefork$(R)') required by the $(dY)${SAPIDESCR[apache2]}$(R), but the '$(dY)event$(R)' module which is required for operation with $(B)php-fpm$(R)." 3; N)"
+                bundle echo "$(ipf; format_string "It looks like the '$(dY)${DESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) is connected while the '$(dY)${DESCR[fpm]}$(N)' $(B)php-fpm$(N) seems not to be connected." 3)"
+                bundle echo "$(xpf; R; format_string "$(message_ wrong_mpm) ('$(dY)prefork$(R)') required by the $(dY)${DESCR[apache2]}$(R), but the '$(dY)event$(R)' module which is required for operation with $(B)php-fpm$(R)." 3; N)"
                 message_ misconfiguration
                 message_ yse
                 bundle echo "$(es 10; button 1; pf)switch apache2 from libapache2-mod-php to php*-fpm, without changing the loaded modules"
@@ -194,8 +194,8 @@ change_sapi(){
                 fi
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(ipf; format_string "The '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) is connected while the '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)libapache2-mod-php$(N) seems to be inactive." 3)"
-                ${bool[alt]} || { bundle echo "$(ipf; B; format_string "libapache2-mod-php$(dY)$active_fpm_version$(N) is not installed, only $(listify B "$(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*libapache2-mod-php'${PHP[vregex]}'/{print $2}' | ${X[sort]})"), $(message_ no_switch) '$(dY)${SAPIDESCR[apache2]}$(N)'." 3)"
+                bundle echo "$(ipf; format_string "The '$(dY)${DESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) is connected while the '$(dY)${DESCR[apache2]}$(N)' $(B)libapache2-mod-php$(N) seems to be inactive." 3)"
+                ${bool[alt]} || { bundle echo "$(ipf; B; format_string "libapache2-mod-php$(dY)$active_fpm_version$(N) is not installed, only $(listify B "$(${X[dpkg]} -l | ${X[gawk]} '/^[hiu]i.*libapache2-mod-php'${PHP[vregex]}'/{print $2}' | ${X[sort]})"), $(message_ no_switch) '$(dY)${DESCR[apache2]}$(N)'." 3)"
                 }
                 message_ yse
                 bundle echo "$(es 10; button 1; pf)completely remove libapache2-mod-php* (recommended)"
@@ -253,7 +253,7 @@ change_sapi(){
                 read_prompt="$(os; C)press $(button 1), $(button 2), $(button 3), $(button 4) or $(button q) to leave it unchanged$(N)"
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(ipf; format_string "It looks like the '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) is connected while the '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)libapache2-mod-php$(N) seems not to be connected." 3)"
+                bundle echo "$(ipf; format_string "It looks like the '$(dY)${DESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) is connected while the '$(dY)${DESCR[apache2]}$(N)' $(B)libapache2-mod-php$(N) seems not to be connected." 3)"
                 bundle echo "$(xpf; R; format_string "$(message_ wrong_mpm) ('$(dY)event$(R)') required by the $(dY)fpm SAPI$(R), but the '$(dY)prefork$(R)' module which is required for operation with $(B)libapache2-mod-php$(R)." 3; N)"
                 message_ misconfiguration
                 message_ yse
@@ -323,9 +323,9 @@ change_sapi(){
                 read_prompt="$(os; C)press $(button 1), $(button 2), $(button 3), $(button 4) or $(button q) to leave it unchanged$(N)"
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(xpf; format_string "It looks like both, the '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) and the '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) are connected to it." 3)"
+                bundle echo "$(xpf; format_string "It looks like both, the '$(dY)${DESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) and the '$(dY)${DESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) are connected to it." 3)"
                 message_ misconfiguration
-                bundle echo "$(ipf; Yi; format_string "The apache2 server has loaded the '$(dY)prefork$(Yi)' multi processing module required by the $(dY)${SAPIDESCR[apache2]}$(Yi) and the '$(dY)event$(Yi)' module which is required for operation with $(B)php-fpm$(Yi) is not loaded." 3; N)"
+                bundle echo "$(ipf; Yi; format_string "The apache2 server has loaded the '$(dY)prefork$(Yi)' multi processing module required by the $(dY)${DESCR[apache2]}$(Yi) and the '$(dY)event$(Yi)' module which is required for operation with $(B)php-fpm$(Yi) is not loaded." 3; N)"
                 message_ yse
                 bundle echo "$(es 10; button 1; pf)disconnect apache2 from php*-fpm, without changing the loaded modules"
                 f
@@ -393,9 +393,9 @@ change_sapi(){
                 read_prompt="$(os; C)press $(button 1), $(button 2), $(button 3), $(button 4) or $(button q) to leave it unchanged$(N)"
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(xpf; format_string "It looks like both, the '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) and the '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) are connected to it." 3)"
+                bundle echo "$(xpf; format_string "It looks like both, the '$(dY)${DESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) and the '$(dY)${DESCR[fpm]}$(N)' $(B)$active_fpm_pkg$(N) are connected to it." 3)"
                 message_ misconfiguration
-                bundle echo "$(ipf; Yi; format_string "The apache2 server has loaded the '$(dY)event$(Yi)' multi processing module required by the $(dY)${SAPIDESCR[fpm]}$(Yi) and the '$(dY)prefork$(Yi)' module which is required for operation with $(B)libapache2-mod-php$(Yi) is not loaded." 3; N)"
+                bundle echo "$(ipf; Yi; format_string "The apache2 server has loaded the '$(dY)event$(Yi)' multi processing module required by the $(dY)${DESCR[fpm]}$(Yi) and the '$(dY)prefork$(Yi)' module which is required for operation with $(B)libapache2-mod-php$(Yi) is not loaded." 3; N)"
                 message_ yse
                 bundle echo "$(es 10; button 1; pf)disconnect apache2 from libapache2-mod-php*, without changing the loaded modules"
                 f
@@ -460,7 +460,7 @@ change_sapi(){
                 read_prompt="$(os; C)press $(button 1), $(button 2) or $(button q) to leave it unchanged$(N)"
                 cursor_ hide
                 message_ explain_the_diference
-                bundle echo "$(ipf; format_string "The apache2 webserver is installed but inactive. The '$(dY)${SAPIDESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) is configured to be connected while the '$(dY)${SAPIDESCR[fpm]}$(N)' $(B)php-fpm$(N) is listening as well." 3)"
+                bundle echo "$(ipf; format_string "The apache2 webserver is installed but inactive. The '$(dY)${DESCR[apache2]}$(N)' $(B)$active_a2_pkg$(N) is configured to be connected while the '$(dY)${DESCR[fpm]}$(N)' $(B)php-fpm$(N) is listening as well." 3)"
                 message_ yse
                 bundle echo "$(es 10; button 1; pf)completely remove libapache2-mod-php*"
                 f
